# Generated by Django 5.2 on 2025-05-12 09:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("larpmanager", "0004_clean_features_writing"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CharacterAnswer",
            new_name="WritingAnswer",
        ),
        migrations.RenameModel(
            old_name="CharacterChoice",
            new_name="WritingChoice",
        ),
        migrations.RenameModel(
            old_name="CharacterOption",
            new_name="WritingOption",
        ),
        migrations.RenameModel(
            old_name="CharacterQuestion",
            new_name="WritingQuestion",
        ),
    ]
