# Generated by Django 5.2 on 2025-05-12 09:33

from django.db import migrations, models
from typing import Any


def copy_values(apps: Any, schema_editor: Any) -> Any:
    WritingChoice = apps.get_model("larpmanager", "WritingChoice")
    WritingAnswer = apps.get_model("larpmanager", "WritingAnswer")

    for el in WritingChoice.objects.all():
        el.element_id = el.character_id
        el.save()

    for el in WritingAnswer.objects.all():
        el.element_id = el.character_id
        el.save()


class Migration(migrations.Migration):
    dependencies = [
        ("larpmanager", "0005_rename_character_form_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="writinganswer",
            name="element_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="writingchoice",
            name="element_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RunPython(copy_values),
    ]
