# Generated by Django 5.2 on 2025-05-12 11:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("larpmanager", "0006_writinganswer_element_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="writinganswer",
            name="character",
        ),
        migrations.RemoveField(
            model_name="writingchoice",
            name="character",
        ),
    ]
