# Generated by Django 5.2 on 2025-05-13 12:33

from django.db import migrations, models

from larpmanager.models.form import QuestionApplicable


def set_default(apps, schema_editor):
    WritingQuestion = apps.get_model("larpmanager", "WritingQuestion")

    for el in WritingQuestion.objects.all():
        el.applicable = QuestionApplicable.CHARACTER
        el.save()


class Migration(migrations.Migration):
    dependencies = [
        ("larpmanager", "0007_remove_character_writing_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="writingquestion",
            name="applicable",
            field=models.CharField(
                default="",
                help_text="Select the types of writing elements that this question applies to.",
                max_length=20,
                null=True,
                verbose_name="Applicable",
            ),
        ),
        migrations.RunPython(set_default),
    ]
