# Generated by Django 5.2 on 2025-05-14 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("larpmanager", "0008_writingquestion_applicable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="writingquestion",
            name="applicable",
            field=models.CharField(
                default="c",
                help_text="Select the types of writing elements that this question applies to.",
                max_length=20,
                null=True,
                verbose_name="Applicable",
            ),
        ),
        migrations.AlterField(
            model_name="writingquestion",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="form_questions", to="larpmanager.event"
            ),
        ),
    ]
