# Generated by Django 5.1 on 2025-05-15 11:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("larpmanager", "0010_clean_features_registration_form"),
    ]

    operations = [
        migrations.AlterField(
            model_name="writingquestion",
            name="applicable",
            field=models.CharField(
                blank=True,
                default="c",
                help_text="Select the types of writing elements that this question applies to.",
                max_length=20,
                null=True,
                verbose_name="Applicable",
            ),
        ),
        migrations.AlterField(
            model_name="writingquestion",
            name="editable",
            field=models.CharField(
                blank=True,
                default="",
                help_text="This field can be edited by the player only when the character is in one of the selected statuses",
                max_length=20,
                null=True,
                verbose_name="Editable",
            ),
        ),
    ]
