# Generated by Django 5.1 on 2025-05-20 07:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("larpmanager", "0011_alter_writingquestion_applicable_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registrationticket",
            name="tier",
            field=models.CharField(
                choices=[
                    ("b", "Standard"),
                    ("l", "Lottery"),
                    ("w", "Waiting"),
                    ("f", "Filler"),
                    ("r", "Reduced"),
                    ("p", "Patron"),
                    ("t", "Staff"),
                    ("n", "NPC"),
                    ("c", "Collaborator"),
                    ("s", "Seller"),
                ],
                default="b",
                help_text="Type of ticket",
                max_length=1,
            ),
        ),
    ]
