# Generated by Django 5.2 on 2025-05-23 18:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("larpmanager", "0012_alter_registrationticket_tier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="writingoption",
            name="dependents",
            field=models.ManyToManyField(
                blank=True,
                help_text="Indicates other options that must be selected for this option to be selectable",
                related_name="dependents_inv",
                to="larpmanager.writingoption",
                verbose_name="Prerequisites",
            ),
        ),
    ]
