# Generated by Django 5.1 on 2025-05-26 08:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("larpmanager", "0015_alter_registrationquestion_typ_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registrationquestion",
            name="status",
            field=models.CharField(
                choices=[("o", "Optional"), ("m", "Mandatory"), ("d", "Disabled"), ("h", "Hidden")],
                default="o",
                help_text="Optional: The question is shown, and can be filled by the player. Mandatory: The question needs to be filled by the player. Disabled: The question is shown, but cannot be changed by the player. Hidden: The question is not shown to the player.",
                max_length=1,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="writingquestion",
            name="status",
            field=models.CharField(
                choices=[("o", "Optional"), ("m", "Mandatory"), ("d", "Disabled"), ("h", "Hidden")],
                default="o",
                help_text="Optional: The question is shown, and can be filled by the player. Mandatory: The question needs to be filled by the player. Disabled: The question is shown, but cannot be changed by the player. Hidden: The question is not shown to the player.",
                max_length=1,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="writingquestion",
            name="visibility",
            field=models.CharField(
                choices=[("s", "Searchable"), ("c", "Public"), ("e", "Private"), ("h", "Hidden")],
                default="e",
                help_text="Searchable: Characters can be filtered according to this question. Public: The answer to this question is publicly visible. Private: The answer to this question is only visible to the player. Hidden: The answer is hidden to all players.",
                max_length=1,
                verbose_name="Visibility",
            ),
        ),
    ]
