# Generated by Django 5.1 on 2025-05-27 11:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("larpmanager", "0016_alter_registrationquestion_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faction",
            name="typ",
            field=models.CharField(
                choices=[("s", "Primary"), ("t", "Transversal"), ("g", "Secret")],
                default="s",
                help_text="Primary: main grouping / affiliation for characters. Transversal: secondary grouping across primary factions. Secret: hidden faction visible only to assigned characters",
                max_length=1,
                verbose_name="Type",
            ),
        ),
    ]
