# Generated by Django 5.1 on 2025-05-27 16:14

from typing import Any

from django.db import migrations, models


def clean_preview(apps: Any, schema_editor: Any) -> Any:
    # create question and answer to save data in "preview"
    Character = apps.get_model("larpmanager", "Character")
    WritingQuestion = apps.get_model("larpmanager", "WritingQuestion")
    WritingAnswer = apps.get_model("larpmanager", "WritingAnswer")
    for char in Character.objects.exclude(preview="").exclude(preview__isnull=True):
        (que, cr) = WritingQuestion.objects.get_or_create(event=char.event, typ="e", display="Preview")
        (ca, cr) = WritingAnswer.objects.get_or_create(element_id=char.id, question=que)
        ca.text = char.preview
        ca.save()
    WritingQuestion.objects.filter(typ="preview").delete()

    # Delete feature
    Feature = apps.get_model("larpmanager", "Feature")
    Feature.objects.filter(id__in=[122]).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("larpmanager", "0018_clean_features_fields"),
    ]

    operations = [
        migrations.RunPython(clean_preview),
        migrations.RemoveField(
            model_name="character",
            name="preview",
        ),
        migrations.RemoveField(
            model_name="faction",
            name="preview",
        ),
        migrations.RemoveField(
            model_name="handout",
            name="preview",
        ),
        migrations.RemoveField(
            model_name="plot",
            name="preview",
        ),
        migrations.RemoveField(
            model_name="prologue",
            name="preview",
        ),
        migrations.RemoveField(
            model_name="prologuetype",
            name="preview",
        ),
        migrations.RemoveField(
            model_name="quest",
            name="preview",
        ),
        migrations.RemoveField(
            model_name="questtype",
            name="preview",
        ),
        migrations.RemoveField(
            model_name="speedlarp",
            name="preview",
        ),
        migrations.RemoveField(
            model_name="textversion",
            name="preview",
        ),
        migrations.RemoveField(
            model_name="trait",
            name="preview",
        ),
        migrations.AlterField(
            model_name="registrationquestion",
            name="typ",
            field=models.CharField(
                choices=[
                    ("s", "Single choice"),
                    ("m", "Multiple choice"),
                    ("t", "Single-line text"),
                    ("p", "Multi-line text"),
                    ("e", "Advanced text editor"),
                    ("name", "Name"),
                    ("teaser", "Presentation"),
                    ("text", "Sheet"),
                    ("cover", "Cover"),
                    ("faction", "Factions"),
                    ("title", "Title"),
                    ("mirror", "Mirror"),
                    ("hide", "Hide"),
                    ("progress", "Progress"),
                    ("assigned", "Assigned"),
                ],
                default="s",
                help_text="Question type",
                max_length=10,
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="writingquestion",
            name="typ",
            field=models.CharField(
                choices=[
                    ("s", "Single choice"),
                    ("m", "Multiple choice"),
                    ("t", "Single-line text"),
                    ("p", "Multi-line text"),
                    ("e", "Advanced text editor"),
                    ("name", "Name"),
                    ("teaser", "Presentation"),
                    ("text", "Sheet"),
                    ("cover", "Cover"),
                    ("faction", "Factions"),
                    ("title", "Title"),
                    ("mirror", "Mirror"),
                    ("hide", "Hide"),
                    ("progress", "Progress"),
                    ("assigned", "Assigned"),
                ],
                default="s",
                help_text="Question type",
                max_length=10,
                verbose_name="Type",
            ),
        ),
    ]
