# Generated by Django 5.1 on 2025-05-27 16:41

from django.db import migrations

from larpmanager.models.form import QuestionStatus


def clean_cocreation(apps, schema_editor):
    # create question and answer to save data in "cocreation"
    WritingQuestion = apps.get_model("larpmanager", "WritingQuestion")
    WritingAnswer = apps.get_model("larpmanager", "WritingAnswer")
    RunText = apps.get_model("larpmanager", "RunText")
    for element in RunText.objects.all():
        event = element.run.event
        if element.first:
            (que, cr) = WritingQuestion.objects.get_or_create(
                event=event, typ="e", display="Cocreation Question", status=QuestionStatus.DISABLED
            )
            (ca, cr) = WritingAnswer.objects.get_or_create(element_id=element.eid, question=que)
            ca.text = element.first
            ca.save()

        if element.second:
            (que, cr) = WritingQuestion.objects.get_or_create(event=event, typ="e", display="Cocreation Answer")
            (ca, cr) = WritingAnswer.objects.get_or_create(element_id=element.eid, question=que)
            ca.text = element.second
            ca.save()

    # Delete feature
    Feature = apps.get_model("larpmanager", "Feature")
    Feature.objects.filter(id__in=[153]).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("larpmanager", "0019_remove_character_preview_remove_faction_preview_and_more"),
    ]

    operations = [
        migrations.RunPython(clean_cocreation),
        migrations.DeleteModel(
            name="RunText",
        ),
    ]
