# Generated by Django 5.1 on 2025-05-29 07:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("larpmanager", "0021_association_nationality_featuremodule_nationality"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="associationconfig",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="characterconfig",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="runconfig",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="characterconfig",
            constraint=models.UniqueConstraint(
                fields=("character", "name", "deleted"), name="unique_character_config_with_optional"
            ),
        ),
        migrations.AddConstraint(
            model_name="characterconfig",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted", None)),
                fields=("character", "name"),
                name="unique_character_config_without_optional",
            ),
        ),
        migrations.AddConstraint(
            model_name="runconfig",
            constraint=models.UniqueConstraint(
                fields=("run", "name", "deleted"), name="unique_run_config_with_optional"
            ),
        ),
        migrations.AddConstraint(
            model_name="runconfig",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted", None)), fields=("run", "name"), name="unique_run_config_without_optional"
            ),
        ),
    ]
