# Generated by Django 5.1 on 2025-05-28 09:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("larpmanager", "0021_association_nationality_featuremodule_nationality"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="registration",
            name="info",
        ),
    ]
