# Generated by Django 5.1 on 2025-05-29 15:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("larpmanager", "0022_alter_associationconfig_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="textversion",
            name="teaser",
        ),
    ]
