# Generated by Django 5.1 on 2025-06-05 09:01

from django.db import migrations, models

import larpmanager.models.utils


class Migration(migrations.Migration):
    dependencies = [
        ("larpmanager", "0023_remove_textversion_teaser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="association",
            name="profile",
            field=models.ImageField(
                blank=True,
                help_text="Optional logo image - you can upload a file of any size, it will be automatically resized",
                max_length=500,
                null=True,
                upload_to=larpmanager.models.utils.UploadToPathAndRename("association/"),
                verbose_name="Logo",
            ),
        ),
    ]
