# Generated by Django 5.2.3 on 2025-06-18 09:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("larpmanager", "0025_delete_larpmanagerhowto_remove_feature_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="assocpermission",
            name="descr",
            field=models.CharField(default="", max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="eventpermission",
            name="descr",
            field=models.CharField(default="", max_length=1000),
            preserve_default=False,
        ),
    ]
