# Generated by Django 5.2 on 2025-06-21 19:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("larpmanager", "0026_assocpermission_descr_eventpermission_descr"),
    ]

    operations = [
        migrations.AddField(
            model_name="feature",
            name="after_link",
            field=models.TextField(default="", max_length=100, blank=True, null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="feature",
            name="after_text",
            field=models.TextField(default="", max_length=300, blank=True, null=True),
            preserve_default=False,
        ),
    ]
