# Generated by Django 5.2.3 on 2025-06-23 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("larpmanager", "0026_assocpermission_descr_eventpermission_descr"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventtext",
            name="typ",
            field=models.CharField(
                choices=[
                    ("i", "Character sheet intro"),
                    ("t", "Terms and conditions"),
                    ("r", "Registration form"),
                    ("s", "Search"),
                    ("g", "Registration mail"),
                    ("a", "Mail assignment"),
                    ("cs", "Proposed character"),
                    ("ca", "Approved character"),
                    ("cr", "Character review"),
                ],
                max_length=2,
                verbose_name="Type",
            ),
        ),
    ]
