# Generated by Django 5.2.3 on 2025-06-24 12:02

import datetime

import django.db.models.deletion
import model_clone.mixin
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("larpmanager", "0028_feature_after_link_feature_after_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssociationSkin",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("deleted", models.DateTimeField(db_index=True, editable=False, null=True)),
                ("deleted_by_cascade", models.BooleanField(default=False, editable=False)),
                ("created", models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("domain", models.CharField(max_length=100)),
                ("default_css", models.CharField(blank=True, max_length=1000)),
                ("default_nation", models.CharField(blank=True, choices=[("it", "Italy")], max_length=2, null=True)),
                (
                    "default_features",
                    models.ManyToManyField(blank=True, related_name="skins", to="larpmanager.feature"),
                ),
            ],
            options={
                "ordering": ["-updated"],
                "abstract": False,
            },
            bases=(model_clone.mixin.CloneMixin, models.Model),
        ),
        migrations.AddField(
            model_name="association",
            name="skin",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="larpmanager.associationskin"
            ),
        ),
    ]
