# Generated by Django 5.2 on 2025-06-25 23:19

from django.db import migrations, models

import larpmanager.models.utils


class Migration(migrations.Migration):
    dependencies = [
        ("larpmanager", "0028_feature_after_link_feature_after_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="profile",
            field=models.ImageField(
                blank=True,
                help_text="Upload your portrait photo. It will be shown to other players to help recognize you in the event. Choose a photo that you would put in an official document (in which you are alone, centered on your face).",
                max_length=500,
                null=True,
                upload_to=larpmanager.models.utils.UploadToPathAndRename("member/"),
                verbose_name="Portrait",
            ),
        ),
    ]
