# Generated by Django 5.2.3 on 2025-06-27 08:48

import datetime

import django.core.validators
import django.db.models.deletion
import model_clone.mixin
from django.db import migrations, models


def create_default_skin(apps, schema_editor):
    AssociationSkin = apps.get_model("larpmanager", "AssociationSkin")
    AssociationSkin.objects.create(
        id=1,
        name="LarpManager",
        #domain="larpmanager.com",
        domain="larpmanager.cpularp.com",
        default_mandatory_fields="",
        default_optional_fields="",
        default_css="",
        default_nation="it",
    )


def trigger_save_assocs(apps, schema_editor):
    Association = apps.get_model("larpmanager", "Association")
    for assoc in Association.objects.all():
        assoc.save()


class Migration(migrations.Migration):
    dependencies = [
        ("larpmanager", "0029_alter_member_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="association",
            name="name",
            field=models.CharField(help_text="Complete name of the Organization", max_length=100),
        ),
        migrations.AlterField(
            model_name="association",
            name="slug",
            field=models.CharField(
                db_index=True,
                help_text="The subdomain identifier - Only lowercase characters and numbers are allowed, no spaces or symbols",
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[0-9a-z_-]*$", "Only characters allowed are: 0-9, a-z, _, -."
                    )
                ],
                verbose_name="URL identifier",
            ),
        ),
        migrations.CreateModel(
            name="AssociationSkin",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("deleted", models.DateTimeField(db_index=True, editable=False, null=True)),
                ("deleted_by_cascade", models.BooleanField(default=False, editable=False)),
                ("created", models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("domain", models.CharField(max_length=100)),
                ("default_mandatory_fields", models.CharField(blank=True, max_length=1000)),
                ("default_optional_fields", models.CharField(blank=True, max_length=1000)),
                ("default_css", models.CharField(blank=True, max_length=1000)),
                ("default_nation", models.CharField(blank=True, choices=[("it", "Italy")], max_length=2, null=True)),
                (
                    "default_features",
                    models.ManyToManyField(blank=True, related_name="skins", to="larpmanager.feature"),
                ),
            ],
            options={
                "ordering": ["-updated"],
                "abstract": False,
            },
            bases=(model_clone.mixin.CloneMixin, models.Model),
        ),
        migrations.RunPython(create_default_skin, reverse_code=migrations.RunPython.noop),
        migrations.AddField(
            model_name="association",
            name="skin",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="larpmanager.associationskin"
            ),
        ),
        migrations.RunPython(trigger_save_assocs, reverse_code=migrations.RunPython.noop),
    ]
