# Generated by Django 5.2.3 on 2025-07-01 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("larpmanager", "0030_alter_association_name_alter_association_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="association",
            name="skin",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="larpmanager.associationskin"),
        ),
    ]
