# Generated by Django 5.2.3 on 2025-07-01 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("larpmanager", "0030_alter_association_name_alter_association_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="association",
            name="skin",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="larpmanager.associationskin"),
        ),
        migrations.AlterField(
            model_name="writingquestion",
            name="applicable",
            field=models.CharField(
                choices=[("c", "character"), ("p", "plot"), ("f", "faction")],
                default="c",
                help_text="Select the types of writing elements that this question applies to.",
                max_length=1,
                verbose_name="Applicable",
            ),
        ),
    ]
