# Generated by Django 5.2.3 on 2025-07-02 09:01

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("larpmanager", "0031_alter_association_skin_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="abilitypx",
            name="descr",
            field=tinymce.models.HTMLField(blank=True, max_length=5000, null=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="abilitypx",
            name="typ",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="abilities",
                to="larpmanager.abilitytypepx",
                verbose_name="Type",
            ),
        ),
    ]
