# Generated by Django 5.2.3 on 2025-07-03 09:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("larpmanager", "0032_alter_abilitypx_descr_alter_abilitypx_typ"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountingitemexpense",
            name="balance",
            field=models.CharField(
                choices=[
                    ("1", "Raw materials, auxiliaries, consumables and goods"),
                    ("2", "Services"),
                    ("3", "Use of third party assets"),
                    ("4", "Personal"),
                    ("5", "Miscellaneous operating expenses"),
                ],
                help_text="Indicate how spending is allocated at the budget level",
                max_length=1,
                null=True,
                verbose_name="Balance",
            ),
        ),
        migrations.AlterField(
            model_name="accountingitemoutflow",
            name="balance",
            field=models.CharField(
                choices=[
                    ("1", "Raw materials, auxiliaries, consumables and goods"),
                    ("2", "Services"),
                    ("3", "Use of third party assets"),
                    ("4", "Personal"),
                    ("5", "Miscellaneous operating expenses"),
                ],
                help_text="Indicate how spending is allocated at the budget level",
                max_length=1,
                null=True,
                verbose_name="Balance",
            ),
        ),
        migrations.AlterField(
            model_name="badge",
            name="cod",
            field=models.CharField(
                help_text="Unique code for internal use - not visible. Indicate a string without spaces or strange symbols",
                max_length=30,
                verbose_name="Code",
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="accessibility",
            field=models.CharField(
                blank=True,
                help_text="Fill in this field if you have accessibility needs",
                max_length=500,
                null=True,
                verbose_name="Accessibility",
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="newsletter",
            field=models.CharField(
                choices=[
                    ("a", "Yes, keep me posted!"),
                    ("o", "Only really important communications"),
                    ("n", "No, I don't want updates"),
                ],
                default="a",
                help_text="Do you wish to be always updated on our events?",
                max_length=1,
                null=True,
                verbose_name="Newsletter",
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="newsletter",
            field=models.CharField(
                choices=[
                    ("a", "Yes, keep me posted!"),
                    ("o", "Only really important communications"),
                    ("n", "No, I don't want updates"),
                ],
                default="a",
                help_text="Do you wish to be always updated on our events?",
                max_length=1,
                verbose_name="Newsletter",
            ),
        ),
        migrations.AlterField(
            model_name="problem",
            name="assigned",
            field=models.CharField(help_text="Who takes it upon themselves to solve it", max_length=100),
        ),
        migrations.AlterField(
            model_name="problem",
            name="what",
            field=models.TextField(help_text="Describe exactly what risks it poses to the game", verbose_name="What"),
        ),
        migrations.AlterField(
            model_name="problem",
            name="when",
            field=models.TextField(help_text="Describe exactly what condition it is in", verbose_name="When"),
        ),
        migrations.AlterField(
            model_name="problem",
            name="where",
            field=models.TextField(help_text="Describe exactly at which point it occurs", verbose_name="Where"),
        ),
        migrations.AlterField(
            model_name="problem",
            name="who",
            field=models.TextField(help_text="Describe exactly which players are involved", verbose_name="Who"),
        ),
        migrations.AlterField(
            model_name="shuttleservice",
            name="address",
            field=models.TextField(
                help_text="Indicate as precisely as possible where to pick you up", verbose_name="Address"
            ),
        ),
        migrations.AlterField(
            model_name="writingquestion",
            name="applicable",
            field=models.CharField(
                choices=[("c", "character"), ("p", "plot"), ("f", "faction")],
                default="c",
                help_text="Select the types of writing elements that this question applies to",
                max_length=1,
                verbose_name="Applicable",
            ),
        ),
    ]
