# Generated by Django 5.1 on 2025-05-27 16:41

from django.db import migrations


def clean_features(apps, schema_editor):
    # Delete features
    Feature = apps.get_model("larpmanager", "Feature")
    Feature.objects.filter(id__in=[145, 95, 56, 88, 34]).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("larpmanager", "0033_alter_accountingitemexpense_balance_and_more"),
    ]

    operations = [
        migrations.RunPython(clean_features),
    ]
