# Generated by Django 5.2.3 on 2025-07-09 09:29

from typing import Any

from django.db import migrations


def clean_features(apps: Any, schema_editor: Any) -> Any:
    # Delete features
    Feature = apps.get_model("larpmanager", "Feature")
    Feature.objects.filter(id__in=[113]).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("larpmanager", "0034_clean_features"),
    ]

    operations = [
        migrations.RunPython(clean_features),
        migrations.RemoveField(
            model_name="event",
            name="lang",
        ),
        migrations.RemoveField(
            model_name="registrationoption",
            name="price_staff",
        ),
    ]
