# Generated by Django 5.2.3 on 2025-07-14 13:58

from django.db import migrations


def clean_permission(apps, schema_editor):
    # Delete features
    EventPermission = apps.get_model("larpmanager", "EventPermission")
    EventPermission.objects.filter(id__in=[73]).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("larpmanager", "0038_alter_event_background_alter_event_cover_and_more"),
    ]

    operations = [
        migrations.RunPython(clean_permission),
    ]
