# Generated by Django 5.2 on 2025-07-16 22:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("larpmanager", "0039_clean_reload"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="featuremodule",
            name="descr",
        ),
        migrations.RemoveField(
            model_name="featuremodule",
            name="default",
        ),
        migrations.AddField(
            model_name="featuremodule",
            name="icon",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="feature",
            name="hidden",
            field=models.BooleanField(default=False),
        ),
    ]
