# Generated by Django 5.2 on 2025-07-17 19:26

import datetime

import django.db.models.deletion
import model_clone.mixin
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("larpmanager", "0040_remove_featuremodule_descr"),
    ]

    operations = [
        migrations.CreateModel(
            name="MemberConfig",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("deleted", models.DateTimeField(db_index=True, editable=False, null=True)),
                ("deleted_by_cascade", models.BooleanField(default=False, editable=False)),
                ("created", models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150)),
                ("value", models.CharField(max_length=1000)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="configs", to="larpmanager.member"
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["member", "name"], name="larpmanager_member__85b005_idx")],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("member", "name", "deleted"), name="unique_member_config_with_optional"
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("deleted", None)),
                        fields=("member", "name"),
                        name="unique_member_config_without_optional",
                    ),
                ],
            },
            bases=(model_clone.mixin.CloneMixin, models.Model),
        ),
    ]
