# Generated by Django 5.2 on 2025-07-19 11:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("larpmanager", "0041_memberconfig"),
    ]

    operations = [
        migrations.AlterField(
            model_name="association",
            name="main_mail",
            field=models.EmailField(
                blank=True,
                help_text="(Optional) Indicate an organization contact address for sending communications",
                max_length=254,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="association",
            name="nationality",
            field=models.CharField(
                blank=True,
                choices=[("it", "Italy")],
                help_text="(Optional) Indicate the organization nationality to activate nation-specific features",
                max_length=2,
                null=True,
                verbose_name="Nationality",
            ),
        ),
    ]
