# Generated by Django 5.2.3 on 2025-07-22 12:50

from django.db import migrations, models

import larpmanager.models.utils


class Migration(migrations.Migration):
    dependencies = [
        ("larpmanager", "0043_alter_association_nationality"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faction",
            name="order",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="registrationoption",
            name="details",
            field=models.CharField(
                blank=True,
                help_text="Optional – Additional information about the option, displayed below the question",
                max_length=500,
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="registrationoption",
            name="display",
            field=models.CharField(
                help_text="Option name, displayed within the question (keep it short)",
                max_length=170,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="registrationoption",
            name="max_available",
            field=models.IntegerField(
                default=0,
                help_text="Optional – Maximum number of times it can be selected across all registrations (0 = unlimited)",
                verbose_name="Maximum number",
            ),
        ),
        migrations.AlterField(
            model_name="registrationoption",
            name="order",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="registrationoption",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Optional – Amount added to the registration fee if selected (0 = no extra cost)",
                max_digits=10,
                verbose_name="Price",
            ),
        ),
        migrations.AlterField(
            model_name="registrationquestion",
            name="description",
            field=models.CharField(
                blank=True,
                help_text="Optional - Extended description (displayed in small gray text)",
                max_length=1000,
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="registrationquestion",
            name="display",
            field=models.CharField(help_text="Question name (keep it short)", max_length=100, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="registrationquestion",
            name="factions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Optional - If you select one (or more) factions, the question will only be shown to players with characters in all chosen factions",
                related_name="registration_questions",
                to="larpmanager.faction",
                verbose_name="Faction list",
            ),
        ),
        migrations.AlterField(
            model_name="registrationquestion",
            name="max_length",
            field=models.IntegerField(
                default=0,
                help_text="Optional - For text questions, maximum number of characters; For multiple options, maximum number of options (0 = no limit)",
                verbose_name="Maximum length",
            ),
        ),
        migrations.AlterField(
            model_name="registrationquestion",
            name="order",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="registrationquestion",
            name="profile",
            field=models.ImageField(
                blank=True,
                help_text="Optional - Image displayed within the question",
                max_length=500,
                null=True,
                upload_to=larpmanager.models.utils.UploadToPathAndRename("reg_questions/"),
                verbose_name="Image",
            ),
        ),
        migrations.AlterField(
            model_name="registrationsection",
            name="order",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="registrationticket",
            name="casting_priority",
            field=models.IntegerField(
                default=1,
                help_text="Optional – Casting priority granted by this option (e.g., 1 = low, 5 = medium, 25 = high)",
            ),
        ),
        migrations.AlterField(
            model_name="registrationticket",
            name="details",
            field=models.CharField(
                blank=True,
                help_text="Optional - Extended description (displayed in small gray text)",
                max_length=500,
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="registrationticket",
            name="giftable",
            field=models.BooleanField(
                default=False, help_text="Optional - Indicates whether the ticket can be gifted to other players"
            ),
        ),
        migrations.AlterField(
            model_name="registrationticket",
            name="max_available",
            field=models.IntegerField(
                default=0,
                help_text="Optional – Maximum number of times it can be requested across all signups (0 = unlimited)",
            ),
        ),
        migrations.AlterField(
            model_name="registrationticket",
            name="name",
            field=models.CharField(help_text="Ticket name (keep it short)", max_length=50, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="registrationticket",
            name="order",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="writingoption",
            name="details",
            field=models.CharField(
                blank=True,
                help_text="Optional – Additional information about the option, displayed below the question",
                max_length=500,
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="writingoption",
            name="display",
            field=models.CharField(
                help_text="Option name, displayed within the question (keep it short)",
                max_length=50,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="writingoption",
            name="max_available",
            field=models.IntegerField(
                default=0,
                help_text="Optional – Maximum number of times it can be selected across all characters (0 = unlimited)",
            ),
        ),
        migrations.AlterField(
            model_name="writingoption",
            name="order",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="writingquestion",
            name="description",
            field=models.CharField(
                blank=True,
                help_text="Optional - Extended description (displayed in small gray text)",
                max_length=1000,
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="writingquestion",
            name="display",
            field=models.CharField(help_text="Question name (keep it short)", max_length=100, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="writingquestion",
            name="order",
            field=models.IntegerField(default=0),
        ),
    ]
