# Generated by Django 5.2.3 on 2025-07-23 09:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("larpmanager", "0044_alter_faction_order_alter_registrationoption_details_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="association",
            name="demo",
            field=models.BooleanField(default=False),
        ),
    ]
