# Generated by Django 5.2 on 2025-07-25 16:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("larpmanager", "0045_association_demo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faction",
            name="typ",
            field=models.CharField(
                choices=[("s", "Primary"), ("t", "Transversal"), ("g", "Secret")],
                default="s",
                max_length=1,
                verbose_name="Type",
            ),
        ),
    ]
