# Generated by Django 5.2 on 2025-07-27 20:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("larpmanager", "0046_alter_faction_typ"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registrationquestion",
            name="status",
            field=models.CharField(
                choices=[("o", "Optional"), ("m", "Mandatory"), ("d", "Disabled"), ("h", "Hidden")],
                default="o",
                max_length=1,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="writingquestion",
            name="status",
            field=models.CharField(
                choices=[("o", "Optional"), ("m", "Mandatory"), ("d", "Disabled"), ("h", "Hidden")],
                default="o",
                max_length=1,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="writingquestion",
            name="visibility",
            field=models.CharField(
                choices=[("s", "Searchable"), ("c", "Public"), ("e", "Private"), ("h", "Hidden")],
                default="e",
                max_length=1,
                verbose_name="Visibility",
            ),
        ),
    ]
