# Generated by Django 5.2 on 2025-07-29 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("larpmanager", "0047_alter_registrationquestion_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quest",
            name="open_show",
        ),
        migrations.RemoveField(
            model_name="trait",
            name="keywords",
        ),
        migrations.RemoveField(
            model_name="trait",
            name="role",
        ),
        migrations.RemoveField(
            model_name="trait",
            name="safety",
        ),
        migrations.AlterField(
            model_name="quest",
            name="typ",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quests",
                to="larpmanager.questtype",
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="trait",
            name="traits",
            field=models.ManyToManyField(blank=True, to="larpmanager.trait"),
        ),
        migrations.AlterField(
            model_name="writingquestion",
            name="applicable",
            field=models.CharField(
                choices=[("c", "character"), ("p", "plot"), ("f", "faction"), ("q", "quest"), ("t", "trait")],
                default="c",
                help_text="Select the types of writing elements that this question applies to",
                max_length=1,
                verbose_name="Applicable",
            ),
        ),
    ]
