# Generated by Django 5.2 on 2025-07-29 12:54

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("larpmanager", "0048_remove_quest_open_show_remove_trait_keywords_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="association",
            name="sec_rgb",
            field=colorfield.fields.ColorField(
                blank=True,
                default=None,
                help_text="Indicate the color that will be used to highlight texts",
                image_field=None,
                max_length=25,
                null=True,
                samples=None,
                verbose_name="Color highlight",
            ),
        ),
    ]
