# Generated by Django 5.2.3 on 2025-07-31 11:28

from django.db import migrations

from larpmanager.models.utils import my_uuid_short


def gen_uuid(apps, schema_editor):
    Character = apps.get_model("larpmanager", "Character")
    for row in Character.objects.all():
        row.access_token = my_uuid_short()
        row.save(update_fields=["access_token"])


class Migration(migrations.Migration):
    dependencies = [
        ("larpmanager", "0050_character_access_token"),
    ]

    operations = [
        migrations.RunPython(gen_uuid),
    ]
