# Generated by Django 5.2.3 on 2025-07-31 11:28

from django.db import migrations, models

import larpmanager


class Migration(migrations.Migration):
    dependencies = [
        ("larpmanager", "0051_set_character_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="access_token",
            field=models.CharField(
                db_index=True,
                default=larpmanager.models.utils.my_uuid_short,
                help_text="\n            Allows external access to this character through a secret URL \n            (change the code if it has been shared with the wrong people)\n        ",
                max_length=12,
                unique=True,
                verbose_name="External access code",
            ),
        ),
    ]
