# Generated by Django 5.2.3 on 2025-07-31 11:42

from django.db import migrations, models

import larpmanager.models.utils


class Migration(migrations.Migration):
    dependencies = [
        ("larpmanager", "0052_set_unique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="access_token",
            field=models.CharField(
                db_index=True,
                default=larpmanager.models.utils.my_uuid_short,
                help_text="Allows external access to this character through a secret URL (change the code if it has been shared with the wrong people)",
                max_length=12,
                unique=True,
                verbose_name="External access code",
            ),
        ),
    ]
