# Generated by Django 5.2.3 on 2025-07-30 14:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("larpmanager", "0053_alter_character_access_token"),
    ]

    operations = [
        migrations.RenameField(
            model_name="registrationoption",
            old_name="details",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="registrationticket",
            old_name="details",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="writingoption",
            old_name="details",
            new_name="description",
        ),
    ]
