# Generated by Django 5.2.3 on 2025-07-30 15:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("larpmanager", "0054_rename_details_registrationoption_description_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="registrationoption",
            old_name="display",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="registrationquestion",
            old_name="display",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="workshopmodule",
            old_name="display",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="workshopoption",
            old_name="display",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="workshopquestion",
            old_name="display",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="writingoption",
            old_name="display",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="writingquestion",
            old_name="display",
            new_name="name",
        ),
    ]
