# Generated by Django 5.2.3 on 2025-08-08 08:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("larpmanager", "0055_rename_display_registrationoption_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assocpermission",
            name="config",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="eventpermission",
            name="config",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
