# Generated by Django 5.2.3 on 2025-07-31 11:28

from django.db import migrations


def clean_runs(apps, schema_editor):
    EventPermission = apps.get_model("larpmanager", "EventPermission")
    EventPermission.objects.filter(pk=2).delete()
    AssocPermission = apps.get_model("larpmanager", "AssocPermission")
    AssocPermission.objects.filter(pk=22).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("larpmanager", "0056_assocpermission_config_eventpermission_config"),
    ]

    operations = [
        migrations.RunPython(clean_runs),
    ]
