# Generated by Django 5.2.3 on 2025-08-08 11:03

import tinymce.models
from django.db import migrations, models

import larpmanager.models.utils


class Migration(migrations.Migration):
    dependencies = [
        ("larpmanager", "0057_clean_runs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="association",
            name="payment_methods",
            field=models.ManyToManyField(
                blank=True,
                help_text="Indicate the payment methods you wish to be available to participants",
                related_name="associations_payments",
                to="larpmanager.paymentmethod",
                verbose_name="Payment Methods",
            ),
        ),
        migrations.AlterField(
            model_name="character",
            name="teaser",
            field=tinymce.models.HTMLField(
                blank=True,
                help_text="Presentation visible to all participants, when 'show presentation' is checked",
                max_length=100000,
                verbose_name="Presentation",
            ),
        ),
        migrations.AlterField(
            model_name="discount",
            name="cod",
            field=models.CharField(
                default=larpmanager.models.utils.my_uuid_short,
                help_text="Indicate the special discount code, to be communicated to the participants, which will need to be entered during registration.",
                max_length=12,
                verbose_name="Code",
            ),
        ),
        migrations.AlterField(
            model_name="discount",
            name="only_reg",
            field=models.BooleanField(
                default=True,
                help_text="Indicate whether the discount can be used only on new enrollment, or whether it can be used by already registered participants.",
            ),
        ),
        migrations.AlterField(
            model_name="discount",
            name="visible",
            field=models.BooleanField(
                default=False, help_text="Indicates whether the discount is visible and usable by participants"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="max_pg",
            field=models.IntegerField(
                default=0,
                help_text="Maximum number of participants spots (0 = unlimited)",
                verbose_name="Max participants",
            ),
        ),
        migrations.AlterField(
            model_name="faction",
            name="selectable",
            field=models.BooleanField(default=False, help_text="Indicates whether it can be selected by participants"),
        ),
        migrations.AlterField(
            model_name="faction",
            name="teaser",
            field=tinymce.models.HTMLField(
                blank=True,
                help_text="Presentation visible to all participants, when 'show presentation' is checked",
                max_length=100000,
                verbose_name="Presentation",
            ),
        ),
        migrations.AlterField(
            model_name="handout",
            name="teaser",
            field=tinymce.models.HTMLField(
                blank=True,
                help_text="Presentation visible to all participants, when 'show presentation' is checked",
                max_length=100000,
                verbose_name="Presentation",
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="legal_name",
            field=models.CharField(
                blank=True,
                help_text="If for whatever reason the first and last name shown on your documents is different from the one you prefer to use, then write it here. It will only be used for internal bureaucratic purposes, and will NEVER be displayed to other participants.",
                max_length=100,
                null=True,
                verbose_name="Legal name",
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="nickname",
            field=models.CharField(
                blank=True,
                help_text="If you prefer that your real name and surname not be publicly visible, please indicate an alias that will be displayed instead. Note: If you register for an event, your real first and last name will be shown to other participants, and to the organisers.",
                max_length=100,
                verbose_name="Alias",
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="profile",
            field=models.ImageField(
                blank=True,
                help_text="Upload your portrait photo. It will be shown to other participants to help recognize you in the event. Choose a photo that you would put in an official document (in which you are alone, centered on your face)",
                max_length=500,
                null=True,
                upload_to=larpmanager.models.utils.UploadToPathAndRename("member/"),
                verbose_name="Portrait",
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="social_contact",
            field=models.CharField(
                blank=True,
                help_text="Indicates a way for other participants to contact you. It can be an email, a social profile, whatever you want. It will be made public to others participants",
                max_length=150,
                null=True,
                verbose_name="Contact",
            ),
        ),
        migrations.AlterField(
            model_name="plot",
            name="teaser",
            field=tinymce.models.HTMLField(
                blank=True,
                help_text="Presentation visible to all participants, when 'show presentation' is checked",
                max_length=100000,
                verbose_name="Presentation",
            ),
        ),
        migrations.AlterField(
            model_name="problem",
            name="severity",
            field=models.CharField(
                choices=[("r", "1 - RED"), ("o", "2 - ORANGE"), ("y", "3 - YELLOW"), ("g", "4 - GREEN")],
                default="g",
                help_text="Indicate severity: RED (risks ruining the event for more than half of the participants), ORANGE (risks ruining the event for more than ten participants),  YELLOW (risks ruining the event for a few participants), GREEN (more than  problems, finesses to be fixed)",
                max_length=1,
                verbose_name="Severity",
            ),
        ),
        migrations.AlterField(
            model_name="problem",
            name="what",
            field=models.TextField(help_text="Describe exactly what risks it poses to the event", verbose_name="What"),
        ),
        migrations.AlterField(
            model_name="problem",
            name="who",
            field=models.TextField(help_text="Describe exactly which participants are involved", verbose_name="Who"),
        ),
        migrations.AlterField(
            model_name="prologue",
            name="teaser",
            field=tinymce.models.HTMLField(
                blank=True,
                help_text="Presentation visible to all participants, when 'show presentation' is checked",
                max_length=100000,
                verbose_name="Presentation",
            ),
        ),
        migrations.AlterField(
            model_name="prologuetype",
            name="teaser",
            field=tinymce.models.HTMLField(
                blank=True,
                help_text="Presentation visible to all participants, when 'show presentation' is checked",
                max_length=100000,
                verbose_name="Presentation",
            ),
        ),
        migrations.AlterField(
            model_name="quest",
            name="teaser",
            field=tinymce.models.HTMLField(
                blank=True,
                help_text="Presentation visible to all participants, when 'show presentation' is checked",
                max_length=100000,
                verbose_name="Presentation",
            ),
        ),
        migrations.AlterField(
            model_name="questtype",
            name="teaser",
            field=tinymce.models.HTMLField(
                blank=True,
                help_text="Presentation visible to all participants, when 'show presentation' is checked",
                max_length=100000,
                verbose_name="Presentation",
            ),
        ),
        migrations.AlterField(
            model_name="registrationcharacterrel",
            name="custom_public",
            field=models.TextField(
                blank=True,
                help_text="Indicates public information about your character, which will be shown to all other participants",
                max_length=5000,
                null=True,
                verbose_name="Public",
            ),
        ),
        migrations.AlterField(
            model_name="registrationquestion",
            name="allowed",
            field=models.ManyToManyField(
                blank=True,
                help_text="Staff members who are allowed to be able to see the responses of participants (leave blank to let everyone see)",
                related_name="questions_allowed",
                to="larpmanager.member",
                verbose_name="Allowed",
            ),
        ),
        migrations.AlterField(
            model_name="registrationquestion",
            name="factions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Optional - If you select one (or more) factions, the question will only be shown to participants with characters in all chosen factions",
                related_name="registration_questions",
                to="larpmanager.faction",
                verbose_name="Faction list",
            ),
        ),
        migrations.AlterField(
            model_name="registrationquestion",
            name="tickets",
            field=models.ManyToManyField(
                blank=True,
                help_text="If you select one (or more) tickets, the question will only be shown to participants who have selected one of those tickets",
                related_name="registration_tickets",
                to="larpmanager.registrationticket",
                verbose_name="Ticket list",
            ),
        ),
        migrations.AlterField(
            model_name="registrationticket",
            name="giftable",
            field=models.BooleanField(
                default=False, help_text="Optional - Indicates whether the ticket can be gifted to other participants"
            ),
        ),
        migrations.AlterField(
            model_name="registrationticket",
            name="visible",
            field=models.BooleanField(default=True, help_text="Is it selectable by participants?"),
        ),
        migrations.AlterField(
            model_name="speedlarp",
            name="teaser",
            field=tinymce.models.HTMLField(
                blank=True,
                help_text="Presentation visible to all participants, when 'show presentation' is checked",
                max_length=100000,
                verbose_name="Presentation",
            ),
        ),
        migrations.AlterField(
            model_name="trait",
            name="teaser",
            field=tinymce.models.HTMLField(
                blank=True,
                help_text="Presentation visible to all participants, when 'show presentation' is checked",
                max_length=100000,
                verbose_name="Presentation",
            ),
        ),
        migrations.AlterField(
            model_name="writingoption",
            name="tickets",
            field=models.ManyToManyField(
                blank=True,
                help_text="If you select one (or more) tickets, the option will only be available to participants who have selected that ticket",
                related_name="character_options",
                to="larpmanager.registrationticket",
            ),
        ),
    ]
