# Generated by Django 5.2 on 2025-08-10 16:34

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("larpmanager", "0058_alter_association_payment_methods_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="text",
            field=tinymce.models.HTMLField(
                blank=True,
                help_text="Text visible only by the assigned participant, when 'show text' is checked",
                max_length=100000,
            ),
        ),
        migrations.AlterField(
            model_name="discount",
            name="typ",
            field=models.CharField(
                choices=[("a", "Standard"), ("p", "Play Again")],
                help_text="Indicate the type of discount: standard, play again (only available to those who have already played this event)",
                max_length=1,
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="faction",
            name="text",
            field=tinymce.models.HTMLField(
                blank=True,
                help_text="Text visible only by the assigned participant, when 'show text' is checked",
                max_length=100000,
            ),
        ),
        migrations.AlterField(
            model_name="handout",
            name="text",
            field=tinymce.models.HTMLField(
                blank=True,
                help_text="Text visible only by the assigned participant, when 'show text' is checked",
                max_length=100000,
            ),
        ),
        migrations.AlterField(
            model_name="plot",
            name="text",
            field=tinymce.models.HTMLField(
                blank=True,
                help_text="Text visible only by the assigned participant, when 'show text' is checked",
                max_length=100000,
            ),
        ),
        migrations.AlterField(
            model_name="prologue",
            name="text",
            field=tinymce.models.HTMLField(
                blank=True,
                help_text="Text visible only by the assigned participant, when 'show text' is checked",
                max_length=100000,
            ),
        ),
        migrations.AlterField(
            model_name="prologuetype",
            name="text",
            field=tinymce.models.HTMLField(
                blank=True,
                help_text="Text visible only by the assigned participant, when 'show text' is checked",
                max_length=100000,
            ),
        ),
        migrations.AlterField(
            model_name="quest",
            name="text",
            field=tinymce.models.HTMLField(
                blank=True,
                help_text="Text visible only by the assigned participant, when 'show text' is checked",
                max_length=100000,
            ),
        ),
        migrations.AlterField(
            model_name="questtype",
            name="text",
            field=tinymce.models.HTMLField(
                blank=True,
                help_text="Text visible only by the assigned participant, when 'show text' is checked",
                max_length=100000,
            ),
        ),
        migrations.AlterField(
            model_name="run",
            name="number",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="speedlarp",
            name="text",
            field=tinymce.models.HTMLField(
                blank=True,
                help_text="Text visible only by the assigned participant, when 'show text' is checked",
                max_length=100000,
            ),
        ),
        migrations.AlterField(
            model_name="trait",
            name="text",
            field=tinymce.models.HTMLField(
                blank=True,
                help_text="Text visible only by the assigned participant, when 'show text' is checked",
                max_length=100000,
            ),
        ),
        migrations.AlterField(
            model_name="writingquestion",
            name="editable",
            field=models.CharField(
                blank=True,
                default="",
                help_text="This field can be edited by the participant only when the character is in one of the selected statuses",
                max_length=20,
                null=True,
                verbose_name="Editable",
            ),
        ),
    ]
