# Generated by Django 5.2 on 2025-08-19 22:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("larpmanager", "0059_alter_character_text_alter_discount_typ_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="first_aid",
            field=models.CharField(
                choices=[("y", "Yes"), ("n", "No")],
                default="n",
                help_text="Are you a doctor, a nurse, or a licensed rescuer? We can ask you to intervene in case accidents occur during the event?",
                max_length=1,
                null=True,
                verbose_name="First aid",
            ),
        ),
    ]
