# Generated by Django 5.2.3 on 2025-08-19 09:33

import datetime

import django.db.models.deletion
import model_clone.mixin
from django.db import migrations, models


def first_module(apps, schema_editor):
    PermissionModule = apps.get_model("larpmanager", "PermissionModule")
    PermissionModule.objects.create(pk=1, name="def")


class Migration(migrations.Migration):
    dependencies = [
        ("larpmanager", "0060_larpmanagerticket"),
    ]

    operations = [
        migrations.CreateModel(
            name="PermissionModule",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("deleted", models.DateTimeField(db_index=True, editable=False, null=True)),
                ("deleted_by_cascade", models.BooleanField(default=False, editable=False)),
                ("created", models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("icon", models.CharField(max_length=100)),
                ("order", models.IntegerField()),
            ],
            options={
                "ordering": ["-updated"],
                "abstract": False,
            },
            bases=(model_clone.mixin.CloneMixin, models.Model),
        ),
        migrations.RunPython(first_module),
        migrations.AddField(
            model_name="assocpermission",
            name="module",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assoc_permissions",
                to="larpmanager.permissionmodule",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="eventpermission",
            name="module",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_permissions",
                to="larpmanager.permissionmodule",
            ),
            preserve_default=False,
        ),
    ]
