# Generated by Django 5.2.3 on 2025-08-19 09:33


from django.db import migrations


def clean(apps, schema_editor):
    EventPermission = apps.get_model("larpmanager", "EventPermission")
    EventPermission.objects.filter(pk=78).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("larpmanager", "0061_permissionmodule_assocpermission_module_and_more"),
    ]

    operations = [migrations.RunPython(clean)]
