# Generated by Django 5.2.3 on 2025-08-20 08:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("larpmanager", "0060_alter_member_first_aid"),
        ("larpmanager", "0062_clean_preferences"),
    ]

    operations = []
