# Generated by Django 5.2.3 on 2025-08-20 11:37

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("larpmanager", "0063_merge_20250820_0843"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="description_short",
        ),
        migrations.AlterField(
            model_name="event",
            name="description",
            field=tinymce.models.HTMLField(
                blank=True,
                help_text="Event description displayed on the event page",
                max_length=10000,
                verbose_name="Description",
            ),
        ),
    ]
