# Generated by Django 5.2 on 2025-08-20 22:02

import datetime

import django.db.models.deletion
import model_clone.mixin
from django.db import migrations, models

import larpmanager.models.utils


class Migration(migrations.Migration):
    dependencies = [
        ("larpmanager", "0064_remove_event_description_short_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inventoryboxhistory",
            name="box",
        ),
        migrations.RemoveField(
            model_name="inventoryboxphoto",
            name="box",
        ),
        migrations.RemoveField(
            model_name="inventoryboxhistory",
            name="member",
        ),
        migrations.CreateModel(
            name="InventoryContainer",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("deleted", models.DateTimeField(db_index=True, editable=False, null=True)),
                ("deleted_by_cascade", models.BooleanField(default=False, editable=False)),
                ("created", models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(help_text="Code of the box or shelf", max_length=100)),
                ("position", models.CharField(blank=True, help_text="Where it is located", max_length=100, null=True)),
                ("description", models.CharField(blank=True, max_length=1000, null=True)),
                (
                    "assoc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="containers",
                        to="larpmanager.association",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated"],
                "abstract": False,
            },
            bases=(model_clone.mixin.CloneMixin, models.Model),
        ),
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("deleted", models.DateTimeField(db_index=True, editable=False, null=True)),
                ("deleted_by_cascade", models.BooleanField(default=False, editable=False)),
                ("created", models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("quantity", models.IntegerField(blank=True, null=True)),
                ("description", models.CharField(blank=True, max_length=1000, null=True)),
                ("tags", models.CharField(blank=True, help_text="List of tags", max_length=100, null=True)),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        help_text="Photo of the object",
                        max_length=500,
                        null=True,
                        upload_to=larpmanager.models.utils.UploadToPathAndRename("inventory/"),
                        verbose_name="Photo",
                    ),
                ),
                (
                    "assoc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="items", to="larpmanager.association"
                    ),
                ),
                (
                    "container",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="larpmanager.inventorycontainer",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated"],
                "abstract": False,
            },
            bases=(model_clone.mixin.CloneMixin, models.Model),
        ),
        migrations.DeleteModel(
            name="InventoryBox",
        ),
        migrations.DeleteModel(
            name="InventoryBoxPhoto",
        ),
        migrations.DeleteModel(
            name="InventoryBoxHistory",
        ),
    ]
