# Generated by Django 5.2.3 on 2025-08-22 11:14

import datetime

import django.db.models.deletion
import model_clone.mixin
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("larpmanager", "0065_inventory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inventoryitem",
            name="tags",
        ),
        migrations.CreateModel(
            name="InventoryTag",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("deleted", models.DateTimeField(db_index=True, editable=False, null=True)),
                ("deleted_by_cascade", models.BooleanField(default=False, editable=False)),
                ("created", models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(blank=True, max_length=1000, null=True)),
                (
                    "assoc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="tags", to="larpmanager.association"
                    ),
                ),
            ],
            options={
                "ordering": ["-updated"],
                "abstract": False,
            },
            bases=(model_clone.mixin.CloneMixin, models.Model),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="items", to="larpmanager.inventorytag"),
        ),
    ]
