# Generated by Django 5.2 on 2025-08-24 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("larpmanager", "0067_alter_registrationquestion_typ_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rulepx",
            name="abilities",
            field=models.ManyToManyField(
                blank=True,
                help_text="The rule will be applied, only one time, if the character has any of the abilities. If no abilities are chosen, the rule is applied to all characters.",
                related_name="rules",
                to="larpmanager.abilitypx",
            ),
        ),
        migrations.AlterField(
            model_name="rulepx",
            name="field",
            field=models.ForeignKey(
                help_text="The character field of computed type that will be updated",
                on_delete=django.db.models.deletion.CASCADE,
                to="larpmanager.writingquestion",
            ),
        ),
    ]
