# Generated by Django 5.2 on 2025-08-24 09:25

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("larpmanager", "0068_alter_rulepx_abilities_alter_rulepx_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="description",
            field=tinymce.models.HTMLField(
                blank=True,
                default="",
                help_text="Event description displayed on the event page",
                max_length=10000,
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="inventoryarea",
            name="description",
            field=models.CharField(blank=True, default="", max_length=1000),
        ),
        migrations.AlterField(
            model_name="inventoryarea",
            name="position",
            field=models.CharField(blank=True, default="", help_text="Where it is", max_length=100),
        ),
        migrations.AlterField(
            model_name="inventoryassignment",
            name="notes",
            field=models.CharField(blank=True, default="", max_length=1000),
        ),
        migrations.AlterField(
            model_name="inventorycontainer",
            name="description",
            field=models.CharField(blank=True, default="", max_length=1000),
        ),
        migrations.AlterField(
            model_name="inventorycontainer",
            name="position",
            field=models.CharField(blank=True, default="", help_text="Where it is located", max_length=100),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="description",
            field=models.CharField(blank=True, default="", max_length=1000),
        ),
        migrations.AlterField(
            model_name="inventorytag",
            name="description",
            field=models.CharField(blank=True, default="", max_length=1000),
        ),
        migrations.AlterField(
            model_name="registrationoption",
            name="description",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional - Additional information about the option, displayed below the question",
                max_length=500,
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="registrationquestion",
            name="description",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional - Extended description (displayed in small gray text)",
                max_length=1000,
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="writingoption",
            name="description",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional - Additional information about the option, displayed below the question",
                max_length=500,
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="writingquestion",
            name="description",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional - Extended description (displayed in small gray text)",
                max_length=1000,
                verbose_name="Description",
            ),
        ),
    ]
