# Generated by Django 5.2 on 2025-08-24 12:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("larpmanager", "0070_alter_registrationticket_tier"),
    ]

    operations = [
        migrations.AddField(
            model_name="associationskin",
            name="managed",
            field=models.BooleanField(default=False),
        ),
    ]
