# Generated by Django 5.2 on 2025-08-24 21:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("larpmanager", "0070_alter_registrationticket_tier"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="inventoryassignment",
            options={},
        ),
        migrations.AddConstraint(
            model_name="inventoryassignment",
            constraint=models.UniqueConstraint(
                fields=("area", "item", "deleted"), name="unique_inventory_assignment_with_optional"
            ),
        ),
        migrations.AddConstraint(
            model_name="inventoryassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted", None)),
                fields=("area", "item"),
                name="unique_inventory_assignment_without_optional",
            ),
        ),
    ]
