# Generated by Django 5.2.5 on 2025-08-25 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('larpmanager', '0071_alter_inventoryassignment_options_and_more'),
        ('larpmanager', '0071_associationskin_managed'),
    ]

    operations = [
    ]
