# Generated by Django 5.2.5 on 2025-08-26 06:25

from django.db import migrations


def clean(apps, schema_editor):
    Feature = apps.get_model("larpmanager", "Feature")
    Feature.objects.filter(pk=190).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("larpmanager", "0072_merge_20250825_0914"),
    ]

    operations = [
        migrations.RunPython(clean),
        migrations.RemoveField(
            model_name="feature",
            name="placeholder",
        ),
    ]
