# Generated by Django 5.2.5 on 2025-08-25 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("larpmanager", "0072_merge_20250825_0914"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="InventoryAssignment",
            new_name="InventoryItemAssignment",
        ),
        migrations.RemoveConstraint(
            model_name="inventoryitemassignment",
            name="unique_inventory_assignment_with_optional",
        ),
        migrations.RemoveConstraint(
            model_name="inventoryitemassignment",
            name="unique_inventory_assignment_without_optional",
        ),
        migrations.AddConstraint(
            model_name="inventoryitemassignment",
            constraint=models.UniqueConstraint(
                fields=("area", "item", "deleted"), name="unique_inventory_item_assignment_with_optional"
            ),
        ),
        migrations.AddConstraint(
            model_name="inventoryitemassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted", None)),
                fields=("area", "item"),
                name="unique_inventory_item__assignment_without_optional",
            ),
        ),
    ]
