# Generated by Django 5.2.5 on 2025-08-25 18:08

import datetime

import django.db.models.deletion
import model_clone.mixin
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("larpmanager", "0073_rename_inventoryassignment_inventoryitemassignment_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryContainerAssignment",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("deleted", models.DateTimeField(db_index=True, editable=False, null=True)),
                ("deleted_by_cascade", models.BooleanField(default=False, editable=False)),
                ("created", models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("notes", models.CharField(blank=True, default="", max_length=1000)),
                ("loaded", models.BooleanField(default=False)),
                ("deployed", models.BooleanField(default=False)),
            ],
            bases=(model_clone.mixin.CloneMixin, models.Model),
        ),
        migrations.RemoveConstraint(
            model_name="inventoryitemassignment",
            name="unique_inventory_item__assignment_without_optional",
        ),
        migrations.AlterField(
            model_name="inventoryitemassignment",
            name="area",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="larpmanager.inventoryarea"),
        ),
        migrations.AlterField(
            model_name="inventoryitemassignment",
            name="event",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="larpmanager.event"),
        ),
        migrations.AddConstraint(
            model_name="inventoryitemassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted", None)),
                fields=("area", "item"),
                name="unique_inventory_item_assignment_without_optional",
            ),
        ),
        migrations.AddField(
            model_name="inventorycontainerassignment",
            name="area",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="larpmanager.inventoryarea"),
        ),
        migrations.AddField(
            model_name="inventorycontainerassignment",
            name="container",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="larpmanager.inventorycontainer",
            ),
        ),
        migrations.AddField(
            model_name="inventorycontainerassignment",
            name="event",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="larpmanager.event"),
        ),
        migrations.AddConstraint(
            model_name="inventorycontainerassignment",
            constraint=models.UniqueConstraint(
                fields=("area", "container", "deleted"), name="unique_inventory_container_assignment_with_optional"
            ),
        ),
        migrations.AddConstraint(
            model_name="inventorycontainerassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted", None)),
                fields=("area", "container"),
                name="unique_inventory_container_assignment_without_optional",
            ),
        ),
    ]
