# Generated by Django 5.2.5 on 2025-08-26 10:15

from django.db import migrations
from typing import Any


def clean(apps: Any, schema_editor: Any) -> Any:
    Feature = apps.get_model("larpmanager", "Feature")
    Feature.objects.filter(pk=190).delete()

    Association = apps.get_model("larpmanager", "Association")
    for assoc in Association.objects.all():
        assoc.features.add(191)
        assoc.save()


class Migration(migrations.Migration):
    dependencies = [
        ("larpmanager", "0074_inventorycontainerassignment_and_more"),
    ]

    operations = [
        migrations.RunPython(clean),
        migrations.DeleteModel(
            name="InventoryContainerAssignment",
        ),
    ]
