# Generated by Django 5.2.5 on 2025-08-26 10:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("larpmanager", "0073_remove_feature_placeholder"),
        ("larpmanager", "0074_inventorycontainerassignment_and_more"),
    ]

    operations = []
