# Generated by Django 5.2 on 2025-08-31 19:45

from django.db import migrations, models

import larpmanager.models.utils


class Migration(migrations.Migration):
    dependencies = [
        ("larpmanager", "0075_delete_inventorycontainerassignment"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="inventoryitemassignment",
            name="unique_inventory_item_assignment_with_optional",
        ),
        migrations.RemoveConstraint(
            model_name="inventoryitemassignment",
            name="unique_inventory_item_assignment_without_optional",
        ),
        migrations.RenameModel(
            old_name="InventoryItem",
            new_name="WarehouseItem",
        ),
        migrations.RenameModel(
            old_name="InventoryArea",
            new_name="WarehouseArea",
        ),
        migrations.RenameModel(
            old_name="InventoryContainer",
            new_name="WarehouseContainer",
        ),
        migrations.RenameModel(
            old_name="InventoryItemAssignment",
            new_name="WarehouseItemAssignment",
        ),
        migrations.RenameModel(
            old_name="InventoryMovement",
            new_name="WarehouseMovement",
        ),
        migrations.RenameModel(
            old_name="InventoryTag",
            new_name="WarehouseTag",
        ),
        migrations.AddConstraint(
            model_name="warehouseitemassignment",
            constraint=models.UniqueConstraint(
                fields=("area", "item", "deleted"), name="unique_warehouse_item_assignment_with_optional"
            ),
        ),
        migrations.AddConstraint(
            model_name="warehouseitemassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted", None)),
                fields=("area", "item"),
                name="unique_warehouse_item_assignment_without_optional",
            ),
        ),
        migrations.AlterField(
            model_name="warehouseitem",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Photo of the object",
                max_length=500,
                null=True,
                upload_to=larpmanager.models.utils.UploadToPathAndRename("warehouse/"),
                verbose_name="Photo",
            ),
        ),
    ]
