# Generated by Django 5.2.5 on 2025-09-03 00:14

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larpmanager', '0076_characterinventory_pooltypeci_poolbalanceci'),
    ]

    operations = [
        migrations.AddField(
            model_name='poolbalanceci',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
        migrations.AddField(
            model_name='poolbalanceci',
            name='deleted',
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='poolbalanceci',
            name='deleted_by_cascade',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='poolbalanceci',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='larpmanager.event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poolbalanceci',
            name='name',
            field=models.CharField(default='default', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poolbalanceci',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poolbalanceci',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
