# Generated by Django 5.2 on 2025-09-06 21:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("larpmanager", "0076_warehouseitem_rename_inventoryarea_warehousearea_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="featuremodule",
            name="slug",
            field=models.SlugField(
                default="coa",
                max_length=100,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[0-9a-z_-]*$", "Only characters allowed are: 0-9, a-z, _, -."
                    )
                ],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="permissionmodule",
            name="slug",
            field=models.SlugField(
                default="coa",
                max_length=100,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[0-9a-z_-]*$", "Only characters allowed are: 0-9, a-z, _, -."
                    )
                ],
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="assocpermission",
            name="slug",
            field=models.SlugField(
                blank=True,
                max_length=100,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[0-9a-z_-]*$", "Only characters allowed are: 0-9, a-z, _, -."
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="eventpermission",
            name="slug",
            field=models.SlugField(
                blank=True,
                max_length=100,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[0-9a-z_-]*$", "Only characters allowed are: 0-9, a-z, _, -."
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="feature",
            name="slug",
            field=models.SlugField(
                max_length=100,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[0-9a-z_-]*$", "Only characters allowed are: 0-9, a-z, _, -."
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="slug",
            field=models.SlugField(
                max_length=100,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[0-9a-z_-]*$", "Only characters allowed are: 0-9, a-z, _, -."
                    )
                ],
            ),
        ),
    ]
