# Generated by Django 5.2.5 on 2025-09-03 14:53

from typing import Any

from django.db import migrations, models


def update(apps: Any, schema_editor: Any) -> Any:
    # This migration intentionally does nothing during the migration.
    # The save_event_registration_form function will be called automatically
    # via post_save signals when the events are next saved.
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("larpmanager", "0076_warehouseitem_rename_inventoryarea_warehousearea_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registrationquestion",
            name="typ",
            field=models.CharField(
                choices=[
                    ("s", "Single choice"),
                    ("m", "Multiple choice"),
                    ("t", "Single-line text"),
                    ("p", "Multi-line text"),
                    ("e", "Advanced text editor"),
                    ("ticket", "Ticket"),
                    ("additional_tickets", "Additional"),
                    ("pay_what_you_want", "Free donation"),
                    ("discount", "discount"),
                    ("reg_quotas", "Quota"),
                    ("reg_surcharges", "Surcharge"),
                ],
                default="s",
                help_text="Question type",
                max_length=50,
                verbose_name="Type",
            ),
        ),
        migrations.RunPython(update),
    ]
