# Generated by Django 5.2 on 2025-09-07 13:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("larpmanager", "0077_featuremodule_slug_permissionmodule_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="featuremodule",
            name="slug",
            field=models.SlugField(
                max_length=100,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[0-9a-z_-]*$", "Only characters allowed are: 0-9, a-z, _, -."
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="permissionmodule",
            name="slug",
            field=models.SlugField(
                max_length=100,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[0-9a-z_-]*$", "Only characters allowed are: 0-9, a-z, _, -."
                    )
                ],
            ),
        ),
    ]
