# Generated by Django 5.2 on 2025-09-14 20:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("larpmanager", "0078_alter_registrationquestion_typ"),
    ]

    operations = [
        migrations.RenameField(
            model_name="abilitypx",
            old_name="dependents",
            new_name="requirements",
        ),
        migrations.RenameField(
            model_name="writingoption",
            old_name="dependents",
            new_name="requirements",
        ),
        migrations.AlterField(
            model_name="abilitypx",
            name="cost",
            field=models.IntegerField(
                default=0, help_text="Note that if the cost is 0, if will assigned automatically"
            ),
        ),
    ]
