# Generated by Django 5.2.5 on 2025-09-03 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('larpmanager', '0078_inventorytransfer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pooltypeci',
            options={},
        ),
    ]
