# Generated by Django 5.2.5 on 2025-09-04 01:40

import datetime
import django.db.models.deletion
import model_clone.mixin
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larpmanager', '0079_alter_pooltypeci_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbilityTemplatePx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=150)),
                ('descr', tinymce.models.HTMLField(blank=True, max_length=5000, null=True, verbose_name='Description')),
                ('rank', models.PositiveIntegerField(default=1, verbose_name='Rank')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='larpmanager.event')),
            ],
            options={
                'ordering': ['event', 'number'],
                'abstract': False,
            },
            bases=(model_clone.mixin.CloneMixin, models.Model),
        ),
    ]
