# Generated by Django 5.2 on 2025-09-14 20:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("larpmanager", "0079_rename_dependents_abilitypx_requirements_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="writingquestion",
            name="applicable",
            field=models.CharField(
                choices=[
                    ("c", "character"),
                    ("p", "plot"),
                    ("f", "faction"),
                    ("q", "quest"),
                    ("t", "trait"),
                    ("r", "prologue"),
                ],
                default="c",
                help_text="Select the types of writing elements that this question applies to",
                max_length=1,
                verbose_name="Applicable",
            ),
        ),
    ]
