# Generated by Django 5.2.5 on 2025-09-04 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larpmanager', '0080_abilitytemplatepx'),
    ]

    operations = [
        migrations.AddField(
            model_name='abilitypx',
            name='template',
            field=models.ForeignKey(blank=True, help_text='Optional template associated with this ability.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abilities', to='larpmanager.abilitytemplatepx', verbose_name='Template'),
        ),
    ]
