# Generated by Django 5.2.5 on 2025-09-04 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larpmanager', '0081_abilitypx_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abilitytemplatepx',
            name='rank',
        ),
        migrations.CreateModel(
            name='AbilityTemplateComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_instances', to='larpmanager.abilitytemplatepx')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_links', to='larpmanager.abilitytemplatepx')),
            ],
            options={
                'unique_together': {('parent', 'component')},
            },
        ),
        migrations.AddField(
            model_name='abilitytemplatepx',
            name='components',
            field=models.ManyToManyField(blank=True, help_text='Other templates that are part of this template. Can include multiple instances.', related_name='used_in', through='larpmanager.AbilityTemplateComponent', to='larpmanager.abilitytemplatepx', verbose_name='Component Templates'),
        ),
    ]
