# Generated by Django 5.2.5 on 2025-09-17 19:57

from django.db import migrations, models

import larpmanager.models.utils


class Migration(migrations.Migration):
    dependencies = [
        ("larpmanager", "0081_alter_abilitypx_cost_alter_abilitypx_requirements_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="LarpManagerBlog",
            new_name="LarpManagerGuide",
        ),
        migrations.AlterField(
            model_name="larpmanagerguide",
            name="photo",
            field=models.ImageField(
                blank=True,
                max_length=500,
                null=True,
                upload_to=larpmanager.models.utils.UploadToPathAndRename("albums/"),
                verbose_name="Photo",
            ),
        ),
    ]
