# Generated by Django 5.2 on 2025-09-22 08:40

from typing import Any

from django.db import migrations, models


def update(apps: Any, schema_editor: Any) -> Any:
    Plot = apps.get_model("larpmanager", "Plot")
    for instance in Plot.objects.all():
        instance.order = instance.number
        instance.save()

    PlotCharacterRel = apps.get_model("larpmanager", "PlotCharacterRel")
    for instance in PlotCharacterRel.objects.all():
        instance.order = instance.plot.number
        instance.save()


class Migration(migrations.Migration):
    dependencies = [
        ("larpmanager", "0082_larpmanagerguide_delete_larpmanagerblog"),
    ]

    operations = [
        migrations.AddField(
            model_name="plot",
            name="order",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="plotcharacterrel",
            name="order",
            field=models.IntegerField(default=0),
        ),
        migrations.RunPython(update),
    ]
