# Generated by Django 5.2.5 on 2025-09-04 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('larpmanager', '0082_remove_abilitytemplatepx_rank_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abilitytemplatepx',
            name='components',
        ),
        migrations.DeleteModel(
            name='AbilityTemplateComponent',
        ),
    ]
