# Generated by Django 5.2 on 2025-09-25 15:47

from django.db import migrations, models

import larpmanager.models.utils
import larpmanager.utils.core.validators


class Migration(migrations.Migration):
    dependencies = [
        ("larpmanager", "0083_plot_order_plotcharacterrel_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="association",
            name="font",
            field=models.FileField(
                blank=True,
                help_text="Font to be used in page titles",
                null=True,
                upload_to=larpmanager.models.utils.UploadToPathAndRename("assoc_font/"),
                validators=[
                    larpmanager.utils.core.validators.FileTypeValidator(
                        [
                            "font/ttf",
                            "font/otf",
                            "application/font-woff",
                            "application/font-woff2",
                            "font/woff",
                            "font/woff2",
                        ]
                    )
                ],
                verbose_name="Title font",
            ),
        ),
        migrations.AlterField(
            model_name="association",
            name="gdpr_contract",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=larpmanager.models.utils.UploadToPathAndRename("contract/gdpr/"),
                validators=[larpmanager.utils.core.validators.FileTypeValidator(["application/pdf"])],
            ),
        ),
        migrations.AlterField(
            model_name="helpquestion",
            name="attachment",
            field=models.FileField(
                blank=True,
                help_text="If you need to attach a file, indicate it here, otherwise leave blank",
                null=True,
                upload_to=larpmanager.models.utils.UploadToPathAndRename("attachment/"),
                validators=[
                    larpmanager.utils.core.validators.FileTypeValidator(
                        [
                            "application/pdf",
                            "application/msword",
                            "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
                            "text/plain",
                            "image/jpeg",
                            "image/png",
                            "image/gif",
                        ]
                    )
                ],
                verbose_name="Attachment",
            ),
        ),
    ]
