# Generated by Django 5.2 on 2025-09-25 17:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("larpmanager", "0084_alter_association_font_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="payment_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
