# Generated by Django 5.2.5 on 2025-10-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("larpmanager", "0085_registration_payment_date"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="paymentinvoice",
            index=models.Index(fields=["reg", "status", "-created"], name="larpmanager_reg_id_173630_idx"),
        ),
        migrations.AddIndex(
            model_name="paymentinvoice",
            index=models.Index(fields=["status", "-created"], name="larpmanager_status_453566_idx"),
        ),
    ]
