# Generated by Django 5.2.5 on 2025-10-07 10:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("larpmanager", "0086_paymentinvoice_larpmanager_reg_id_173630_idx_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="accountingitempayment",
            old_name="vat",
            new_name="vat_options",
        ),
        migrations.AddField(
            model_name="accountingitempayment",
            name="vat_ticket",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
