# Generated by Django 5.2.5 on 2025-10-07 09:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("larpmanager", "0086_paymentinvoice_larpmanager_reg_id_173630_idx_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="character",
            index=models.Index(fields=["event", "status"], name="larpmanager_event_i_5059af_idx"),
        ),
        migrations.AddIndex(
            model_name="character",
            index=models.Index(fields=["player", "event"], name="larpmanager_player__ba9e27_idx"),
        ),
        migrations.AddIndex(
            model_name="character",
            index=models.Index(fields=["event", "hide"], name="larpmanager_event_i_4f966a_idx"),
        ),
        migrations.AddIndex(
            model_name="character",
            index=models.Index(fields=["mirror"], name="larpmanager_mirror__e41bdc_idx"),
        ),
        migrations.AddIndex(
            model_name="relationship",
            index=models.Index(fields=["source"], name="larpmanager_source__7347dc_idx"),
        ),
        migrations.AddIndex(
            model_name="relationship",
            index=models.Index(fields=["target"], name="larpmanager_target__f1c1dd_idx"),
        ),
        migrations.AddIndex(
            model_name="relationship",
            index=models.Index(fields=["source", "target"], name="larpmanager_source__8d5491_idx"),
        ),
    ]
