# Generated by Django 5.2 on 2025-09-07 13:39
import os
import shutil

import django.core.validators
from django.conf import settings as conf_settings
from django.db import migrations, models

from larpmanager.models.utils import _key_id


def move_enc_files(apps, schema_editor):
    if not os.path.isdir(conf_settings.PAYMENT_SETTING_FOLDER):
        return
    Association = apps.get_model("larpmanager", "Association")
    for assoc in Association.objects.all():
        if not assoc.key:
            continue
        kid = _key_id(assoc.key)
        new_filename = f"{Path(assoc.slug).name}.{kid}.enc"
        new_path = os.path.join(conf_settings.PAYMENT_SETTING_FOLDER, new_filename)
        old_path = os.path.join(conf_settings.PAYMENT_SETTING_FOLDER, f"{assoc.slug}.enc")
        if os.path.isfile(old_path):
            shutil.move(old_path, new_path)


class Migration(migrations.Migration):
    dependencies = [
        ("larpmanager", "0090_featuremodule_slug_permissionmodule_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="featuremodule",
            name="slug",
            field=models.SlugField(
                max_length=100,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[0-9a-z_-]*$", "Only characters allowed are: 0-9, a-z, _, -."
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="permissionmodule",
            name="slug",
            field=models.SlugField(
                max_length=100,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[0-9a-z_-]*$", "Only characters allowed are: 0-9, a-z, _, -."
                    )
                ],
            ),
        ),
        migrations.RunPython(move_enc_files),
    ]
