# Generated by Django 5.2.5 on 2025-10-15 10:19

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("larpmanager", "0092_onetimecontent_onetimeaccesstoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="relationship",
            name="text",
            field=tinymce.models.HTMLField(),
        ),
    ]
