# Generated by Django 5.2.5 on 2025-10-17 07:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("larpmanager", "0093_alter_relationship_text"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="larpmanagerprofiler",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="larpmanagerprofiler",
            name="duration",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="larpmanagerprofiler",
            name="method",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="larpmanagerprofiler",
            name="path",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="larpmanagerprofiler",
            name="query",
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name="larpmanagerprofiler",
            index=models.Index(fields=["domain", "view_func_name"], name="larpmanager_domain_6b16a3_idx"),
        ),
        migrations.RemoveField(
            model_name="larpmanagerprofiler",
            name="date",
        ),
    ]
