# Generated by Django 5.2 on 2025-10-19 09:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("larpmanager", "0094_alter_larpmanagerprofiler_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="assocpermission",
            options={},
        ),
        migrations.AlterModelOptions(
            name="eventpermission",
            options={},
        ),
        migrations.AlterModelOptions(
            name="registrationanswer",
            options={},
        ),
        migrations.AlterModelOptions(
            name="registrationchoice",
            options={},
        ),
        migrations.AlterModelOptions(
            name="registrationoption",
            options={},
        ),
        migrations.AlterModelOptions(
            name="registrationquestion",
            options={},
        ),
        migrations.AlterModelOptions(
            name="writinganswer",
            options={},
        ),
        migrations.AlterModelOptions(
            name="writingchoice",
            options={},
        ),
        migrations.AlterModelOptions(
            name="writingquestion",
            options={},
        ),
        migrations.RemoveIndex(
            model_name="accountingitemmembership",
            name="larpmanager_assoc_i_f4986d_idx",
        ),
        migrations.RemoveIndex(
            model_name="character",
            name="larpmanager_event_i_5059af_idx",
        ),
        migrations.RemoveIndex(
            model_name="character",
            name="larpmanager_player__ba9e27_idx",
        ),
        migrations.RemoveIndex(
            model_name="character",
            name="larpmanager_event_i_4f966a_idx",
        ),
        migrations.RemoveIndex(
            model_name="relationship",
            name="larpmanager_source__7347dc_idx",
        ),
        migrations.RemoveIndex(
            model_name="relationship",
            name="larpmanager_target__f1c1dd_idx",
        ),
        migrations.RemoveIndex(
            model_name="relationship",
            name="larpmanager_source__8d5491_idx",
        ),
        migrations.AlterField(
            model_name="run",
            name="end",
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name="End date"),
        ),
        migrations.AddIndex(
            model_name="accountingitemmembership",
            index=models.Index(
                condition=models.Q(("deleted__isnull", True)), fields=["assoc", "year"], name="acctmem_assoc_year_act"
            ),
        ),
        migrations.AddIndex(
            model_name="assocpermission",
            index=models.Index(condition=models.Q(("deleted__isnull", True)), fields=["slug"], name="aperm_slug_act"),
        ),
        migrations.AddIndex(
            model_name="character",
            index=models.Index(
                condition=models.Q(("deleted__isnull", True)), fields=["event", "status"], name="char_evt_stat_act"
            ),
        ),
        migrations.AddIndex(
            model_name="character",
            index=models.Index(
                condition=models.Q(("deleted__isnull", True)), fields=["player", "event"], name="char_plyr_evt_act"
            ),
        ),
        migrations.AddIndex(
            model_name="character",
            index=models.Index(
                condition=models.Q(("deleted__isnull", True)), fields=["event", "hide"], name="char_evt_hide_act"
            ),
        ),
        migrations.AddIndex(
            model_name="character",
            index=models.Index(condition=models.Q(("deleted__isnull", True)), fields=["event"], name="char_evt_act"),
        ),
        migrations.AddIndex(
            model_name="eventpermission",
            index=models.Index(condition=models.Q(("deleted__isnull", True)), fields=["slug"], name="eperm_slug_act"),
        ),
        migrations.AddIndex(
            model_name="faction",
            index=models.Index(condition=models.Q(("deleted__isnull", True)), fields=["event"], name="fac_evt_act"),
        ),
        migrations.AddIndex(
            model_name="handout",
            index=models.Index(condition=models.Q(("deleted__isnull", True)), fields=["event"], name="hand_evt_act"),
        ),
        migrations.AddIndex(
            model_name="membership",
            index=models.Index(
                condition=models.Q(("deleted__isnull", True)), fields=["assoc", "member"], name="memb_assoc_mem_act"
            ),
        ),
        migrations.AddIndex(
            model_name="membership",
            index=models.Index(
                condition=models.Q(("deleted__isnull", True)), fields=["assoc", "status"], name="memb_assoc_stat_act"
            ),
        ),
        migrations.AddIndex(
            model_name="playerrelationship",
            index=models.Index(condition=models.Q(("deleted__isnull", True)), fields=["reg"], name="prel_reg_act"),
        ),
        migrations.AddIndex(
            model_name="playerrelationship",
            index=models.Index(
                condition=models.Q(("deleted__isnull", True)), fields=["target"], name="prel_target_act"
            ),
        ),
        migrations.AddIndex(
            model_name="plot",
            index=models.Index(condition=models.Q(("deleted__isnull", True)), fields=["event"], name="plot_evt_act"),
        ),
        migrations.AddIndex(
            model_name="prologue",
            index=models.Index(condition=models.Q(("deleted__isnull", True)), fields=["event"], name="prol_evt_act"),
        ),
        migrations.AddIndex(
            model_name="prologuetype",
            index=models.Index(condition=models.Q(("deleted__isnull", True)), fields=["event"], name="ptype_evt_act"),
        ),
        migrations.AddIndex(
            model_name="quest",
            index=models.Index(condition=models.Q(("deleted__isnull", True)), fields=["event"], name="quest_evt_act"),
        ),
        migrations.AddIndex(
            model_name="questtype",
            index=models.Index(condition=models.Q(("deleted__isnull", True)), fields=["event"], name="qtype_evt_act"),
        ),
        migrations.AddIndex(
            model_name="registration",
            index=models.Index(
                condition=models.Q(("deleted__isnull", True)),
                fields=["member", "run", "cancellation_date", "redeem_code"],
                name="reg_mem_run_canc_red_act",
            ),
        ),
        migrations.AddIndex(
            model_name="registration",
            index=models.Index(condition=models.Q(("deleted__isnull", True)), fields=["run"], name="reg_run_act"),
        ),
        migrations.AddIndex(
            model_name="registration",
            index=models.Index(
                condition=models.Q(("cancellation_date__isnull", True), ("deleted__isnull", True)),
                fields=["member", "run", "redeem_code"],
                name="reg_mem_run_red_active",
            ),
        ),
        migrations.AddIndex(
            model_name="registration",
            index=models.Index(
                condition=models.Q(("cancellation_date__isnull", True), ("deleted__isnull", True)),
                fields=["run"],
                name="reg_run_active_only",
            ),
        ),
        migrations.AddIndex(
            model_name="registrationanswer",
            index=models.Index(
                condition=models.Q(("deleted__isnull", True)), fields=["reg", "question"], name="ra_reg_q_act"
            ),
        ),
        migrations.AddIndex(
            model_name="registrationanswer",
            index=models.Index(condition=models.Q(("deleted__isnull", True)), fields=["reg"], name="ra_reg_act"),
        ),
        migrations.AddIndex(
            model_name="registrationchoice",
            index=models.Index(
                condition=models.Q(("deleted__isnull", True)), fields=["reg", "question"], name="rc_reg_q_act"
            ),
        ),
        migrations.AddIndex(
            model_name="registrationchoice",
            index=models.Index(condition=models.Q(("deleted__isnull", True)), fields=["reg"], name="rc_reg_act"),
        ),
        migrations.AddIndex(
            model_name="registrationoption",
            index=models.Index(condition=models.Q(("deleted__isnull", True)), fields=["event"], name="ro_evt_act"),
        ),
        migrations.AddIndex(
            model_name="registrationoption",
            index=models.Index(condition=models.Q(("deleted__isnull", True)), fields=["question"], name="ro_quest_act"),
        ),
        migrations.AddIndex(
            model_name="registrationquestion",
            index=models.Index(condition=models.Q(("deleted__isnull", True)), fields=["event"], name="rq_evt_act"),
        ),
        migrations.AddIndex(
            model_name="registrationquestion",
            index=models.Index(
                condition=models.Q(("deleted__isnull", True)), fields=["event", "status"], name="rq_evt_stat_act"
            ),
        ),
        migrations.AddIndex(
            model_name="relationship",
            index=models.Index(condition=models.Q(("deleted__isnull", True)), fields=["source"], name="rel_src_act"),
        ),
        migrations.AddIndex(
            model_name="relationship",
            index=models.Index(condition=models.Q(("deleted__isnull", True)), fields=["target"], name="rel_tgt_act"),
        ),
        migrations.AddIndex(
            model_name="relationship",
            index=models.Index(
                condition=models.Q(("deleted__isnull", True)), fields=["source", "target"], name="rel_src_tgt_act"
            ),
        ),
        migrations.AddIndex(
            model_name="speedlarp",
            index=models.Index(condition=models.Q(("deleted__isnull", True)), fields=["event"], name="speed_evt_act"),
        ),
        migrations.AddIndex(
            model_name="trait",
            index=models.Index(condition=models.Q(("deleted__isnull", True)), fields=["event"], name="trait_evt_act"),
        ),
        migrations.AddIndex(
            model_name="writinganswer",
            index=models.Index(
                condition=models.Q(("deleted__isnull", True)), fields=["element_id", "question"], name="wan_elem_q_act"
            ),
        ),
        migrations.AddIndex(
            model_name="writinganswer",
            index=models.Index(
                condition=models.Q(("deleted__isnull", True)), fields=["element_id"], name="wan_elem_act"
            ),
        ),
        migrations.AddIndex(
            model_name="writingchoice",
            index=models.Index(
                condition=models.Q(("deleted__isnull", True)), fields=["element_id", "question"], name="wch_elem_q_act"
            ),
        ),
        migrations.AddIndex(
            model_name="writingchoice",
            index=models.Index(
                condition=models.Q(("deleted__isnull", True)), fields=["element_id"], name="wch_elem_act"
            ),
        ),
        migrations.AddIndex(
            model_name="writingquestion",
            index=models.Index(
                condition=models.Q(("deleted__isnull", True)),
                fields=["event", "applicable", "status"],
                name="wq_evt_app_stat_act",
            ),
        ),
        migrations.AddIndex(
            model_name="writingquestion",
            index=models.Index(
                condition=models.Q(("deleted__isnull", True)), fields=["event", "applicable"], name="wq_evt_app_act"
            ),
        ),
    ]
