# Generated by Django 5.2.5 on 2025-10-20 10:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("larpmanager", "0095_alter_assocpermission_options_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="run",
            index=models.Index(fields=["id", "deleted"], name="larpmanager_id_070db1_idx"),
        ),
        migrations.AddIndex(
            model_name="run",
            index=models.Index(fields=["event", "deleted"], name="larpmanager_event_i_ac914c_idx"),
        ),
    ]
