# Generated by Django 5.2 on 2025-10-27 15:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("larpmanager", "0096_run_larpmanager_id_070db1_idx_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="associationconfig",
            name="unique_assoc_config_with_optional",
        ),
        migrations.RemoveConstraint(
            model_name="associationconfig",
            name="unique_assoc_config_without_optional",
        ),
        migrations.RemoveConstraint(
            model_name="assocrole",
            name="unique_assoc_role_with_optional",
        ),
        migrations.RemoveConstraint(
            model_name="assocrole",
            name="unique_assoc_role_without_optional",
        ),
        migrations.RemoveConstraint(
            model_name="assoctext",
            name="unique_assoc_text_with_optional",
        ),
        migrations.RemoveConstraint(
            model_name="assoctext",
            name="nique_assoc_text_without_optional",
        ),
        migrations.RemoveConstraint(
            model_name="electronicinvoice",
            name="unique_number_with_optional",
        ),
        migrations.RemoveConstraint(
            model_name="electronicinvoice",
            name="unique_number_without_optional",
        ),
        migrations.RemoveConstraint(
            model_name="membership",
            name="unique_membership_number_with_optional",
        ),
        migrations.RemoveConstraint(
            model_name="membership",
            name="unique_membership_number_without_optional",
        ),
        migrations.RemoveConstraint(
            model_name="volunteerregistry",
            name="unique_volunteer_registry_with_optional",
        ),
        migrations.RemoveConstraint(
            model_name="volunteerregistry",
            name="unique_volunteer_registry_without_optional",
        ),
        migrations.RemoveConstraint(
            model_name="vote",
            name="unique_vote_number_with_optional",
        ),
        migrations.RemoveConstraint(
            model_name="vote",
            name="unique_vote_number_without_optional",
        ),
        migrations.RemoveIndex(
            model_name="accountingitemmembership",
            name="acctmem_assoc_year_act",
        ),
        migrations.RemoveIndex(
            model_name="associationconfig",
            name="larpmanager_assoc_i_fea18c_idx",
        ),
        migrations.RemoveIndex(
            model_name="membership",
            name="memb_assoc_mem_act",
        ),
        migrations.RemoveIndex(
            model_name="membership",
            name="memb_assoc_stat_act",
        ),
        migrations.RemoveIndex(
            model_name="paymentinvoice",
            name="larpmanager_assoc_i_ade55e_idx",
        ),
        migrations.RenameField(
            model_name="accountingitemcollection",
            old_name="assoc",
            new_name="association",
        ),
        migrations.RenameField(
            model_name="accountingitemdiscount",
            old_name="assoc",
            new_name="association",
        ),
        migrations.RenameField(
            model_name="accountingitemdonation",
            old_name="assoc",
            new_name="association",
        ),
        migrations.RenameField(
            model_name="accountingitemexpense",
            old_name="assoc",
            new_name="association",
        ),
        migrations.RenameField(
            model_name="accountingiteminflow",
            old_name="assoc",
            new_name="association",
        ),
        migrations.RenameField(
            model_name="accountingitemmembership",
            old_name="assoc",
            new_name="association",
        ),
        migrations.RenameField(
            model_name="accountingitemother",
            old_name="assoc",
            new_name="association",
        ),
        migrations.RenameField(
            model_name="accountingitemoutflow",
            old_name="assoc",
            new_name="association",
        ),
        migrations.RenameField(
            model_name="accountingitempayment",
            old_name="assoc",
            new_name="association",
        ),
        migrations.RenameField(
            model_name="accountingitemtransaction",
            old_name="assoc",
            new_name="association",
        ),
        migrations.RenameField(
            model_name="album",
            old_name="assoc",
            new_name="association",
        ),
        migrations.RenameField(
            model_name="associationconfig",
            old_name="assoc",
            new_name="association",
        ),
        migrations.RenameField(
            model_name="assocrole",
            old_name="assoc",
            new_name="association",
        ),
        migrations.RenameField(
            model_name="assoctext",
            old_name="assoc",
            new_name="association",
        ),
        migrations.RenameField(
            model_name="badge",
            old_name="assoc",
            new_name="association",
        ),
        migrations.RenameField(
            model_name="chatmessage",
            old_name="assoc",
            new_name="association",
        ),
        migrations.RenameField(
            model_name="collection",
            old_name="assoc",
            new_name="association",
        ),
        migrations.RenameField(
            model_name="competence",
            old_name="assoc",
            new_name="association",
        ),
        migrations.RenameField(
            model_name="contact",
            old_name="assoc",
            new_name="association",
        ),
        migrations.RenameField(
            model_name="electronicinvoice",
            old_name="assoc",
            new_name="association",
        ),
        migrations.RenameField(
            model_name="email",
            old_name="assoc",
            new_name="association",
        ),
        migrations.RenameField(
            model_name="event",
            old_name="assoc",
            new_name="association",
        ),
        migrations.RenameField(
            model_name="helpquestion",
            old_name="assoc",
            new_name="association",
        ),
        migrations.RenameField(
            model_name="larpmanagerticket",
            old_name="assoc",
            new_name="association",
        ),
        migrations.RenameField(
            model_name="membership",
            old_name="assoc",
            new_name="association",
        ),
        migrations.RenameField(
            model_name="paymentinvoice",
            old_name="assoc",
            new_name="association",
        ),
        migrations.RenameField(
            model_name="recordaccounting",
            old_name="assoc",
            new_name="association",
        ),
        migrations.RenameField(
            model_name="refundrequest",
            old_name="assoc",
            new_name="association",
        ),
        migrations.RenameField(
            model_name="shuttleservice",
            old_name="assoc",
            new_name="association",
        ),
        migrations.RenameField(
            model_name="urlshortner",
            old_name="assoc",
            new_name="association",
        ),
        migrations.RenameField(
            model_name="volunteerregistry",
            old_name="assoc",
            new_name="association",
        ),
        migrations.RenameField(
            model_name="vote",
            old_name="assoc",
            new_name="association",
        ),
        migrations.RenameField(
            model_name="warehousecontainer",
            old_name="assoc",
            new_name="association",
        ),
        migrations.RenameField(
            model_name="warehouseitem",
            old_name="assoc",
            new_name="association",
        ),
        migrations.RenameField(
            model_name="warehousemovement",
            old_name="assoc",
            new_name="association",
        ),
        migrations.RenameField(
            model_name="warehousetag",
            old_name="assoc",
            new_name="association",
        ),
        migrations.AddIndex(
            model_name="accountingitemmembership",
            index=models.Index(
                condition=models.Q(("deleted__isnull", True)),
                fields=["association", "year"],
                name="acctmem_assoc_year_act",
            ),
        ),
        migrations.AddIndex(
            model_name="associationconfig",
            index=models.Index(fields=["association", "name"], name="larpmanager_associa_0dbbf7_idx"),
        ),
        migrations.AddIndex(
            model_name="membership",
            index=models.Index(
                condition=models.Q(("deleted__isnull", True)),
                fields=["association", "member"],
                name="memb_assoc_mem_act",
            ),
        ),
        migrations.AddIndex(
            model_name="membership",
            index=models.Index(
                condition=models.Q(("deleted__isnull", True)),
                fields=["association", "status"],
                name="memb_assoc_stat_act",
            ),
        ),
        migrations.AddIndex(
            model_name="paymentinvoice",
            index=models.Index(fields=["association", "cod"], name="larpmanager_associa_0773c9_idx"),
        ),
        migrations.AddConstraint(
            model_name="associationconfig",
            constraint=models.UniqueConstraint(
                fields=("association", "name", "deleted"), name="unique_assoc_config_with_optional"
            ),
        ),
        migrations.AddConstraint(
            model_name="associationconfig",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted", None)),
                fields=("association", "name"),
                name="unique_assoc_config_without_optional",
            ),
        ),
        migrations.AddConstraint(
            model_name="assocrole",
            constraint=models.UniqueConstraint(
                fields=("association", "number", "deleted"), name="unique_assoc_role_with_optional"
            ),
        ),
        migrations.AddConstraint(
            model_name="assocrole",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted", None)),
                fields=("association", "number"),
                name="unique_assoc_role_without_optional",
            ),
        ),
        migrations.AddConstraint(
            model_name="assoctext",
            constraint=models.UniqueConstraint(
                fields=("association", "typ", "language", "deleted"), name="unique_assoc_text_with_optional"
            ),
        ),
        migrations.AddConstraint(
            model_name="assoctext",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted", None)),
                fields=("association", "typ", "language"),
                name="nique_assoc_text_without_optional",
            ),
        ),
        migrations.AddConstraint(
            model_name="electronicinvoice",
            constraint=models.UniqueConstraint(
                fields=("number", "year", "association", "deleted"), name="unique_number_with_optional"
            ),
        ),
        migrations.AddConstraint(
            model_name="electronicinvoice",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted", None)),
                fields=("number", "year", "association"),
                name="unique_number_without_optional",
            ),
        ),
        migrations.AddConstraint(
            model_name="membership",
            constraint=models.UniqueConstraint(
                fields=("member", "association", "deleted"), name="unique_membership_number_with_optional"
            ),
        ),
        migrations.AddConstraint(
            model_name="membership",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted", None)),
                fields=("member", "association"),
                name="unique_membership_number_without_optional",
            ),
        ),
        migrations.AddConstraint(
            model_name="volunteerregistry",
            constraint=models.UniqueConstraint(
                fields=("member", "association", "deleted"), name="unique_volunteer_registry_with_optional"
            ),
        ),
        migrations.AddConstraint(
            model_name="volunteerregistry",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted", None)),
                fields=("member", "association"),
                name="unique_volunteer_registry_without_optional",
            ),
        ),
        migrations.AddConstraint(
            model_name="vote",
            constraint=models.UniqueConstraint(
                fields=("member", "association", "year", "number", "deleted"), name="unique_vote_number_with_optional"
            ),
        ),
        migrations.AddConstraint(
            model_name="vote",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted", None)),
                fields=("member", "association", "year", "number"),
                name="unique_vote_number_without_optional",
            ),
        ),
    ]
