# Generated by Django 5.2 on 2025-10-27 16:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("larpmanager", "0096_run_larpmanager_id_070db1_idx_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AssocRole",
            new_name="AssociationRole",
        ),
        migrations.RenameModel(
            old_name="AssocPermission",
            new_name="AssociationPermission",
        ),
    ]
