# Generated by Django 5.2 on 2025-10-27 15:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("larpmanager", "0097_remove_associationconfig_unique_assoc_config_with_optional_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AssocPermission",
            new_name="AssociationPermission",
        ),
        migrations.RenameModel(
            old_name="AssocRole",
            new_name="AssociationRole",
        ),
        migrations.RenameModel(
            old_name="AssocText",
            new_name="AssociationText",
        ),
    ]
