# Generated by Django 5.2.5 on 2025-10-28 20:26

import datetime

import django.db.models.deletion
import model_clone.mixin
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("larpmanager", "0098_rename_assoctext_associationtext_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssociationTranslation",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("deleted", models.DateTimeField(db_index=True, editable=False, null=True)),
                ("deleted_by_cascade", models.BooleanField(default=False, editable=False)),
                ("created", models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("number", models.IntegerField(blank=True, null=True)),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("it", "Italiano"),
                            ("es", "Español"),
                            ("de", "Deutsch"),
                            ("fr", "Français"),
                            ("cs", "Čeština"),
                            ("pl", "Polski"),
                            ("nl", "Nederlands"),
                            ("nb", "Norsk"),
                            ("sv", "Svenska"),
                        ],
                        help_text="Language code for this translation",
                        max_length=3,
                        verbose_name="Language",
                    ),
                ),
                (
                    "msgid",
                    models.TextField(
                        db_index=True,
                        help_text="The original text to translate (in English)",
                        verbose_name="Original text",
                    ),
                ),
                (
                    "msgstr",
                    models.TextField(
                        help_text="The custom translation for this organization", verbose_name="Translated text"
                    ),
                ),
                (
                    "context",
                    models.CharField(
                        blank=True,
                        help_text="Optional context for disambiguation (msgctxt in gettext)",
                        max_length=200,
                        null=True,
                        verbose_name="Context",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True, help_text="Whether this translation is currently active", verbose_name="Active"
                    ),
                ),
                (
                    "association",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_translations",
                        to="larpmanager.association",
                        verbose_name="Association",
                    ),
                ),
            ],
            options={
                "verbose_name": "Association Translation",
                "verbose_name_plural": "Association Translations",
                "indexes": [
                    models.Index(fields=["association", "language", "msgid"], name="larpmanager_associa_7671be_idx"),
                    models.Index(fields=["active"], name="larpmanager_active_8671d4_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("association", "language", "msgid", "context", "deleted"),
                        name="unique_assoc_translation_with_deleted",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("deleted", None)),
                        fields=("association", "language", "msgid", "context"),
                        name="unique_assoc_translation_without_deleted",
                    ),
                ],
            },
            bases=(model_clone.mixin.CloneMixin, models.Model),
        ),
    ]
