# Generated by Django 5.2 on 2025-10-30 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("larpmanager", "0099_associationtranslation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="associationtranslation",
            name="active",
            field=models.BooleanField(
                default=True,
                help_text="Whether this translation override is currently active. Inactive translations are ignored.",
                verbose_name="Active",
            ),
        ),
        migrations.AlterField(
            model_name="associationtranslation",
            name="association",
            field=models.ForeignKey(
                help_text="The organization this translation belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="custom_translations",
                to="larpmanager.association",
                verbose_name="Association",
            ),
        ),
        migrations.AlterField(
            model_name="associationtranslation",
            name="context",
            field=models.CharField(
                blank=True,
                help_text="Optional context for disambiguation when the same text has different meanings (msgctxt)",
                max_length=200,
                null=True,
                verbose_name="Context",
            ),
        ),
        migrations.AlterField(
            model_name="associationtranslation",
            name="language",
            field=models.CharField(
                choices=[
                    ("en", "English"),
                    ("it", "Italiano"),
                    ("es", "Español"),
                    ("de", "Deutsch"),
                    ("fr", "Français"),
                    ("cs", "Čeština"),
                    ("pl", "Polski"),
                    ("nl", "Nederlands"),
                    ("nb", "Norsk"),
                    ("sv", "Svenska"),
                ],
                help_text="ISO language code (e.g., 'en', 'it', 'de')",
                max_length=3,
                verbose_name="Language",
            ),
        ),
        migrations.AlterField(
            model_name="associationtranslation",
            name="msgid",
            field=models.TextField(
                db_index=True,
                help_text="The original English text as it appears in the code (msgid in gettext)",
                verbose_name="Original text",
            ),
        ),
        migrations.AlterField(
            model_name="associationtranslation",
            name="msgstr",
            field=models.TextField(
                help_text="The custom translation that will replace the default for this organization",
                verbose_name="Translated text",
            ),
        ),
        migrations.AlterField(
            model_name="associationtranslation",
            name="number",
            field=models.IntegerField(
                blank=True, help_text="Optional ordering number", null=True, verbose_name="Number"
            ),
        ),
        migrations.AlterField(
            model_name="discount",
            name="runs",
            field=models.ManyToManyField(
                blank=True,
                help_text="Indicate the sessions for which the discount is active",
                related_name="discounts",
                to="larpmanager.run",
                verbose_name="Sessions",
            ),
        ),
    ]
