# Generated by Django 5.2 on 2025-11-01 10:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("larpmanager", "0100_alter_associationtranslation_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="association",
            name="maintainers",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users who can manage support tickets and receive ticket notifications",
                related_name="maintained_associations",
                to="larpmanager.member",
                verbose_name="Maintainers",
            ),
        ),
        migrations.AddField(
            model_name="larpmanagerticket",
            name="analysis",
            field=models.CharField(default="", max_length=10000, verbose_name="Analysis"),
        ),
        migrations.AddField(
            model_name="larpmanagerticket",
            name="priority",
            field=models.CharField(default="", max_length=100, verbose_name="Priority"),
        ),
        migrations.AddField(
            model_name="larpmanagerticket",
            name="status",
            field=models.BooleanField(default=False),
        ),
    ]
