# Generated by Django 5.2.5 on 2025-10-31 23:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("larpmanager", "0100_alter_associationtranslation_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="larpmanagerticket",
            name="analysis",
            field=models.CharField(default="", max_length=10000, verbose_name="Analysis"),
        ),
        migrations.AddField(
            model_name="larpmanagerticket",
            name="priority",
            field=models.CharField(default="", max_length=100, verbose_name="Priority"),
        ),
        migrations.AddField(
            model_name="larpmanagerticket",
            name="status",
            field=models.BooleanField(default=False),
        ),
    ]
