# Generated by Django 5.2 on 2025-11-02 16:36

from django.db import migrations, models

import larpmanager.models.utils
import larpmanager.utils.core.validators


class Migration(migrations.Migration):
    dependencies = [
        ("larpmanager", "0101_association_maintainers_larpmanagerticket_analysis_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="association",
            name="font",
            field=models.FileField(
                blank=True,
                help_text="Font to be used in page titles",
                null=True,
                upload_to=larpmanager.models.utils.UploadToPathAndRename("association_font/"),
                validators=[
                    larpmanager.utils.core.validators.FileTypeValidator(
                        [
                            "font/ttf",
                            "font/otf",
                            "application/font-woff",
                            "application/font-woff2",
                            "font/woff",
                            "font/woff2",
                            "font/sfnt",
                        ]
                    )
                ],
                verbose_name="Title font",
            ),
        ),
    ]
