# Generated by Django 5.2.5 on 2025-11-06 21:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("larpmanager", "0102_alter_association_font"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discount",
            name="typ",
            field=models.CharField(
                choices=[("a", "Standard"), ("p", "Play Again"), ("f", "Friend"), ("I", "Influencer"), ("g", "Gift")],
                help_text="Indicate the type of discount: standard, play again (only available to those who have already played this event)",
                max_length=1,
                verbose_name="Type",
            ),
        ),
    ]
