# Generated by Django 5.2.7 on 2025-11-10 09:10

import django.core.validators
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larpmanager', '0103_alter_discount_typ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abilitypx',
            name='descr',
            field=tinymce.models.HTMLField(blank=True, default='', max_length=5000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='accountingitemexpense',
            name='balance',
            field=models.CharField(choices=[('1', 'Raw materials, auxiliaries, consumables and goods'), ('2', 'Services'), ('3', 'Use of third party assets'), ('4', 'Personal'), ('5', 'Miscellaneous operating expenses')], default='', help_text='Indicate how spending is allocated at the budget level', max_length=1, verbose_name='Balance'),
        ),
        migrations.AlterField(
            model_name='accountingitemoutflow',
            name='balance',
            field=models.CharField(choices=[('1', 'Raw materials, auxiliaries, consumables and goods'), ('2', 'Services'), ('3', 'Use of third party assets'), ('4', 'Personal'), ('5', 'Miscellaneous operating expenses')], default='', help_text='Indicate how spending is allocated at the budget level', max_length=1, verbose_name='Balance'),
        ),
        migrations.AlterField(
            model_name='accountingitempayment',
            name='info',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='association',
            name='main_mail',
            field=models.EmailField(blank=True, default='', help_text='(Optional) Indicate an organization contact address for sending communications', max_length=254),
        ),
        migrations.AlterField(
            model_name='association',
            name='nationality',
            field=models.CharField(blank=True, choices=[('it', 'Italy')], default='', help_text='(Optional) Indicate the organization nationality to activate nation-specific features', max_length=2, verbose_name='Nationality'),
        ),
        migrations.AlterField(
            model_name='association',
            name='payment_currency',
            field=models.CharField(blank=True, choices=[('e', 'EUR'), ('u', 'USD'), ('g', 'GBP'), ('c', 'CAD'), ('j', 'JPY')], default='e', help_text='Indicates the currency in which to receive payments', max_length=1, verbose_name='Payment currency'),
        ),
        migrations.AlterField(
            model_name='associationpermission',
            name='config',
            field=models.TextField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='associationskin',
            name='default_nation',
            field=models.CharField(blank=True, choices=[('it', 'Italy')], default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='associationtext',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('it', 'Italiano'), ('es', 'Español'), ('de', 'Deutsch'), ('fr', 'Français'), ('cs', 'Čeština'), ('pl', 'Polski'), ('nl', 'Nederlands'), ('nb', 'Norsk'), ('sv', 'Svenska')], default='en', help_text='Text language', max_length=3, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='associationtext',
            name='text',
            field=tinymce.models.HTMLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='associationtranslation',
            name='context',
            field=models.CharField(blank=True, default='', help_text='Optional context for disambiguation when the same text has different meanings (msgctxt)', max_length=200, verbose_name='Context'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='contribute_code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='collection',
            name='redeem_code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='electronicinvoice',
            name='response',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='electronicinvoice',
            name='xml',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='email',
            name='reply_to',
            field=models.CharField(blank=True, default='', max_length=170),
        ),
        migrations.AlterField(
            model_name='event',
            name='authors',
            field=models.CharField(blank=True, default='', help_text='Names of the collaborators who are organizing it', max_length=500, verbose_name='Authors'),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Only lowercase characters and numbers are allowed, no spaces or symbols', max_length=30, validators=[django.core.validators.RegexValidator('^[0-9a-z_-]*$', 'Only characters allowed are: 0-9, a-z, _, -.')], verbose_name='URL identifier'),
        ),
        migrations.AlterField(
            model_name='event',
            name='tagline',
            field=models.CharField(blank=True, default='', help_text='A short tagline, slogan', max_length=500, verbose_name='Tagline'),
        ),
        migrations.AlterField(
            model_name='event',
            name='where',
            field=models.CharField(blank=True, default='', help_text='Where it is held', max_length=500),
        ),
        migrations.AlterField(
            model_name='eventpermission',
            name='config',
            field=models.TextField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='eventtext',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('it', 'Italiano'), ('es', 'Español'), ('de', 'Deutsch'), ('fr', 'Français'), ('cs', 'Čeština'), ('pl', 'Polski'), ('nl', 'Nederlands'), ('nb', 'Norsk'), ('sv', 'Svenska')], default='en', help_text='Text language', max_length=3, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='eventtext',
            name='text',
            field=tinymce.models.HTMLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='feature',
            name='after_link',
            field=models.TextField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='feature',
            name='after_text',
            field=models.TextField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='featuremodule',
            name='nationality',
            field=models.CharField(blank=True, choices=[('it', 'Italy')], default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='handouttemplate',
            name='css',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='larpmanagerfaq',
            name='answer',
            field=tinymce.models.HTMLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='larpmanagerguide',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='larpmanagerguide',
            name='text',
            field=tinymce.models.HTMLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='larpmanagershowcase',
            name='text',
            field=tinymce.models.HTMLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='larpmanagerticket',
            name='email',
            field=models.EmailField(default='', help_text='How can we contact you', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='larpmanagerticket',
            name='reason',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='larpmanagertutorial',
            name='descr',
            field=tinymce.models.HTMLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='member',
            name='accessibility',
            field=models.CharField(blank=True, default='', help_text='Fill in this field if you have accessibility needs', max_length=500, verbose_name='Accessibility'),
        ),
        migrations.AlterField(
            model_name='member',
            name='birth_place',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Birth place'),
        ),
        migrations.AlterField(
            model_name='member',
            name='diet',
            field=models.CharField(blank=True, default='', help_text='Fill in this field if you follow a personal diet for reasons of choice(e.g. vegetarian, vegan) or health (celiac disease, allergies). Leave empty if you do not have things to report!', max_length=500, verbose_name='Diet'),
        ),
        migrations.AlterField(
            model_name='member',
            name='document',
            field=models.CharField(blank=True, default='', help_text='Enter the number or code of the identification document indicated above', max_length=16, verbose_name='Document number'),
        ),
        migrations.AlterField(
            model_name='member',
            name='document_type',
            field=models.CharField(blank=True, choices=[('i', 'ID Card'), ('p', "Driver's License"), ('s', 'Passport')], default='i', help_text='Indicates a type of identification document issued by the nation in which you reside', max_length=1, verbose_name='Document type'),
        ),
        migrations.AlterField(
            model_name='member',
            name='first_aid',
            field=models.CharField(blank=True, choices=[('y', 'Yes'), ('n', 'No')], default='n', help_text='Are you a doctor, a nurse, or a licensed rescuer? We can ask you to intervene in case accidents occur during the event?', max_length=1, verbose_name='First aid'),
        ),
        migrations.AlterField(
            model_name='member',
            name='fiscal_code',
            field=models.CharField(blank=True, default='', help_text='If you are an Italian citizen, indicate your tax code; otherwise leave blank', max_length=16, verbose_name='Fiscal code'),
        ),
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female'), ('o', 'Other')], default='o', help_text='Indicates what gender you identify yourself as', max_length=1, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='member',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('it', 'Italiano'), ('es', 'Español'), ('de', 'Deutsch'), ('fr', 'Français'), ('cs', 'Čeština'), ('pl', 'Polski'), ('nl', 'Nederlands'), ('nb', 'Norsk'), ('sv', 'Svenska')], default='en', help_text='Preferred navigation language', max_length=3, verbose_name='Navigation language'),
        ),
        migrations.AlterField(
            model_name='member',
            name='legal_name',
            field=models.CharField(blank=True, default='', help_text='If for whatever reason the first and last name shown on your documents is different from the one you prefer to use, then write it here. It will only be used for internal bureaucratic purposes, and will NEVER be displayed to other participants.', max_length=100, verbose_name='Legal name'),
        ),
        migrations.AlterField(
            model_name='member',
            name='nationality',
            field=models.CharField(blank=True, choices=[('AF', 'Afghanistan'), ('AX', 'Åland Islands'), ('AL', 'Albania'), ('DZ', 'Algeria'), ('AS', 'American Samoa'), ('AD', 'Andorra'), ('AO', 'Angola'), ('AI', 'Anguilla'), ('AQ', 'Antarctica'), ('AG', 'Antigua and Barbuda'), ('AR', 'Argentina'), ('AM', 'Armenia'), ('AW', 'Aruba'), ('AU', 'Australia'), ('AT', 'Austria'), ('AZ', 'Azerbaijan'), ('BS', 'Bahamas'), ('BH', 'Bahrain'), ('BD', 'Bangladesh'), ('BB', 'Barbados'), ('BY', 'Belarus'), ('BE', 'Belgium'), ('BZ', 'Belize'), ('BJ', 'Benin'), ('BM', 'Bermuda'), ('BT', 'Bhutan'), ('BO', 'Bolivia, Plurinational State of'), ('BQ', 'Bonaire, Sint Eustatius and Saba'), ('BA', 'Bosnia and Herzegovina'), ('BW', 'Botswana'), ('BV', 'Bouvet Island'), ('BR', 'Brazil'), ('IO', 'British Indian Ocean Territory'), ('BN', 'Brunei Darussalam'), ('BG', 'Bulgaria'), ('BF', 'Burkina Faso'), ('BI', 'Burundi'), ('KH', 'Cambodia'), ('CM', 'Cameroon'), ('CA', 'Canada'), ('CV', 'Cape Verde'), ('KY', 'Cayman Islands'), ('CF', 'Central African Republic'), ('TD', 'Chad'), ('CL', 'Chile'), ('CN', 'China'), ('CX', 'Christmas Island'), ('CC', 'Cocos (Keeling Islands)'), ('CO', 'Colombia'), ('KM', 'Comoros'), ('CG', 'Congo'), ('CD', 'Congo, The Democratic Republic of the'), ('CK', 'Cook Islands'), ('CR', 'Costa Rica'), ('CI', "Côte D'ivoire"), ('HR', 'Croatia'), ('CU', 'Cuba'), ('CW', 'Curaçao'), ('CY', 'Cyprus'), ('CZ', 'Czech Republic'), ('DK', 'Denmark'), ('DJ', 'Djibouti'), ('DM', 'Dominica'), ('DO', 'Dominican Republic'), ('EC', 'Ecuador'), ('EG', 'Egypt'), ('SV', 'El Salvador'), ('GQ', 'Equatorial Guinea'), ('ER', 'Eritrea'), ('EE', 'Estonia'), ('ET', 'Ethiopia'), ('FK', 'Falkland Islands (Malvinas)'), ('FO', 'Faroe Islands'), ('FJ', 'Fiji'), ('FI', 'Finland'), ('FR', 'France'), ('GF', 'French Guiana'), ('PF', 'French Polynesia'), ('TF', 'French Southern Territories'), ('GA', 'Gabon'), ('GM', 'Gambia'), ('GE', 'Georgia'), ('DE', 'Germany'), ('GH', 'Ghana'), ('GI', 'Gibraltar'), ('GR', 'Greece'), ('GL', 'Greenland'), ('GD', 'Grenada'), ('GP', 'Guadeloupe'), ('GU', 'Guam'), ('GT', 'Guatemala'), ('GG', 'Guernsey'), ('GN', 'Guinea'), ('GW', 'Guinea-bissau'), ('GY', 'Guyana'), ('HT', 'Haiti'), ('HM', 'Heard Island and McDonald Islands'), ('VA', 'Holy See (Vatican City State)'), ('HN', 'Honduras'), ('HK', 'Hong Kong'), ('HU', 'Hungary'), ('IS', 'Iceland'), ('IN', 'India'), ('ID', 'Indonesia'), ('IR', 'Iran, Islamic Republic of'), ('IQ', 'Iraq'), ('IE', 'Ireland'), ('IM', 'Isle of Man'), ('IL', 'Israel'), ('IT', 'Italy'), ('JM', 'Jamaica'), ('JP', 'Japan'), ('JE', 'Jersey'), ('JO', 'Jordan'), ('KZ', 'Kazakhstan'), ('KE', 'Kenya'), ('KI', 'Kiribati'), ('KP', "Korea, Democratic People's Republic of"), ('KR', 'Korea, Republic of'), ('KW', 'Kuwait'), ('KG', 'Kyrgyzstan'), ('LA', "Lao People's Democratic Republic"), ('LV', 'Latvia'), ('LB', 'Lebanon'), ('LS', 'Lesotho'), ('LR', 'Liberia'), ('LY', 'Libya'), ('LI', 'Liechtenstein'), ('LT', 'Lithuania'), ('LU', 'Luxembourg'), ('MO', 'Macao'), ('MK', 'Macedonia, The Former Yugoslav Republic of'), ('MG', 'Madagascar'), ('MW', 'Malawi'), ('MY', 'Malaysia'), ('MV', 'Maldives'), ('ML', 'Mali'), ('MT', 'Malta'), ('MH', 'Marshall Islands'), ('MQ', 'Martinique'), ('MR', 'Mauritania'), ('MU', 'Mauritius'), ('YT', 'Mayotte'), ('MX', 'Mexico'), ('FM', 'Micronesia, Federated States of'), ('MD', 'Moldova, Republic of'), ('MC', 'Monaco'), ('MN', 'Mongolia'), ('ME', 'Montenegro'), ('MS', 'Montserrat'), ('MA', 'Morocco'), ('MZ', 'Mozambique'), ('MM', 'Myanmar'), ('NA', 'Namibia'), ('NR', 'Nauru'), ('NP', 'Nepal'), ('NL', 'Netherlands'), ('NC', 'New Caledonia'), ('NZ', 'New Zealand'), ('NI', 'Nicaragua'), ('NE', 'Niger'), ('NG', 'Nigeria'), ('NU', 'Niue'), ('NF', 'Norfolk Island'), ('MP', 'Northern Mariana Islands'), ('NO', 'Norway'), ('OM', 'Oman'), ('PK', 'Pakistan'), ('PW', 'Palau'), ('PS', 'Palestinian Territory, Occupied'), ('PA', 'Panama'), ('PG', 'Papua New Guinea'), ('PY', 'Paraguay'), ('PE', 'Peru'), ('PH', 'Philippines'), ('PN', 'Pitcairn'), ('PL', 'Poland'), ('PT', 'Portugal'), ('PR', 'Puerto Rico'), ('QA', 'Qatar'), ('RE', 'Réunion'), ('RO', 'Romania'), ('RU', 'Russian Federation'), ('RW', 'Rwanda'), ('BL', 'Saint Barthélemy'), ('SH', 'Saint Helena, Ascension and Tristan Da Cunha'), ('KN', 'Saint Kitts and Nevis'), ('LC', 'Saint Lucia'), ('MF', 'Saint Martin (French Part)'), ('PM', 'Saint Pierre and Miquelon'), ('VC', 'Saint Vincent and the Grenadines'), ('WS', 'Samoa'), ('SM', 'San Marino'), ('ST', 'Sao Tome and Principe'), ('SA', 'Saudi Arabia'), ('SN', 'Senegal'), ('RS', 'Serbia'), ('SC', 'Seychelles'), ('SL', 'Sierra Leone'), ('SG', 'Singapore'), ('SX', 'Sint Maarten (Dutch Part)'), ('SK', 'Slovakia'), ('SI', 'Slovenia'), ('SB', 'Solomon Islands'), ('SO', 'Somalia'), ('ZA', 'South Africa'), ('GS', 'South Georgia and the South Sandwich Islands'), ('SS', 'South Sudan'), ('ES', 'Spain'), ('LK', 'Sri Lanka'), ('SD', 'Sudan'), ('SR', 'Suriname'), ('SJ', 'Svalbard and Jan Mayen'), ('SZ', 'Swaziland'), ('SE', 'Sweden'), ('CH', 'Switzerland'), ('SY', 'Syrian Arab Republic'), ('TW', 'Taiwan, Province of China'), ('TJ', 'Tajikistan'), ('TZ', 'Tanzania, United Republic of'), ('TH', 'Thailand'), ('TL', 'Timor-leste'), ('TG', 'Togo'), ('TK', 'Tokelau'), ('TO', 'Tonga'), ('TT', 'Trinidad and Tobago'), ('TN', 'Tunisia'), ('TR', 'Turkey'), ('TM', 'Turkmenistan'), ('TC', 'Turks and Caicos Islands'), ('TV', 'Tuvalu'), ('UG', 'Uganda'), ('UA', 'Ukraine'), ('AE', 'United Arab Emirates'), ('GB', 'United Kingdom'), ('US', 'United States'), ('UM', 'United States Minor Outlying Islands'), ('UY', 'Uruguay'), ('UZ', 'Uzbekistan'), ('VU', 'Vanuatu'), ('VE', 'Venezuela, Bolivarian Republic of'), ('VN', 'Viet Nam'), ('VG', 'Virgin Islands, British'), ('VI', 'Virgin Islands, U.S.'), ('WF', 'Wallis and Futuna'), ('EH', 'Western Sahara'), ('YE', 'Yemen'), ('ZM', 'Zambia'), ('ZW', 'Zimbabwe')], default='', help_text='Indicate the country of which you are a citizen', max_length=2, verbose_name='Nationality'),
        ),
        migrations.AlterField(
            model_name='member',
            name='newsletter',
            field=models.CharField(blank=True, choices=[('a', 'Yes, keep me posted!'), ('o', 'Only really important communications'), ('n', "No, I don't want updates")], default='a', help_text='Do you wish to be always updated on our events?', max_length=1, verbose_name='Newsletter'),
        ),
        migrations.AlterField(
            model_name='member',
            name='presentation',
            field=models.CharField(blank=True, default='', help_text='If you are a candidate for the Board, please write an introduction here!', max_length=500, verbose_name='Presentation'),
        ),
        migrations.AlterField(
            model_name='member',
            name='pronoun',
            field=models.CharField(blank=True, default='', help_text='Indicate the pronouns you wish to be used to refer to you', max_length=20, verbose_name='Pronouns'),
        ),
        migrations.AlterField(
            model_name='member',
            name='residence_address',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Residence address'),
        ),
        migrations.AlterField(
            model_name='member',
            name='safety',
            field=models.CharField(blank=True, default='', help_text="Fill in this field if there is something you think is important that the organizers know about you. It's up to you to decide what to share with us. This information will be treated as strictly confidential: only a restricted part of the organizers will have access to the answers, and will not be transmitted in any form. This information may concern: physical health problems, epilepsy, mental health problems (e.g. neurosis, bipolar disorder, anxiety disorder, various phobias), trigger topics ('lines and veils', we can't promise that you won't run into them in the event, but we'll make sure they're not part of your main quests). Leave empty if you do not have things to report!", max_length=500, verbose_name='Safety'),
        ),
        migrations.AlterField(
            model_name='member',
            name='social_contact',
            field=models.CharField(blank=True, default='', help_text='Indicates a way for other participants to contact you. It can be an email, a social profile, whatever you want. It will be made public to others participants', max_length=150, verbose_name='Contact'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='password_reset',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='paymentinvoice',
            name='key',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='paymentinvoice',
            name='text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='paymentinvoice',
            name='txn_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='instructions',
            field=tinymce.models.HTMLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='plotcharacterrel',
            name='text',
            field=models.TextField(blank=True, default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='registration',
            name='redeem_code',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='registrationcharacterrel',
            name='custom_name',
            field=models.CharField(blank=True, default='', help_text='Specify your custom character name (depending on the event you can choose the name, or adapt the name to your chosen gender)', max_length=150, verbose_name='Character name'),
        ),
        migrations.AlterField(
            model_name='registrationcharacterrel',
            name='custom_private',
            field=models.TextField(blank=True, default='', help_text='Indicates public information about your character, which will be shown only to you and the organizers', max_length=5000, verbose_name='Private'),
        ),
        migrations.AlterField(
            model_name='registrationcharacterrel',
            name='custom_pronoun',
            field=models.CharField(blank=True, default='', help_text='If you wish, indicate a pronoun for your character', max_length=15, verbose_name='Pronoun'),
        ),
        migrations.AlterField(
            model_name='registrationcharacterrel',
            name='custom_public',
            field=models.TextField(blank=True, default='', help_text='Indicates public information about your character, which will be shown to all other participants', max_length=5000, verbose_name='Public'),
        ),
        migrations.AlterField(
            model_name='registrationcharacterrel',
            name='custom_song',
            field=models.URLField(blank=True, default='', help_text='Indicate a song you want to dedicate to your character', max_length=100, verbose_name='Song'),
        ),
        migrations.AlterField(
            model_name='registrationsection',
            name='description',
            field=tinymce.models.HTMLField(blank=True, default='', help_text='Description - will be displayed at the beginning of the section', max_length=5000),
        ),
        migrations.AlterField(
            model_name='registrationticket',
            name='description',
            field=models.CharField(blank=True, default='', help_text='Optional - Extended description (displayed in small gray text)', max_length=500, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='run',
            name='plan',
            field=models.CharField(blank=True, choices=[('f', 'Free'), ('p', 'Support')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='shuttleservice',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Indicates useful information to passengers, such as color of your car, time estimated time of your arrival', verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='util',
            name='cod',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='warehousemovement',
            name='notes',
            field=models.CharField(blank=True, default='', help_text='Where it has been placed? When it is expected to come back?', max_length=1000),
        ),
        migrations.AlterField(
            model_name='writingquestion',
            name='editable',
            field=models.CharField(blank=True, default='', help_text='This field can be edited by the participant only when the character is in one of the selected statuses', max_length=20, verbose_name='Editable'),
        ),
    ]
