# Generated by Claude Code on 2025-11-14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("larpmanager", "0105_alter_abilitypx_created_alter_abilitytypepx_created_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizerNotificationQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("registration_new", "New Registration"),
                            ("registration_update", "Updated Registration"),
                            ("registration_cancel", "Cancelled Registration"),
                            ("payment_money", "Money Payment"),
                            ("payment_credit", "Credit Payment"),
                            ("payment_token", "Token Payment"),
                            ("invoice_approval", "Invoice Awaiting Approval"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "details",
                    models.JSONField(blank=True, default=dict),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True),
                ),
                (
                    "sent",
                    models.BooleanField(default=False),
                ),
                (
                    "sent_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="larpmanager.event",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="larpmanager.accountingitem",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="larpmanager.accountingitempayment",
                    ),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="larpmanager.registration",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organizer Notification Queue",
                "verbose_name_plural": "Organizer Notification Queue",
                "ordering": ["-created_at"],
            },
        ),
    ]
