# Generated by Django 5.2.7 on 2025-11-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larpmanager', '0105_alter_abilitypx_created_alter_abilitytypepx_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='status',
            field=models.CharField(choices=[('e', 'Inactive (E)'), ('j', 'Inactive (J)'), ('u', 'Inactive (U)'), ('s', 'Review'), ('a', 'Accepted'), ('r', 'Kicked out')], db_index=True, default='e', max_length=1),
        ),
    ]
