# Generated by Django 5.2.7 on 2025-11-19 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larpmanager', '0107_alter_membership_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='status',
            field=models.CharField(choices=[('e', 'Inactive (E)'), ('j', 'Inactive (J)'), ('u', 'Inactive (U)'), ('s', 'Review'), ('a', 'Accepted'), ('r', 'Kicked out')], db_index=True, default='e', help_text='Current status of the membership application and approval process', max_length=1, verbose_name='Membership status'),
        ),
    ]
