# Generated by Django 5.2.7 on 2025-11-27 01:49

import django.db.models.deletion
import django.utils.timezone
import model_clone.mixin
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larpmanager', '0109_alter_util_util'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbilityTemplatePx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=150)),
                ('descr', tinymce.models.HTMLField(blank=True, max_length=5000, null=True, verbose_name='Description')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='larpmanager.event')),
            ],
            options={
                'ordering': ['event', 'number'],
                'abstract': False,
            },
            bases=(model_clone.mixin.CloneMixin, models.Model),
        ),
        migrations.AddField(
            model_name='abilitypx',
            name='template',
            field=models.ForeignKey(blank=True, help_text='Optional template associated with this ability.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abilities', to='larpmanager.abilitytemplatepx', verbose_name='Template'),
        ),
    ]
