# Generated by Django 5.2.7 on 2025-11-27 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('larpmanager', '0109_abilitytemplatecomponent_abilitytemplatepx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abilitytemplatepx',
            name='components',
        ),
        migrations.DeleteModel(
            name='AbilityTemplateComponent',
        ),
    ]
