# Generated by Django 5.2.7 on 2025-12-18 12:07

import secrets

from django.db import migrations, models

from larpmanager.models.utils import my_uuid_short


def my_uuid_short():
    """Generate a unique 12-character UUID for member public URLs."""
    return secrets.token_urlsafe(9)[:12]


def populate_member_uuids(apps, schema_editor):
    """Populate UUID field for existing members."""
    Member = apps.get_model("larpmanager", "Member")
    for member in Member.objects.filter(uuid__isnull=True):
        # Generate unique UUIDs, checking for collisions
        while True:
            new_uuid = my_uuid_short()
            if not Member.objects.filter(uuid=new_uuid).exists():
                member.uuid = new_uuid
                member.save(update_fields=["uuid"])
                break


class Migration(migrations.Migration):

    dependencies = [
        ("larpmanager", "0113_create_highlights_and_migrate_showcase_photos"),
    ]

    operations = [
        # Add UUID field as nullable first
        migrations.AddField(
            model_name="member",
            name="uuid",
            field=models.CharField(
                default=None,
                editable=False,
                help_text="Unique identifier for public profile URLs",
                max_length=12,
                null=True,
                verbose_name="Public UUID",
            ),
        ),
        # Populate UUIDs for existing members
        migrations.RunPython(populate_member_uuids, migrations.RunPython.noop),
        # Make field non-nullable with default
        migrations.AlterField(
            model_name="member",
            name="uuid",
            field=models.CharField(
                default=my_uuid_short,
                editable=False,
                help_text="Unique identifier for public profile URLs",
                max_length=12,
                verbose_name="Public UUID",
            ),
        ),
        # Add unique constraint
        migrations.AlterField(
            model_name="member",
            name="uuid",
            field=models.CharField(
                default=my_uuid_short,
                editable=False,
                help_text="Unique identifier for public profile URLs",
                max_length=12,
                unique=True,
                verbose_name="Public UUID",
            ),
        )
    ]
