# Generated by Django 5.2.7 on 2025-12-20 12:58

from django.db import migrations, models

from larpmanager.models.utils import my_uuid_short


def populate_paymentinvoice_uuids(apps, schema_editor):
    """Populate UUID field for existing payment invoices."""
    PaymentInvoice = apps.get_model("larpmanager", "PaymentInvoice")
    for invoice in PaymentInvoice.objects.filter(uuid__isnull=True):
        # Generate unique UUIDs, checking for collisions
        while True:
            new_uuid = my_uuid_short()
            if not PaymentInvoice.objects.filter(uuid=new_uuid).exists():
                invoice.uuid = new_uuid
                invoice.save(update_fields=["uuid"])
                break


def populate_registrationticket_uuids(apps, schema_editor):
    """Populate UUID field for existing registration tickets."""
    RegistrationTicket = apps.get_model("larpmanager", "RegistrationTicket")
    for ticket in RegistrationTicket.objects.filter(uuid__isnull=True):
        # Generate unique UUIDs, checking for collisions
        while True:
            new_uuid = my_uuid_short()
            if not RegistrationTicket.objects.filter(uuid=new_uuid).exists():
                ticket.uuid = new_uuid
                ticket.save(update_fields=["uuid"])
                break


class Migration(migrations.Migration):

    dependencies = [
        ('larpmanager', '0115_alter_member_uuid'),
    ]

    operations = [
        # PaymentInvoice UUID field
        # Step 1: Add UUID field as nullable
        migrations.AddField(
            model_name='paymentinvoice',
            name='uuid',
            field=models.CharField(
                default=None,
                editable=False,
                max_length=12,
                null=True,
            ),
        ),
        # Step 2: Populate UUIDs for existing records
        migrations.RunPython(populate_paymentinvoice_uuids, migrations.RunPython.noop),
        # Step 3: Make field non-nullable with default
        migrations.AlterField(
            model_name='paymentinvoice',
            name='uuid',
            field=models.CharField(
                default=my_uuid_short,
                editable=False,
                max_length=12,
            ),
        ),
        # Step 4: Add unique constraint
        migrations.AlterField(
            model_name='paymentinvoice',
            name='uuid',
            field=models.CharField(
                default=my_uuid_short,
                editable=False,
                max_length=12,
                unique=True,
            ),
        ),

        # Registration: Rename special_cod to uuid
        migrations.RenameField(
            model_name='registration',
            old_name='special_cod',
            new_name='uuid',
        ),
        # Update uuid field to match model definition
        migrations.AlterField(
            model_name='registration',
            name='uuid',
            field=models.CharField(
                default=my_uuid_short,
                editable=False,
                max_length=12,
                unique=True,
            ),
        ),

        # RegistrationTicket UUID field
        # Step 1: Add UUID field as nullable
        migrations.AddField(
            model_name='registrationticket',
            name='uuid',
            field=models.CharField(
                default=None,
                editable=False,
                max_length=12,
                null=True,
            ),
        ),
        # Step 2: Populate UUIDs for existing records
        migrations.RunPython(populate_registrationticket_uuids, migrations.RunPython.noop),
        # Step 3: Make field non-nullable with default
        migrations.AlterField(
            model_name='registrationticket',
            name='uuid',
            field=models.CharField(
                default=my_uuid_short,
                editable=False,
                max_length=12,
            ),
        ),
        # Step 4: Add unique constraint
        migrations.AlterField(
            model_name='registrationticket',
            name='uuid',
            field=models.CharField(
                default=my_uuid_short,
                editable=False,
                max_length=12,
                unique=True,
            ),
        ),

        # Update Member UUID field to match current model state
        migrations.AlterField(
            model_name='member',
            name='uuid',
            field=models.CharField(
                default=my_uuid_short,
                editable=False,
                max_length=12,
                unique=True,
            ),
        ),
    ]
