# Generated by Django 5.2.7 on 2025-12-27 17:11

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import model_clone.mixin
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larpmanager', '0115_alter_member_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='LarpManagerBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('keywords', models.CharField(max_length=1000, null=True)),
                ('slug', models.SlugField(max_length=100, validators=[django.core.validators.RegexValidator('^[0-9a-z_-]*$', 'Only characters allowed are: 0-9, a-z, _, -.')])),
                ('text', tinymce.models.HTMLField(blank=True, null=True)),
                ('published', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-updated'],
                'abstract': False,
            },
            bases=(model_clone.mixin.CloneMixin, models.Model),
        ),
        migrations.AddField(
            model_name='larpmanagerguide',
            name='keywords',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='larpmanagershowcase',
            name='blog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='showcases', to='larpmanager.larpmanagerblog'),
        ),
    ]
