# Generated by Django 5.2.7 on 2025-12-22 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larpmanager', '0116_everyone_uuid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abilitytemplatepx',
            options={},
        ),
        migrations.AlterModelOptions(
            name='album',
            options={},
        ),
        migrations.AlterModelOptions(
            name='badge',
            options={},
        ),
        migrations.AlterModelOptions(
            name='collection',
            options={},
        ),
        migrations.AlterModelOptions(
            name='email',
            options={},
        ),
        migrations.AlterModelOptions(
            name='larpmanagerticket',
            options={},
        ),
        migrations.AlterModelOptions(
            name='problem',
            options={},
        ),
        migrations.AlterModelOptions(
            name='refundrequest',
            options={},
        ),
        migrations.AlterModelOptions(
            name='registrationsection',
            options={},
        ),
        migrations.AlterModelOptions(
            name='registrationticket',
            options={},
        ),
        migrations.AlterModelOptions(
            name='rulepx',
            options={},
        ),
        migrations.AlterModelOptions(
            name='shuttleservice',
            options={},
        ),
        migrations.AlterModelOptions(
            name='textversion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='urlshortner',
            options={},
        ),
        migrations.AlterModelOptions(
            name='util',
            options={},
        ),
        migrations.AlterModelOptions(
            name='warehousearea',
            options={},
        ),
        migrations.AlterModelOptions(
            name='warehousecontainer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='warehouseitem',
            options={},
        ),
        migrations.AlterModelOptions(
            name='warehousemovement',
            options={},
        ),
        migrations.AlterModelOptions(
            name='warehousetag',
            options={},
        ),
        migrations.AlterModelOptions(
            name='workshopmodule',
            options={},
        ),
        migrations.AlterModelOptions(
            name='workshopoption',
            options={},
        ),
        migrations.AlterModelOptions(
            name='writingoption',
            options={},
        ),
        migrations.AlterField(
            model_name='member',
            name='uuid',
            field=models.CharField(db_index=True, editable=False, max_length=12, unique=True),
        ),
    ]
