# Generated by Django 5.2.7 on 2025-12-22
# Migration to add UUID fields to all models with UuidMixin

from django.db import migrations, models
import larpmanager.models.utils


def populate_uuids(apps, schema_editor):
    """Populate UUID fields for all models with UuidMixin."""
    models_to_populate = [
        'Badge', 'PlotCharacterRel', 'TextVersion',
        'WritingQuestion', 'WritingOption', 'LarpManagerTicket',
        'Association', 'AssociationText', 'AssociationTranslation',
        'RegistrationTicket', 'RegistrationSection', 'RegistrationQuota',
        'RegistrationInstallment', 'RegistrationSurcharge',
        'RegistrationQuestion', 'RegistrationOption',
        'Util', 'UrlShortner', 'Album', 'WorkshopModule',
        'WorkshopQuestion', 'WorkshopOption', 'WarehouseContainer',
        'WarehouseTag', 'WarehouseItem', 'WarehouseMovement',
        'WarehouseArea', 'ShuttleService', 'Problem', 'Email',
        'OneTimeContent', 'AssociationRole', 'EventRole',
        'AbilityTemplatePx', 'AbilityTypePx', 'AbilityPx',
        'DeliveryPx', 'RulePx', 'ModifierPx', 'Event',
        'EventButton', 'EventText', 'ProgressStep', 'Run',
        'PaymentInvoice', 'ElectronicInvoice',
        'Discount', 'Collection', 'RefundRequest', 'OneTimeAccessToken',
        'HelpQuestion',
        # Writing subclasses
        'Character', 'Plot', 'Faction', 'PrologueType', 'Prologue',
        'Handout', 'SpeedLarp', 'QuestType', 'Quest', 'Trait',
        # AccountingItem subclasses
        'AccountingItemTransaction', 'AccountingItemMembership',
        'AccountingItemDonation', 'AccountingItemOther',
        'AccountingItemPayment', 'AccountingItemExpense',
        'AccountingItemOutflow', 'AccountingItemInflow',
        'AccountingItemDiscount', 'AccountingItemCollection',
    ]

    for model_name in models_to_populate:
        Model = apps.get_model('larpmanager', model_name)
        for instance in Model.objects.filter(uuid__isnull=True):
            # Generate unique UUIDs, checking for collisions
            while True:
                new_uuid = larpmanager.models.utils.my_uuid_short()
                if not Model.objects.filter(uuid=new_uuid).exists():
                    instance.uuid = new_uuid
                    instance.save(update_fields=['uuid'])
                    break


class Migration(migrations.Migration):

    dependencies = [
        ('larpmanager', '0116_larpmanagerblog_larpmanagerguide_keywords_and_more'),
    ]

    operations = []

    # Step 0: Rename Registration.special_cod to uuid (it already exists)
    operations.append(
        migrations.RenameField(
            model_name='registration',
            old_name='special_cod',
            new_name='uuid',
        )
    )

    # Model names to table names mapping (excluding Registration which is handled above)
    model_names = [
        ('badge', 'Badge'),
        ('plotcharacterrel', 'PlotCharacterRel'),
        ('textversion', 'TextVersion'),
        ('writingquestion', 'WritingQuestion'),
        ('writingoption', 'WritingOption'),
        ('larpmanagerticket', 'LarpManagerTicket'),
        ('association', 'Association'),
        ('associationtext', 'AssociationText'),
        ('associationtranslation', 'AssociationTranslation'),
        ('registrationticket', 'RegistrationTicket'),
        ('registrationsection', 'RegistrationSection'),
        ('registrationquota', 'RegistrationQuota'),
        ('registrationinstallment', 'RegistrationInstallment'),
        ('registrationsurcharge', 'RegistrationSurcharge'),
        ('registrationquestion', 'RegistrationQuestion'),
        ('registrationoption', 'RegistrationOption'),
        ('util', 'Util'),
        ('urlshortner', 'UrlShortner'),
        ('album', 'Album'),
        ('workshopmodule', 'WorkshopModule'),
        ('workshopquestion', 'WorkshopQuestion'),
        ('workshopoption', 'WorkshopOption'),
        ('warehousecontainer', 'WarehouseContainer'),
        ('warehousetag', 'WarehouseTag'),
        ('warehouseitem', 'WarehouseItem'),
        ('warehousemovement', 'WarehouseMovement'),
        ('warehousearea', 'WarehouseArea'),
        ('shuttleservice', 'ShuttleService'),
        ('problem', 'Problem'),
        ('email', 'Email'),
        ('onetimecontent', 'OneTimeContent'),
        ('associationrole', 'AssociationRole'),
        ('eventrole', 'EventRole'),
        ('abilitytemplatepx', 'AbilityTemplatePx'),
        ('abilitytypepx', 'AbilityTypePx'),
        ('abilitypx', 'AbilityPx'),
        ('deliverypx', 'DeliveryPx'),
        ('rulepx', 'RulePx'),
        ('modifierpx', 'ModifierPx'),
        ('event', 'Event'),
        ('eventbutton', 'EventButton'),
        ('eventtext', 'EventText'),
        ('progressstep', 'ProgressStep'),
        ('run', 'Run'),
        ('paymentinvoice', 'PaymentInvoice'),
        ('electronicinvoice', 'ElectronicInvoice'),
        ('discount', 'Discount'),
        ('collection', 'Collection'),
        ('refundrequest', 'RefundRequest'),
        ('onetimeaccesstoken', 'OneTimeAccessToken'),
        ('helpquestion', 'HelpQuestion'),
        # Writing subclasses
        ('character', 'Character'),
        ('plot', 'Plot'),
        ('faction', 'Faction'),
        ('prologuetype', 'PrologueType'),
        ('prologue', 'Prologue'),
        ('handout', 'Handout'),
        ('speedlarp', 'SpeedLarp'),
        ('questtype', 'QuestType'),
        ('quest', 'Quest'),
        ('trait', 'Trait'),
        # AccountingItem subclasses
        ('accountingitemtransaction', 'AccountingItemTransaction'),
        ('accountingitemmembership', 'AccountingItemMembership'),
        ('accountingitemdonation', 'AccountingItemDonation'),
        ('accountingitemother', 'AccountingItemOther'),
        ('accountingitempayment', 'AccountingItemPayment'),
        ('accountingitemexpense', 'AccountingItemExpense'),
        ('accountingitemoutflow', 'AccountingItemOutflow'),
        ('accountingiteminflow', 'AccountingItemInflow'),
        ('accountingitemdiscount', 'AccountingItemDiscount'),
        ('accountingitemcollection', 'AccountingItemCollection'),
    ]

    # Step 1: Add UUID fields as nullable for all models (except Registration)
    for model_name, _ in model_names:
        operations.append(
            migrations.AddField(
                model_name=model_name,
                name='uuid',
                field=models.CharField(
                    default=None,
                    editable=False,
                    max_length=12,
                    null=True,
                    db_index=False,  # Add index later with unique constraint
                ),
            )
        )

    # Step 2: Populate UUIDs for all models
    operations.append(
        migrations.RunPython(populate_uuids, migrations.RunPython.noop)
    )

    # Step 3: Make UUID fields unique and add db_index for all models (including Registration)
    # Add Registration first
    operations.append(
        migrations.AlterField(
            model_name='registration',
            name='uuid',
            field=models.CharField(
                editable=False,
                max_length=12,
                unique=True,
                db_index=True,
            ),
        )
    )

    # Then all other models
    for model_name, _ in model_names:
        operations.append(
            migrations.AlterField(
                model_name=model_name,
                name='uuid',
                field=models.CharField(
                    editable=False,
                    max_length=12,
                    unique=True,
                    db_index=True,
                ),
            )
        )
