# Generated by Django 5.2.7 on 2025-12-22 17:58

from django.db import migrations, models


def convert_casting_elements_to_uuid(apps, schema_editor):
    """Convert Casting.element from integer ID to UUID string.

    This migration converts existing Casting records that have integer IDs
    in the element field to use UUID strings instead. The element field
    can reference either Character (typ=0) or Trait (typ!=0).
    """
    Casting = apps.get_model('larpmanager', 'Casting')
    Character = apps.get_model('larpmanager', 'Character')
    Trait = apps.get_model('larpmanager', 'Trait')

    # Build lookup dictionaries: id -> uuid
    character_uuid_map = {char.id: str(char.uuid) for char in Character.objects.all()}
    trait_uuid_map = {trait.id: str(trait.uuid) for trait in Trait.objects.all()}

    # Process all casting records
    castings_to_update = []
    for casting in Casting.objects.all():
        # Try to parse element as integer ID
        try:
            element_id = int(casting.element)
        except (ValueError, TypeError):
            # Already a UUID string, skip
            continue

        # Look up UUID based on casting type
        if casting.typ == 0:
            # Character casting
            if element_id in character_uuid_map:
                casting.element = character_uuid_map[element_id]
                castings_to_update.append(casting)
        else:
            # Trait casting
            if element_id in trait_uuid_map:
                casting.element = trait_uuid_map[element_id]
                castings_to_update.append(casting)

    # Bulk update all modified casting records
    if castings_to_update:
        Casting.objects.bulk_update(castings_to_update, ['element'])


class Migration(migrations.Migration):

    dependencies = [
        ('larpmanager', '0118_everyone_uuid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abilitytemplatepx',
            options={},
        ),
        migrations.AlterModelOptions(
            name='album',
            options={},
        ),
        migrations.AlterModelOptions(
            name='badge',
            options={},
        ),
        migrations.AlterModelOptions(
            name='collection',
            options={},
        ),
        migrations.AlterModelOptions(
            name='email',
            options={},
        ),
        migrations.AlterModelOptions(
            name='larpmanagerticket',
            options={},
        ),
        migrations.AlterModelOptions(
            name='problem',
            options={},
        ),
        migrations.AlterModelOptions(
            name='refundrequest',
            options={},
        ),
        migrations.AlterModelOptions(
            name='registrationsection',
            options={},
        ),
        migrations.AlterModelOptions(
            name='registrationticket',
            options={},
        ),
        migrations.AlterModelOptions(
            name='rulepx',
            options={},
        ),
        migrations.AlterModelOptions(
            name='shuttleservice',
            options={},
        ),
        migrations.AlterModelOptions(
            name='textversion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='urlshortner',
            options={},
        ),
        migrations.AlterModelOptions(
            name='util',
            options={},
        ),
        migrations.AlterModelOptions(
            name='warehousearea',
            options={},
        ),
        migrations.AlterModelOptions(
            name='warehousecontainer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='warehouseitem',
            options={},
        ),
        migrations.AlterModelOptions(
            name='warehousemovement',
            options={},
        ),
        migrations.AlterModelOptions(
            name='warehousetag',
            options={},
        ),
        migrations.AlterModelOptions(
            name='workshopmodule',
            options={},
        ),
        migrations.AlterModelOptions(
            name='workshopoption',
            options={},
        ),
        migrations.AlterModelOptions(
            name='writingoption',
            options={},
        ),
        migrations.AlterField(
            model_name='member',
            name='uuid',
            field=models.CharField(db_index=True, editable=False, max_length=12, unique=True),
        ),
        migrations.AlterModelOptions(
            name='helpquestion',
            options={},
        ),
        migrations.AlterField(
            model_name='casting',
            name='element',
            field=models.CharField(max_length=12),
        ),
        migrations.RunPython(convert_casting_elements_to_uuid, reverse_code=migrations.RunPython.noop),
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={},
        ),
    ]
