# Generated by Django 5.2.7 on 2025-12-29 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larpmanager', '0119_finish_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='larpmanagerticket',
            name='status',
            field=models.CharField(max_length=20, default='open'),
        ),
        migrations.AlterField(
            model_name='larpmanagerticket',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=20, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='larpmanagerticket',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('working', 'Working'), ('done', 'Done')], default='open', max_length=20, verbose_name='Status'),
        ),
    ]
