# Generated by Django 5.2.7 on 2026-01-08 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('larpmanager', '0121_migrate_config_ids_to_uuids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plotcharacterrel',
            name='uuid',
        ),
    ]
