# Generated by Django 5.2.7 on 2026-01-08 16:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larpmanager', '0121_migrate_config_ids_to_uuids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plotcharacterrel',
            name='uuid',
        ),
        migrations.AddField(
            model_name='inventorytransfer',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='inventorytransfer',
            name='deleted',
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='inventorytransfer',
            name='deleted_by_cascade',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='inventorytransfer',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
