# Generated by Django 5.2.7 on 2026-01-09 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larpmanager', '0122_remove_plotcharacterrel_uuid_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='playerrelationship',
            name='unique_player_relationship_with_optional',
        ),
        migrations.RemoveConstraint(
            model_name='playerrelationship',
            name='unique_player_relationship_without_optional',
        ),
        migrations.RemoveIndex(
            model_name='accountingitempayment',
            name='larpmanager_pay_93a76d_idx',
        ),
        migrations.RemoveIndex(
            model_name='paymentinvoice',
            name='larpmanager_reg_id_173630_idx',
        ),
        migrations.RemoveIndex(
            model_name='playerrelationship',
            name='prel_reg_act',
        ),
        migrations.RemoveIndex(
            model_name='registrationanswer',
            name='ra_reg_q_act',
        ),
        migrations.RemoveIndex(
            model_name='registrationanswer',
            name='ra_reg_act',
        ),
        migrations.RemoveIndex(
            model_name='registrationchoice',
            name='rc_reg_q_act',
        ),
        migrations.RemoveIndex(
            model_name='registrationchoice',
            name='rc_reg_act',
        ),
        migrations.RenameField(
            model_name='accountingitempayment',
            old_name='reg',
            new_name='registration',
        ),
        migrations.RenameField(
            model_name='accountingitemtransaction',
            old_name='reg',
            new_name='registration',
        ),
        migrations.RenameField(
            model_name='paymentinvoice',
            old_name='reg',
            new_name='registration',
        ),
        migrations.RenameField(
            model_name='playerrelationship',
            old_name='reg',
            new_name='registration',
        ),
        migrations.RenameField(
            model_name='registrationanswer',
            old_name='reg',
            new_name='registration',
        ),
        migrations.RenameField(
            model_name='registrationcharacterrel',
            old_name='reg',
            new_name='registration',
        ),
        migrations.RenameField(
            model_name='registrationchoice',
            old_name='reg',
            new_name='registration',
        ),
        migrations.AddIndex(
            model_name='accountingitempayment',
            index=models.Index(fields=['pay', 'registration'], name='larpmanager_pay_ad81d9_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentinvoice',
            index=models.Index(fields=['registration', 'status', '-created'], name='larpmanager_registr_e02272_idx'),
        ),
        migrations.AddIndex(
            model_name='playerrelationship',
            index=models.Index(condition=models.Q(('deleted__isnull', True)), fields=['registration'], name='prel_reg_act'),
        ),
        migrations.AddIndex(
            model_name='registrationanswer',
            index=models.Index(condition=models.Q(('deleted__isnull', True)), fields=['registration', 'question'], name='ra_reg_q_act'),
        ),
        migrations.AddIndex(
            model_name='registrationanswer',
            index=models.Index(condition=models.Q(('deleted__isnull', True)), fields=['registration'], name='ra_reg_act'),
        ),
        migrations.AddIndex(
            model_name='registrationchoice',
            index=models.Index(condition=models.Q(('deleted__isnull', True)), fields=['registration', 'question'], name='rc_reg_q_act'),
        ),
        migrations.AddIndex(
            model_name='registrationchoice',
            index=models.Index(condition=models.Q(('deleted__isnull', True)), fields=['registration'], name='rc_reg_act'),
        ),
        migrations.AddConstraint(
            model_name='playerrelationship',
            constraint=models.UniqueConstraint(fields=('registration', 'target', 'deleted'), name='unique_player_relationship_with_optional'),
        ),
        migrations.AddConstraint(
            model_name='playerrelationship',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', None)), fields=('registration', 'target'), name='unique_player_relationship_without_optional'),
        ),
    ]
