# Generated by Django 5.2.7 on 2026-01-13

from typing import Any

from django.db import migrations


def set_old_dashboard_config(apps: Any, schema_editor: Any) -> None:
    """Set old_dashboard config to True for all existing associations.

    This allows existing associations to keep using the old dashboard
    while new associations default to the new dashboard.
    """
    Association = apps.get_model("larpmanager", "Association")
    AssociationConfig = apps.get_model("larpmanager", "AssociationConfig")

    # Get all existing associations
    associations = Association.objects.all()

    # Set old_dashboard config to True for each association
    for association in associations:
        # Only create if it doesn't already exist
        if not AssociationConfig.objects.filter(
            association=association,
            key="old_dashboard"
        ).exists():
            AssociationConfig.objects.create(
                association=association,
                key="old_dashboard",
                value="True"
            )


class Migration(migrations.Migration):

    dependencies = [
        ('larpmanager', '0124_remove_playerrelationship_unique_player_relationship_with_optional_and_more'),
    ]

    operations = [
        migrations.RunPython(set_old_dashboard_config, reverse_code=migrations.RunPython.noop),
    ]
