# Generated by Django 5.2.7 on 2026-01-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larpmanager', '0125_set_old_dashboard_config'),
    ]

    operations = [
        # Remove old constraints that enforce global slug uniqueness
        migrations.RemoveConstraint(
            model_name='event',
            name='unique_event_with_optional',
        ),
        migrations.RemoveConstraint(
            model_name='event',
            name='unique_event_without_optional',
        ),
        # Add new constraints that enforce slug uniqueness per association
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(
                fields=('association', 'slug', 'deleted'),
                name='unique_event_with_optional'
            ),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(
                condition=models.Q(('deleted', None)),
                fields=('association', 'slug'),
                name='unique_event_without_optional'
            ),
        ),
    ]
