# Generated by Django 5.2.7 on 2026-01-18 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larpmanager', '0126_fix_event_slug_unique_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='larpmanager.registrationticket'),
        ),
    ]
