# Generated by Django 5.2.7 on 2026-02-04 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larpmanager', '0134_alter_event_max_filler_alter_event_max_pg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refundrequest',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Indicates the amount of reimbursement desired (can't be higher than your current credits)", max_digits=10, verbose_name='Refund'),
        ),
    ]
