# Generated by Django 5.2.7 on 2026-02-22 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larpmanager', '0142_demo_default_true'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='dependencies',
            field=models.ManyToManyField(blank=True, related_name='dependents', to='larpmanager.feature'),
        ),
        migrations.AlterField(
            model_name='associationtext',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('it', 'Italiano'), ('es', 'Español'), ('de', 'Deutsch'), ('fr', 'Français'), ('cs', 'Čeština'), ('pl', 'Polski'), ('nl', 'Nederlands'), ('nb', 'Norsk'), ('sv', 'Svenska'), ('fi', 'suomi')], default='en', help_text='Text language', max_length=3, null=True, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='associationtranslation',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('it', 'Italiano'), ('es', 'Español'), ('de', 'Deutsch'), ('fr', 'Français'), ('cs', 'Čeština'), ('pl', 'Polski'), ('nl', 'Nederlands'), ('nb', 'Norsk'), ('sv', 'Svenska'), ('fi', 'suomi')], help_text="ISO language code (e.g., 'en', 'it', 'de')", max_length=3, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='eventtext',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('it', 'Italiano'), ('es', 'Español'), ('de', 'Deutsch'), ('fr', 'Français'), ('cs', 'Čeština'), ('pl', 'Polski'), ('nl', 'Nederlands'), ('nb', 'Norsk'), ('sv', 'Svenska'), ('fi', 'suomi')], default='en', help_text='Text language', max_length=3, null=True, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='member',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('it', 'Italiano'), ('es', 'Español'), ('de', 'Deutsch'), ('fr', 'Français'), ('cs', 'Čeština'), ('pl', 'Polski'), ('nl', 'Nederlands'), ('nb', 'Norsk'), ('sv', 'Svenska'), ('fi', 'suomi')], default='en', help_text='Preferred navigation language', max_length=3, null=True, verbose_name='Navigation language'),
        ),
    ]
