# Generated by Django 5.2.7 on 2026-04-14 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larpmanager', '0155_event_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='keywords',
            field=models.CharField(blank=True, help_text='Keywords describing the event', max_length=100, verbose_name='Keywords'),
        ),
    ]
