# Generated by Django 5.2.7 on 2026-05-16 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larpmanager', '0163_add_emailcontent_attachment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='birth_province',
            field=models.CharField(blank=True, help_text='If you were born in Italy, indicate your birth province; otherwise insert EE', max_length=2, null=True, verbose_name='Birth province'),
        ),
        migrations.AlterField(
            model_name='member',
            name='legal_name',
            field=models.CharField(blank=True, help_text='If for any reason the first and last name on your documents are different from the one you prefer to use, then write them here. Use a comma(,) to separate them, especially if composed by multiple words.. It will only be used for internal bureaucratic purposes, and will NEVER be displayed to other participants. ', max_length=100, null=True, verbose_name='Legal name'),
        ),
    ]
