# Generated by Django 5.2.7 on 2026-05-25 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('larpmanager', '0164_member_birth_province_alter_member_legal_name'),
        ('larpmanager', '0164_remove_player_cancellation_feature'),
    ]

    operations = [
    ]
