# Generated by Django 5.2.7 on 2026-05-26 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('larpmanager', '0165_merge_20260525_2039'),
        ('larpmanager', '0165_relationship_auto_field'),
    ]

    operations = [
    ]
