# Generated by Django 5.2.7 on 2026-07-16 12:15

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('larpmanager', '0176_alter_refundrequest_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guild',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=None, verbose_name='Color'),
        ),
    ]
