# Generated by Django 5.2.7 on 2026-07-15 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larpmanager', '0176_alter_refundrequest_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationquestion',
            name='applicable',
            field=models.CharField(choices=[('r', 'registration'), ('m', 'matchmaker')], default='r', help_text='Select which form this question belongs to', max_length=1, verbose_name='Applicable'),
        ),
        migrations.AddIndex(
            model_name='registrationquestion',
            index=models.Index(condition=models.Q(('deleted__isnull', True)), fields=['event', 'applicable'], name='rq_evt_app_act'),
        ),
    ]
