# Generated by Django 5.2.7 on 2026-08-26 13:55

import django.db.models.deletion
import django.utils.timezone
import model_clone.mixin
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larpmanager', '0190_writingoption_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('checked_in_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkins_performed', to='larpmanager.member')),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='check_in', to='larpmanager.registration')),
            ],
            options={
                'ordering': ['-updated'],
                'abstract': False,
            },
            bases=(model_clone.mixin.CloneMixin, models.Model),
        ),
        migrations.AlterField(
            model_name='associationtext',
            name='typ',
            field=models.CharField(
                choices=[('p', 'Profile'), ('h', 'Calendar'), ('u', 'Registration email'), ('m', 'Membership request'),
                         ('s', 'Association Statute'), ('l', 'Legal notice'), ('f', 'Footer'),
                         ('t', 'Terms and Conditions'), ('r', 'Receipt'), ('g', 'Mail signature'), ('y', 'Privacy'),
                         ('rm', 'Membership request reminder email'), ('rf', 'Membership request reminder email'),
                         ('rp', 'Payment reminder email'), ('rr', 'Profile completion reminder email'),
                         ('rc', 'Character creation reminder email')], help_text='Type of text', max_length=2,
                verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='registrationquestion',
            name='status',
            field=models.CharField(choices=[('o', 'Optional'), ('m', 'Mandatory'), ('d', 'Read only'), ('h', 'Hidden')],
                                   default='o', max_length=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='writingquestion',
            name='status',
            field=models.CharField(choices=[('o', 'Optional'), ('m', 'Mandatory'), ('d', 'Read only'), ('h', 'Hidden')],
                                   default='o', max_length=1, verbose_name='Status'),
        ),
    ]
