# Generated by Django 5.2.7 on 2026-09-05 18:02

import csv
from pathlib import Path

from django.conf import settings as conf_settings
from django.db import migrations, models


def _load_province_map():
    """Build comune-name-slug -> province-sigla map from data/Elenco-comuni-italiani.csv."""
    from larpmanager.utils.users.municipalities import _slugify

    province_map = {}
    csv_path = Path(conf_settings.BASE_DIR) / ".." / "data" / "Elenco-comuni-italiani.csv"
    with csv_path.open(encoding="utf-8") as csv_file:
        reader = csv.reader(csv_file)
        next(reader)
        for row in reader:
            comune_name, province_sigla = row[5], row[14]
            province_map[_slugify(comune_name)] = province_sigla
    return province_map


def populate_birth_province(apps, schema_editor):
    """One-time backfill of birth_province for Italian members, derived from birth_place."""
    from larpmanager.utils.users.municipalities import _slugify
    from larpmanager.utils.users.municipalities import _clean_birth_place

    Member = apps.get_model("larpmanager", "Member")
    province_map = _load_province_map()

    members = Member.objects.filter(nationality="IT", birth_place__isnull=False).exclude(birth_place="")
    for member in members.iterator():
        slug = _slugify(_clean_birth_place(member.birth_place))
        province = province_map.get(slug)
        if province:
            member.birth_province = province
            member.save(update_fields=["birth_province"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('larpmanager', '0191_checkin'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='birth_province',
            field=models.CharField(blank=True, help_text='Province where you were born (code)', max_length=150, null=True, verbose_name='Birth province'),
        ),
        migrations.AlterField(
            model_name='member',
            name='birth_place',
            field=models.CharField(blank=True, help_text='City where you were born (full name)', max_length=150, null=True, verbose_name='Birth place'),
        ),
        migrations.RunPython(populate_birth_province, noop),
    ]
