# Generated by Django 5.2.7 on 2026-09-22 09:23

import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ("larpmanager", "0193_member_flag_def"),
    ]

    operations = [
        migrations.AlterField(
            model_name="associationconfig",
            name="value",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="config",
            name="value",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="eventconfig",
            name="value",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="memberconfig",
            name="value",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="runconfig",
            name="value",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='onetimeaccesstoken',
            name='used_by',
            field=models.ForeignKey(blank=True, help_text='User who used this token (if authenticated)', null=True,
                                    on_delete=django.db.models.deletion.SET_NULL, related_name='used_onetime_tokens',
                                    to='larpmanager.member', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='writingquestion',
            name='typ',
            field=models.CharField(choices=[('s', 'Single choice'), ('m', 'Multiple choice'), ('t', 'Single-line text'),
                                            ('p', 'Multi-line text'), ('e', 'Advanced text editor'), ('name', 'Name'),
                                            ('teaser', 'Presentation'), ('text', 'Sheet'), ('cover', 'Cover'),
                                            ('faction', 'Factions'), ('title', 'Title'), ('mirror', 'Mirror'),
                                            ('file', 'File'), ('hide', 'Hide'), ('locked', 'Locked'),
                                            ('progress', 'Progress'), ('assigned', 'Assignment'), ('c', 'Computed')],
                                   default='s', help_text='Question type', max_length=10, verbose_name='Type'),
        ),
    ]
