# Generated by Django 5.2.7 on 2026-09-22 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("larpmanager", "0193_member_flag_def"),
    ]

    operations = [
        migrations.AlterField(
            model_name="associationconfig",
            name="value",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="config",
            name="value",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="eventconfig",
            name="value",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="memberconfig",
            name="value",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="runconfig",
            name="value",
            field=models.TextField(),
        ),
    ]
