# Generated by Django 5.2.17 on 2026-10-06 08:31

import django.db.models.deletion
import django.utils.timezone
import model_clone.mixin
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larpmanager', '0194_alter_associationconfig_value_alter_config_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associationtext',
            name='typ',
            field=models.CharField(choices=[('p', 'Profile'), ('h', 'Calendar'), ('u', 'Registration email'), ('m', 'Membership request'), ('s', 'Association Statute'), ('l', 'Legal notice'), ('f', 'Footer'), ('t', 'Terms and Conditions'), ('r', 'Receipt'), ('g', 'Mail signature'), ('y', 'Privacy'), ('rm', 'Membership request reminder email'), ('rf', 'Membership fee reminder email'), ('rp', 'Payment reminder email'), ('rr', 'Profile completion reminder email'), ('rc', 'Character creation reminder email')], help_text='Type of text', max_length=2, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='writingquestion',
            name='typ',
            field=models.CharField(choices=[('s', 'Single choice'), ('m', 'Multiple choice'), ('t', 'Single-line text'), ('p', 'Multi-line text'), ('e', 'Advanced text editor'), ('name', 'Name'), ('teaser', 'Presentation'), ('text', 'Sheet'), ('cover', 'Cover'), ('faction', 'Factions'), ('title', 'Title'), ('concept', 'Concept'), ('mirror', 'Mirror'), ('file', 'File'), ('hide', 'Hide'), ('locked', 'Locked'), ('progress', 'Progress'), ('assigned', 'Assignment'), ('c', 'Computed')], default='s', help_text='Question type', max_length=10, verbose_name='Type'),
        ),
        migrations.CreateModel(
            name='CallExp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('uuid', models.CharField(db_index=True, editable=False, max_length=12, unique=True)),
                ('order', models.IntegerField(default=0)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=150)),
                ('descr', tinymce.models.HTMLField(blank=True, max_length=5000, null=True, verbose_name='Description')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='larpmanager.event')),
            ],
            options={
                'indexes': [models.Index(fields=['number', 'event'], name='larpmanager_number_73d5d2_idx')],
                'constraints': [models.UniqueConstraint(fields=('event', 'number', 'deleted'), name='unique_call_with_optional'), models.UniqueConstraint(condition=models.Q(('deleted', None)), fields=('event', 'number'), name='unique_call_without_optional')],
            },
            bases=(model_clone.mixin.CloneMixin, models.Model),
        ),
    ]
