# LarpManager - https://larpmanager.com
# Copyright (C) 2025 Scanagatta Mauro
#
# This file is part of LarpManager and is dual-licensed:
#
# 1. Under the terms of the GNU Affero General Public License (AGPL) version 3,
#    as published by the Free Software Foundation. You may use, modify, and
#    distribute this file under those terms.
#
# 2. Under a commercial license, allowing use in closed-source or proprietary
#    environments without the obligations of the AGPL.
#
# If you have obtained this file under the AGPL, and you make it available over
# a network, you must also make the complete source code available under the same license.
#
# For more information or to purchase a commercial license, contact:
# commercial@larpmanager.com
#
# SPDX-License-Identifier: AGPL-3.0-or-later OR Proprietary

from django.urls import path

from larpmanager.views import manage as views_mg
from larpmanager.views.exe import accounting as views_ea
from larpmanager.views.exe import assoc as views_eas
from larpmanager.views.exe import event as views_ee
from larpmanager.views.exe import member as views_em
from larpmanager.views.exe import miscellanea as views_ems

urlpatterns = [
    path(
        "manage/",
        views_mg.manage,
        name="manage",
    ),
    path(
        "manage/quick/",
        views_eas.exe_quick,
        name="exe_quick",
    ),
    path(
        "manage/deadlines/",
        views_ee.exe_deadlines,
        name="exe_deadlines",
    ),
    path(
        "manage/urlshortner/",
        views_ems.exe_urlshortner,
        name="exe_urlshortner",
    ),
    path(
        "manage/urlshortner/edit/<int:num>/",
        views_ems.exe_urlshortner_edit,
        name="exe_urlshortner_edit",
    ),
    path(
        "manage/inventory/",
        views_ems.exe_inventory,
        name="exe_inventory",
    ),
    path(
        "manage/inventory/edit/<int:num>/",
        views_ems.exe_inventory_edit,
        name="exe_inventory_edit",
    ),
    path(
        "manage/inventory/<int:num>/history",
        views_ems.exe_inventory_history,
        name="exe_inventory_history",
    ),
    path(
        "manage/badges/",
        views_em.exe_badges,
        name="exe_badges",
    ),
    path(
        "manage/badges/edit/<int:num>/",
        views_em.exe_badges_edit,
        name="exe_badges_edit",
    ),
    path(
        "manage/mail/send",
        views_em.exe_send_mail,
        name="exe_send_mail",
    ),
    path(
        "manage/mail/archive",
        views_em.exe_archive_email,
        name="exe_archive_email",
    ),
    path(
        "manage/questions/",
        views_em.exe_questions,
        name="exe_questions",
    ),
    path(
        "manage/questions/<int:r>/answer/",
        views_em.exe_questions_answer,
        name="exe_questions_answer",
    ),
    path(
        "manage/questions/<int:r>/close/",
        views_em.exe_questions_close,
        name="exe_questions_close",
    ),
    path(
        "manage/newsletter/",
        views_em.exe_newsletter,
        name="exe_newsletter",
    ),
    path(
        "manage/newsletter/csv/<slug:lang>/",
        views_em.exe_newsletter_csv,
        name="exe_newsletter_csv",
    ),
    path(
        "manage/organization/",
        views_eas.exe_association,
        name="exe_association",
    ),
    path(
        "manage/appearance/",
        views_eas.exe_appearance,
        name="exe_appearance",
    ),
    path(
        "manage/config/<slug:section>/",
        views_eas.exe_config,
        name="exe_config",
    ),
    path(
        "manage/config/",
        views_eas.exe_config,
        name="exe_config",
    ),
    path(
        "manage/profile/",
        views_eas.exe_profile,
        name="exe_profile",
    ),
    path(
        "manage/payments/details/",
        views_eas.exe_payment_details,
        name="exe_payment_details",
    ),
    path(
        "manage/texts/",
        views_eas.exe_texts,
        name="exe_texts",
    ),
    path(
        "manage/texts/edit/<int:num>/",
        views_eas.exe_texts_edit,
        name="exe_texts_edit",
    ),
    path(
        "manage/roles/",
        views_eas.exe_roles,
        name="exe_roles",
    ),
    path(
        "manage/roles/edit/<int:num>/",
        views_eas.exe_roles_edit,
        name="exe_roles_edit",
    ),
    path(
        "manage/balance/",
        views_ea.exe_balance,
        name="exe_balance",
    ),
    path(
        "manage/verification/",
        views_ea.exe_verification,
        name="exe_verification",
    ),
    path(
        "manage/verification/manual/<int:num>",
        views_ea.exe_verification_manual,
        name="exe_verification_manual",
    ),
    path(
        "manage/features/",
        views_eas.exe_features,
        name="exe_features",
    ),
    path(
        "manage/features/<int:num>/on/",
        views_eas.exe_features_on,
        name="exe_features_on",
    ),
    path(
        "manage/features/<int:num>/off/",
        views_eas.exe_features_off,
        name="exe_features_off",
    ),
    path(
        "manage/pre_registrations/",
        views_ee.exe_pre_registrations,
        name="exe_pre_registrations",
    ),
    path(
        "manage/credits/",
        views_ea.exe_credits,
        name="exe_credits",
    ),
    path(
        "manage/credits/edit/<int:num>/",
        views_ea.exe_credits_edit,
        name="exe_credits_edit",
    ),
    path(
        "manage/tokens/",
        views_ea.exe_tokens,
        name="exe_tokens",
    ),
    path(
        "manage/tokens/edit/<int:num>/",
        views_ea.exe_tokens_edit,
        name="exe_tokens_edit",
    ),
    path(
        "manage/payments/",
        views_ea.exe_payments,
        name="exe_payments",
    ),
    path(
        "manage/payments/edit/<int:num>/",
        views_ea.exe_payments_edit,
        name="exe_payments_edit",
    ),
    path(
        "manage/invoices/",
        views_ea.exe_invoices,
        name="exe_invoices",
    ),
    path(
        "manage/invoices/edit/<int:num>/",
        views_ea.exe_invoices_edit,
        name="exe_invoices_edit",
    ),
    path(
        "manage/invoices/confirm/<int:num>/",
        views_ea.exe_invoices_confirm,
        name="exe_invoices_confirm",
    ),
    path(
        "manage/expenses/",
        views_ea.exe_expenses,
        name="exe_expenses",
    ),
    path(
        "manage/expenses/edit/<int:num>/",
        views_ea.exe_expenses_edit,
        name="exe_expenses_edit",
    ),
    path(
        "manage/expenses/approve/<int:num>/",
        views_ea.exe_expenses_approve,
        name="exe_expenses_approve",
    ),
    path(
        "manage/membership/",
        views_em.exe_membership,
        name="exe_membership",
    ),
    path(
        "manage/membership/<int:num>/",
        views_em.exe_member,
        name="exe_member",
    ),
    path(
        "manage/membership/evaluation/<int:num>/",
        views_em.exe_membership_evaluation,
        name="exe_membership_evaluation",
    ),
    path(
        "manage/membership/status/<int:num>/",
        views_em.exe_membership_status,
        name="exe_membership_status",
    ),
    path(
        "manage/membership/request/<int:num>/",
        views_em.exe_membership_request,
        name="exe_membership_request",
    ),
    path(
        "manage/membership/check/",
        views_em.exe_membership_check,
        name="exe_membership_check",
    ),
    path(
        "manage/membership/registry/",
        views_em.exe_membership_registry,
        name="exe_membership_registry",
    ),
    path(
        "manage/events/",
        views_ee.exe_events,
        name="exe_events",
    ),
    path(
        "manage/events/edit/<int:num>/",
        views_ee.exe_events_edit,
        name="exe_events_edit",
    ),
    path(
        "manage/template/",
        views_ee.exe_templates,
        name="exe_templates",
    ),
    path(
        "manage/template/edit/<int:num>/",
        views_ee.exe_templates_edit,
        name="exe_templates_edit",
    ),
    path(
        "manage/template/config/<int:num>/",
        views_ee.exe_templates_config,
        name="exe_templates_config",
    ),
    path(
        "manage/template/roles/<int:eid>/<int:num>/",
        views_ee.exe_templates_roles,
        name="exe_templates_roles",
    ),
    path(
        "manage/vote/",
        views_em.exe_vote,
        name="exe_vote",
    ),
    path(
        "manage/runs/edit/<int:num>/",
        views_ee.exe_runs_edit,
        name="exe_runs_edit",
    ),
    path(
        "manage/outflows/",
        views_ea.exe_outflows,
        name="exe_outflows",
    ),
    path(
        "manage/outflows/edit/<int:num>/",
        views_ea.exe_outflows_edit,
        name="exe_outflows_edit",
    ),
    path(
        "manage/inflows/",
        views_ea.exe_inflows,
        name="exe_inflows",
    ),
    path(
        "manage/inflows/edit/<int:num>/",
        views_ea.exe_inflows_edit,
        name="exe_inflows_edit",
    ),
    path(
        "manage/collections/",
        views_ea.exe_collections,
        name="exe_collections",
    ),
    path(
        "manage/collections/<int:num>/",
        views_ea.exe_collections_edit,
        name="exe_collections_edit",
    ),
    path(
        "manage/donations/",
        views_ea.exe_donations,
        name="exe_donations",
    ),
    path(
        "manage/donations/edit/<int:num>/",
        views_ea.exe_donations_edit,
        name="exe_donations_edit",
    ),
    path(
        "manage/refunds/",
        views_ea.exe_refunds,
        name="exe_refunds",
    ),
    path(
        "manage/refunds/edit/<int:num>/",
        views_ea.exe_refunds_edit,
        name="exe_refunds_edit",
    ),
    path(
        "manage/refunds/confirm/<int:num>/",
        views_ea.exe_refunds_confirm,
        name="exe_refunds_confirm",
    ),
    path(
        "manage/enrolment/",
        views_em.exe_enrolment,
        name="exe_enrolment",
    ),
    path(
        "manage/accounting/",
        views_ea.exe_accounting,
        name="exe_accounting",
    ),
    path(
        "manage/accounting/year",
        views_ea.exe_year_accounting,
        name="exe_year_accounting",
    ),
    path(
        "manage/accounting/run/<int:num>/",
        views_ea.exe_run_accounting,
        name="exe_run_accounting",
    ),
    path(
        "manage/accounting/record/",
        views_ea.exe_accounting_rec,
        name="exe_accounting_rec",
    ),
    path(
        "manage/volunteer_registry/",
        views_em.exe_volunteer_registry,
        name="exe_volunteer_registry",
    ),
    path(
        "manage/volunteer_registry/edit/<int:num>/",
        views_em.exe_volunteer_registry_edit,
        name="exe_volunteer_registry_edit",
    ),
    path(
        "manage/volunteer_registry/print",
        views_em.exe_volunteer_registry_print,
        name="exe_volunteer_registry_print",
    ),
    path(
        "manage/larpmanager/",
        views_eas.exe_larpmanager,
        name="exe_larpmanager",
    ),
    path(
        "feature/description/",
        views_eas.feature_description,
        name="feature_description",
    ),
    path(
        "manage/suggestions/<slug:perm>/",
        views_mg.exe_close_suggestion,
        name="exe_close_suggestion",
    ),
]
