# LarpManager - https://larpmanager.com
# Copyright (C) 2025 Scanagatta Mauro
#
# This file is part of LarpManager and is dual-licensed:
#
# 1. Under the terms of the GNU Affero General Public License (AGPL) version 3,
#    as published by the Free Software Foundation. You may use, modify, and
#    distribute this file under those terms.
#
# 2. Under a commercial license, allowing use in closed-source or proprietary
#    environments without the obligations of the AGPL.
#
# If you have obtained this file under the AGPL, and you make it available over
# a network, you must also make the complete source code available under the same license.
#
# For more information or to purchase a commercial license, contact:
# commercial@larpmanager.com
#
# SPDX-License-Identifier: AGPL-3.0-or-later OR Proprietary

from django.urls import path

from larpmanager.views import manage as views_mg
from larpmanager.views.orga import accounting as views_oa
from larpmanager.views.orga import casting as views_oca
from larpmanager.views.orga import character as views_oc
from larpmanager.views.orga import copy as views_oy
from larpmanager.views.orga import event as views_oe
from larpmanager.views.orga import experience as views_ox
from larpmanager.views.orga import form as views_of
from larpmanager.views.orga import member as views_om
from larpmanager.views.orga import miscellanea as views_oms
from larpmanager.views.orga import pdf as views_op
from larpmanager.views.orga import registration as views_or
from larpmanager.views.orga import writing as views_ow

urlpatterns = [
    path(
        "<slug:s>/manage/",
        views_mg.manage,
        name="manage",
    ),
    path(
        "<slug:s>/manage/quick/",
        views_oe.orga_quick,
        name="orga_quick",
    ),
    path(
        "<slug:s>/manage/mail/read/<int:nm>",
        views_om.orga_read_mail,
        name="orga_read_mail",
    ),
    path(
        "<slug:s>/manage/pre_registrations/",
        views_or.orga_pre_registrations,
        name="orga_pre_registrations",
    ),
    path(
        "<slug:s>/manage/assignments/",
        views_ow.orga_assignments,
        name="orga_assignments",
    ),
    path(
        "<slug:s>/manage/casting/preferences/",
        views_oca.orga_casting_preferences,
        name="orga_casting_preferences",
    ),
    path(
        "<slug:s>/manage/casting/preferences/<int:typ>/",
        views_oca.orga_casting_preferences,
        name="orga_casting_preferences",
    ),
    path(
        "<slug:s>/manage/casting/history/",
        views_oca.orga_casting_history,
        name="orga_casting_history",
    ),
    path(
        "<slug:s>/manage/casting/history/<int:typ>/",
        views_oca.orga_casting_history,
        name="orga_casting_history",
    ),
    path(
        "<slug:s>/manage/registrations/",
        views_or.orga_registrations,
        name="orga_registrations",
    ),
    path(
        "<slug:s>/manage/registrations/edit/<int:num>/",
        views_or.orga_registrations_edit,
        name="orga_registrations_edit",
    ),
    path(
        "<slug:s>/manage/registrations/<int:num>/discounts/",
        views_or.orga_registration_discounts,
        name="orga_registration_discounts",
    ),
    path(
        "<slug:s>/manage/registrations/<int:num>/customization/",
        views_or.orga_registrations_customization,
        name="orga_registrations_customization",
    ),
    path(
        "<slug:s>/manage/registrations/<int:num>/discounts/add/<int:dis>/",
        views_or.orga_registration_discount_add,
        name="orga_registration_discount_add",
    ),
    path(
        "<slug:s>/manage/registrations/<int:num>/discounts/del/<int:dis>/",
        views_or.orga_registration_discount_del,
        name="orga_registration_discount_del",
    ),
    path(
        "<slug:s>/manage/registrations/reload",
        views_or.orga_registrations_reload,
        name="orga_registrations_reload",
    ),
    path(
        "<slug:s>/manage/registrations/accounting",
        views_or.orga_registrations_accounting,
        name="orga_registrations_accounting",
    ),
    path(
        "<slug:s>/manage/deadlines/",
        views_oe.orga_deadlines,
        name="orga_deadlines",
    ),
    path(
        "<slug:s>/manage/discounts/",
        views_oa.orga_discounts,
        name="orga_discounts",
    ),
    path(
        "<slug:s>/manage/discounts/edit/<int:num>/",
        views_oa.orga_discounts_edit,
        name="orga_discounts_edit",
    ),
    path(
        "<slug:s>/manage/tickets/",
        views_of.orga_registration_tickets,
        name="orga_registration_tickets",
    ),
    path(
        "<slug:s>/manage/tickets/edit/<int:num>/",
        views_of.orga_registration_tickets_edit,
        name="orga_registration_tickets_edit",
    ),
    path(
        "<slug:s>/manage/tickets/order/<int:num>/<int:order>/",
        views_of.orga_registration_tickets_order,
        name="orga_registration_tickets_order",
    ),
    path(
        "<slug:s>/manage/sections/",
        views_of.orga_registration_sections,
        name="orga_registration_sections",
    ),
    path(
        "<slug:s>/manage/sections/edit/<int:num>/",
        views_of.orga_registration_sections_edit,
        name="orga_registration_sections_edit",
    ),
    path(
        "<slug:s>/manage/sections/order/<int:num>/<int:order>/",
        views_of.orga_registration_sections_order,
        name="orga_registration_sections_order",
    ),
    path(
        "<slug:s>/manage/form/",
        views_of.orga_registration_form,
        name="orga_registration_form",
    ),
    path(
        "<slug:s>/manage/form/edit/<int:num>/",
        views_of.orga_registration_form_edit,
        name="orga_registration_form_edit",
    ),
    path(
        "<slug:s>/manage/form/order/<int:num>/<int:order>/",
        views_of.orga_registration_form_order,
        name="orga_registration_form_order",
    ),
    path(
        "<slug:s>/manage/form/list/",
        views_or.orga_registration_form_list,
        name="orga_registration_form_list",
    ),
    path(
        "<slug:s>/manage/form/email/",
        views_or.orga_registration_form_email,
        name="orga_registration_form_email",
    ),
    path(
        "<slug:s>/manage/options/edit/<int:num>/",
        views_of.orga_registration_options_edit,
        name="orga_registration_options_edit",
    ),
    path(
        "<slug:s>/manage/options/new/<int:num>/",
        views_of.orga_registration_options_new,
        name="orga_registration_options_new",
    ),
    path(
        "<slug:s>/manage/options/order/<int:num>/<int:order>/",
        views_of.orga_registration_options_order,
        name="orga_registration_options_order",
    ),
    path(
        "<slug:s>/manage/quotas/",
        views_of.orga_registration_quotas,
        name="orga_registration_quotas",
    ),
    path(
        "<slug:s>/manage/quotas/edit/<int:num>/",
        views_of.orga_registration_quotas_edit,
        name="orga_registration_quotas_edit",
    ),
    path(
        "<slug:s>/manage/installments/",
        views_of.orga_registration_installments,
        name="orga_registration_installments",
    ),
    path(
        "<slug:s>/manage/installments/edit/<int:num>/",
        views_of.orga_registration_installments_edit,
        name="orga_registration_installments_edit",
    ),
    path(
        "<slug:s>/manage/surcharges/",
        views_of.orga_registration_surcharges,
        name="orga_registration_surcharges",
    ),
    path(
        "<slug:s>/manage/surcharges/edit/<int:num>/",
        views_of.orga_registration_surcharges_edit,
        name="orga_registration_surcharges_edit",
    ),
    path(
        "<slug:s>/manage/cancellations/",
        views_or.orga_cancellations,
        name="orga_cancellations",
    ),
    path(
        "<slug:s>/manage/cancellations/<int:num>/refund/",
        views_or.orga_cancellation_refund,
        name="orga_cancellation_refund",
    ),
    path(
        "<slug:s>/manage/registrations/member",
        views_or.orga_registration_member,
        name="orga_registration_member",
    ),
    path(
        "<slug:s>/manage/albums/",
        views_oms.orga_albums,
        name="orga_albums",
    ),
    path(
        "<slug:s>/manage/albums/edit/<int:num>/",
        views_oms.orga_albums_edit,
        name="orga_albums_edit",
    ),
    path(
        "<slug:s>/manage/albums/<slug:a>/upload/",
        views_oms.orga_albums_upload,
        name="orga_albums_upload",
    ),
    path(
        "<slug:s>/manage/pdf/",
        views_op.orga_characters_pdf,
        name="orga_characters_pdf",
    ),
    path(
        "<slug:s>/manage/cache/",
        views_or.orga_reload_cache,
        name="orga_reload_cache",
    ),
    path(
        "<slug:s>/manage/characters/<int:num>/pdf/sheet/",
        views_op.orga_characters_sheet_pdf,
        name="orga_characters_sheet_pdf",
    ),
    path(
        "<slug:s>/manage/characters/<int:num>/pdf/sheet/test/",
        views_op.orga_characters_sheet_test,
        name="orga_characters_sheet_test",
    ),
    path(
        "<slug:s>/manage/characters/<int:num>/pdf/relationships/",
        views_op.orga_characters_relationships_pdf,
        name="orga_characters_relationships_pdf",
    ),
    path(
        "<slug:s>/manage/characters/<int:num>/pdf/relationships/test/",
        views_op.orga_characters_relationships_test,
        name="orga_characters_relationships_test",
    ),
    path(
        "<slug:s>/manage/characters/<int:num>/pdf/friendly/",
        views_op.orga_characters_friendly_pdf,
        name="orga_characters_friendly_pdf",
    ),
    path(
        "<slug:s>/manage/characters/<int:num>/pdf/friendly/test/",
        views_op.orga_characters_friendly_test,
        name="orga_characters_friendly_test",
    ),
    path(
        "<slug:s>/manage/pdf/gallery/pdf/",
        views_op.orga_gallery_pdf,
        name="orga_gallery_pdf",
    ),
    path(
        "<slug:s>/manage/pdf/gallery/test/",
        views_op.orga_gallery_test,
        name="orga_gallery_test",
    ),
    path(
        "<slug:s>/manage/pdf/profiles/pdf/",
        views_op.orga_profiles_pdf,
        name="orga_profiles_pdf",
    ),
    path(
        "<slug:s>/manage/pdf/regenerate",
        views_op.orga_pdf_regenerate,
        name="orga_pdf_regenerate",
    ),
    path(
        "<slug:s>/manage/characters/",
        views_oc.orga_characters,
        name="orga_characters",
    ),
    path(
        "<slug:s>/manage/characters/<int:num>/view/",
        views_oc.orga_characters_view,
        name="orga_characters_view",
    ),
    path(
        "<slug:s>/manage/characters/edit/<int:num>/",
        views_oc.orga_characters_edit,
        name="orga_characters_edit",
    ),
    path(
        "<slug:s>/manage/characters/<int:num>/versions/",
        views_oc.orga_characters_versions,
        name="orga_characters_versions",
    ),
    path(
        "<slug:s>/manage/characters/<int:num>/summary/",
        views_oc.orga_characters_summary,
        name="orga_characters_summary",
    ),
    path(
        "<slug:s>/manage/characters/get/number/",
        views_oc.orga_character_get_number,
        name="orga_character_get_number",
    ),
    path(
        "<slug:s>/manage/characters/<int:num>/relationships/",
        views_oc.orga_characters_relationships,
        name="orga_characters_relationships",
    ),
    path(
        "<slug:s>/manage/check/",
        views_oc.orga_check,
        name="orga_check",
    ),
    path(
        "<slug:s>/manage/writing/form/",
        views_oc.orga_character_form,
        name="orga_character_form",
    ),
    path(
        "<slug:s>/manage/writing/form/<slug:typ>/",
        views_oc.orga_writing_form,
        name="orga_writing_form",
    ),
    path(
        "<slug:s>/manage/writing/form/<slug:typ>/edit/<int:num>/",
        views_oc.orga_writing_form_edit,
        name="orga_writing_form_edit",
    ),
    path(
        "<slug:s>/manage/writing/form/<slug:typ>/order/<int:num>/<int:order>/",
        views_oc.orga_writing_form_order,
        name="orga_writing_form_order",
    ),
    path(
        "<slug:s>/manage/writing/form/<slug:typ>/list",
        views_oc.orga_writing_form_list,
        name="orga_writing_form_list",
    ),
    path(
        "<slug:s>/manage/writing/form/<slug:typ>/email",
        views_oc.orga_writing_form_email,
        name="orga_writing_form_email",
    ),
    path(
        "<slug:s>/manage/writing/options/<slug:typ>/edit/<int:num>/",
        views_oc.orga_writing_options_edit,
        name="orga_writing_options_edit",
    ),
    path(
        "<slug:s>/manage/writing/options/<slug:typ>/new/<int:num>/",
        views_oc.orga_writing_options_new,
        name="orga_writing_options_new",
    ),
    path(
        "<slug:s>/manage/writing/options/<slug:typ>/order/<int:num>/<int:order>/",
        views_oc.orga_writing_options_order,
        name="orga_writing_options_order",
    ),
    path(
        "<slug:s>/manage/writing/edit/<slug:typ>/",
        views_oc.orga_writing_excel_edit,
        name="orga_writing_excel_edit",
    ),
    path(
        "<slug:s>/manage/writing/submit/<slug:typ>/",
        views_oc.orga_writing_excel_submit,
        name="orga_writing_excel_submit",
    ),
    path(
        "<slug:s>/manage/utils/",
        views_oms.orga_utils,
        name="orga_utils",
    ),
    path(
        "<slug:s>/manage/utils/edit/<int:num>/",
        views_oms.orga_utils_edit,
        name="orga_utils_edit",
    ),
    path(
        "<slug:s>/manage/onetimes/",
        views_oms.orga_onetimes,
        name="orga_onetimes",
    ),
    path(
        "<slug:s>/manage/onetimes/edit/<int:num>/",
        views_oms.orga_onetimes_edit,
        name="orga_onetimes_edit",
    ),
    path(
        "<slug:s>/manage/onetimes/<int:num>/tokens/",
        views_oms.orga_onetimes_tokens,
        name="orga_onetimes_tokens",
    ),
    path(
        "<slug:s>/manage/onetimes/<int:content_num>/tokens/edit/<int:num>/",
        views_oms.orga_onetimes_tokens_edit,
        name="orga_onetimes_tokens_edit",
    ),
    path(
        "<slug:s>/manage/newsletter/",
        views_om.orga_newsletter,
        name="orga_newsletter",
    ),
    path(
        "<slug:s>/manage/plots/",
        views_ow.orga_plots,
        name="orga_plots",
    ),
    path(
        "<slug:s>/manage/plots/<int:num>/view/",
        views_ow.orga_plots_view,
        name="orga_plots_view",
    ),
    path(
        "<slug:s>/manage/plots/edit/<int:num>/",
        views_ow.orga_plots_edit,
        name="orga_plots_edit",
    ),
    path(
        "<slug:s>/manage/plots/order/<int:num>/<int:order>/",
        views_ow.orga_plots_order,
        name="orga_plots_order",
    ),
    path(
        "<slug:s>/manage/plots/<int:num>/versions/",
        views_ow.orga_plots_versions,
        name="orga_plots_versions",
    ),
    path(
        "<slug:s>/manage/plots/rels/order/<int:num>/<int:order>/",
        views_ow.orga_plots_rels_order,
        name="orga_plots_rels_order",
    ),
    path(
        "<slug:s>/manage/factions/",
        views_ow.orga_factions,
        name="orga_factions",
    ),
    path(
        "<slug:s>/manage/factions/<int:num>/view/",
        views_ow.orga_factions_view,
        name="orga_factions_view",
    ),
    path(
        "<slug:s>/manage/factions/edit/<int:num>/",
        views_ow.orga_factions_edit,
        name="orga_factions_edit",
    ),
    path(
        "<slug:s>/manage/factions/order/<int:num>/<int:order>/",
        views_ow.orga_factions_order,
        name="orga_factions_order",
    ),
    path(
        "<slug:s>/manage/factions/<int:num>/versions/",
        views_ow.orga_factions_versions,
        name="orga_factions_versions",
    ),
    path(
        "<slug:s>/manage/quest_types/",
        views_ow.orga_quest_types,
        name="orga_quest_types",
    ),
    path(
        "<slug:s>/manage/quest_types/<int:num>/view/",
        views_ow.orga_quest_types_view,
        name="orga_quest_types_view",
    ),
    path(
        "<slug:s>/manage/quest_types/edit/<int:num>/",
        views_ow.orga_quest_types_edit,
        name="orga_quest_types_edit",
    ),
    path(
        "<slug:s>/manage/quest_types/<int:num>/versions/",
        views_ow.orga_quest_types_versions,
        name="orga_quest_types_versions",
    ),
    path(
        "<slug:s>/manage/quests/",
        views_ow.orga_quests,
        name="orga_quests",
    ),
    path(
        "<slug:s>/manage/quests/<int:num>/view/",
        views_ow.orga_quests_view,
        name="orga_quests_view",
    ),
    path(
        "<slug:s>/manage/quests/edit/<int:num>/",
        views_ow.orga_quests_edit,
        name="orga_quests_edit",
    ),
    path(
        "<slug:s>/manage/quests/<int:num>/versions/",
        views_ow.orga_quests_versions,
        name="orga_quests_versions",
    ),
    path(
        "<slug:s>/manage/traits/",
        views_ow.orga_traits,
        name="orga_traits",
    ),
    path(
        "<slug:s>/manage/traits/<int:num>/view/",
        views_ow.orga_traits_view,
        name="orga_traits_view",
    ),
    path(
        "<slug:s>/manage/traits/edit/<int:num>/",
        views_ow.orga_traits_edit,
        name="orga_traits_edit",
    ),
    path(
        "<slug:s>/manage/traits/<int:num>/versions/",
        views_ow.orga_traits_versions,
        name="orga_traits_versions",
    ),
    path(
        "<slug:s>/manage/handout_templates/",
        views_ow.orga_handout_templates,
        name="orga_handout_templates",
    ),
    path(
        "<slug:s>/manage/handout_templates/edit/<int:num>/",
        views_ow.orga_handout_templates_edit,
        name="orga_handout_templates_edit",
    ),
    path(
        "<slug:s>/manage/handouts/",
        views_ow.orga_handouts,
        name="orga_handouts",
    ),
    path(
        "<slug:s>/manage/handouts/<int:num>/view/",
        views_ow.orga_handouts_view,
        name="orga_handouts_view",
    ),
    path(
        "<slug:s>/manage/handouts/edit/<int:num>/",
        views_ow.orga_handouts_edit,
        name="orga_handouts_edit",
    ),
    path(
        "<slug:s>/manage/handouts/<int:num>/versions/",
        views_ow.orga_handouts_versions,
        name="orga_handouts_versions",
    ),
    path(
        "<slug:s>/manage/handouts/<int:num>/test/",
        views_ow.orga_handouts_test,
        name="orga_handouts_test",
    ),
    path(
        "<slug:s>/manage/handouts/<int:num>/print/",
        views_ow.orga_handouts_print,
        name="orga_handouts_print",
    ),
    path(
        "<slug:s>/manage/prologue_types/",
        views_ow.orga_prologue_types,
        name="orga_prologue_types",
    ),
    path(
        "<slug:s>/manage/prologue_types/edit/<int:num>/",
        views_ow.orga_prologue_types_edit,
        name="orga_prologue_types_edit",
    ),
    path(
        "<slug:s>/manage/prologues/",
        views_ow.orga_prologues,
        name="orga_prologues",
    ),
    path(
        "<slug:s>/manage/prologues/<int:num>/view/",
        views_ow.orga_prologues_view,
        name="orga_prologues_view",
    ),
    path(
        "<slug:s>/manage/prologues/edit/<int:num>/",
        views_ow.orga_prologues_edit,
        name="orga_prologues_edit",
    ),
    path(
        "<slug:s>/manage/prologues/<int:num>/versions/",
        views_ow.orga_prologues_versions,
        name="orga_prologues_versions",
    ),
    path(
        "<slug:s>/manage/speedlarps/",
        views_ow.orga_speedlarps,
        name="orga_speedlarps",
    ),
    path(
        "<slug:s>/manage/speedlarps/<int:num>/view/",
        views_ow.orga_speedlarps_view,
        name="orga_speedlarps_view",
    ),
    path(
        "<slug:s>/manage/speedlarps/edit/<int:num>/",
        views_ow.orga_speedlarps_edit,
        name="orga_speedlarps_edit",
    ),
    path(
        "<slug:s>/manage/speedlarps/<int:num>/versions/",
        views_ow.orga_speedlarps_versions,
        name="orga_speedlarps_versions",
    ),
    path(
        "<slug:s>/manage/reading/",
        views_ow.orga_reading,
        name="orga_reading",
    ),
    path(
        "<slug:s>/manage/upload_expenses/",
        views_oa.orga_expenses_my,
        name="orga_expenses_my",
    ),
    path(
        "<slug:s>/manage/upload_expenses/edit/0",
        views_oa.orga_expenses_my_new,
        name="orga_expenses_my_new",
    ),
    path(
        "<slug:s>/manage/invoices/",
        views_oa.orga_invoices,
        name="orga_invoices",
    ),
    path(
        "<slug:s>/manage/invoices/confirm/<int:num>/",
        views_oa.orga_invoices_confirm,
        name="orga_invoices_confirm",
    ),
    path(
        "<slug:s>/manage/workshops/",
        views_oms.orga_workshops,
        name="orga_workshops",
    ),
    path(
        "<slug:s>/manage/workshops/modules/",
        views_oms.orga_workshop_modules,
        name="orga_workshop_modules",
    ),
    path(
        "<slug:s>/manage/workshops/modules/edit/<int:num>/",
        views_oms.orga_workshop_modules_edit,
        name="orga_workshop_modules_edit",
    ),
    path(
        "<slug:s>/manage/workshops/questions/",
        views_oms.orga_workshop_questions,
        name="orga_workshop_questions",
    ),
    path(
        "<slug:s>/manage/workshops/questions/edit/<int:num>/",
        views_oms.orga_workshop_questions_edit,
        name="orga_workshop_questions_edit",
    ),
    path(
        "<slug:s>/manage/workshops/options/",
        views_oms.orga_workshop_options,
        name="orga_workshop_options",
    ),
    path(
        "<slug:s>/manage/workshops/options/edit/<int:num>/",
        views_oms.orga_workshop_options_edit,
        name="orga_workshop_options_edit",
    ),
    path(
        "<slug:s>/manage/problems/",
        views_oms.orga_problems,
        name="orga_problems",
    ),
    path(
        "<slug:s>/manage/problems/edit/<int:num>/",
        views_oms.orga_problems_edit,
        name="orga_problems_edit",
    ),
    path(
        "<slug:s>/manage/progress_steps/",
        views_ow.orga_progress_steps,
        name="orga_progress_steps",
    ),
    path(
        "<slug:s>/manage/progress_steps/edit/<int:num>/",
        views_ow.orga_progress_steps_edit,
        name="orga_progress_steps_edit",
    ),
    path(
        "<slug:s>/manage/progress_steps/order/<int:num>/<int:order>/",
        views_ow.orga_progress_steps_order,
        name="orga_progress_steps_order",
    ),
    path(
        "<slug:s>/manage/px/deliveries/",
        views_ox.orga_px_deliveries,
        name="orga_px_deliveries",
    ),
    path(
        "<slug:s>/manage/px/deliveries/edit/<int:num>/",
        views_ox.orga_px_deliveries_edit,
        name="orga_px_deliveries_edit",
    ),
    path(
        "<slug:s>/manage/px/abilities/",
        views_ox.orga_px_abilities,
        name="orga_px_abilities",
    ),
    path(
        "<slug:s>/manage/px/abilities/edit/<int:num>/",
        views_ox.orga_px_abilities_edit,
        name="orga_px_abilities_edit",
    ),
    path(
        "<slug:s>/manage/px/ability_types/",
        views_ox.orga_px_ability_types,
        name="orga_px_ability_types",
    ),
    path(
        "<slug:s>/manage/px/ability_types/edit/<int:num>/",
        views_ox.orga_px_ability_types_edit,
        name="orga_px_ability_types_edit",
    ),
    path(
        "<slug:s>/manage/px/rules/",
        views_ox.orga_px_rules,
        name="orga_px_rules",
    ),
    path(
        "<slug:s>/manage/px/rules/edit/<int:num>/",
        views_ox.orga_px_rules_edit,
        name="orga_px_rules_edit",
    ),
    path(
        "<slug:s>/manage/px/rules/<int:num>/<int:order>/",
        views_ox.orga_px_rules_order,
        name="orga_px_rules_order",
    ),
    path(
        "<slug:s>/manage/px/modifiers/",
        views_ox.orga_px_modifiers,
        name="orga_px_modifiers",
    ),
    path(
        "<slug:s>/manage/px/modifiers/edit/<int:num>/",
        views_ox.orga_px_modifiers_edit,
        name="orga_px_modifiers_edit",
    ),
    path(
        "<slug:s>/manage/px/modifiers/<int:num>/<int:order>/",
        views_ox.orga_px_modifiers_order,
        name="orga_px_modifiers_order",
    ),
    path(
        "<slug:s>/manage/casting/",
        views_oca.orga_casting,
        name="orga_casting",
    ),
    path(
        "<slug:s>/manage/casting/<int:typ>/",
        views_oca.orga_casting,
        name="orga_casting",
    ),
    path(
        "<slug:s>/manage/casting/<int:typ>/<slug:tick>/",
        views_oca.orga_casting,
        name="orga_casting",
    ),
    path(
        "<slug:s>/manage/casting/toggle/<int:typ>/",
        views_oca.orga_casting_toggle,
        name="orga_casting_toggle",
    ),
    path(
        "<slug:s>/manage/accounting/",
        views_oa.orga_accounting,
        name="orga_accounting",
    ),
    path(
        "<slug:s>/manage/safety/",
        views_om.orga_safety,
        name="orga_safety",
    ),
    path(
        "<slug:s>/manage/diet/",
        views_om.orga_diet,
        name="orga_diet",
    ),
    path(
        "<slug:s>/manage/expenses/",
        views_oa.orga_expenses,
        name="orga_expenses",
    ),
    path(
        "<slug:s>/manage/expenses/edit/<int:num>/",
        views_oa.orga_expenses_edit,
        name="orga_expenses_edit",
    ),
    path(
        "<slug:s>/manage/expenses/approve/<int:num>/",
        views_oa.orga_expenses_approve,
        name="orga_expenses_approve",
    ),
    path(
        "<slug:s>/manage/payments/",
        views_oa.orga_payments,
        name="orga_payments",
    ),
    path(
        "<slug:s>/manage/payments/edit/<int:num>/",
        views_oa.orga_payments_edit,
        name="orga_payments_edit",
    ),
    path(
        "<slug:s>/manage/credits/",
        views_oa.orga_credits,
        name="orga_credits",
    ),
    path(
        "<slug:s>/manage/credits/edit/<int:num>/",
        views_oa.orga_credits_edit,
        name="orga_credits_edit",
    ),
    path(
        "<slug:s>/manage/tokens/",
        views_oa.orga_tokens,
        name="orga_tokens",
    ),
    path(
        "<slug:s>/manage/tokens/edit/<int:num>/",
        views_oa.orga_tokens_edit,
        name="orga_tokens_edit",
    ),
    path(
        "<slug:s>/manage/outflows/",
        views_oa.orga_outflows,
        name="orga_outflows",
    ),
    path(
        "<slug:s>/manage/outflows/edit/<int:num>/",
        views_oa.orga_outflows_edit,
        name="orga_outflows_edit",
    ),
    path(
        "<slug:s>/manage/inflows/",
        views_oa.orga_inflows,
        name="orga_inflows",
    ),
    path(
        "<slug:s>/manage/inflows/edit/<int:num>/",
        views_oa.orga_inflows_edit,
        name="orga_inflows_edit",
    ),
    path(
        "<slug:s>/manage/event/",
        views_oe.orga_event,
        name="orga_event",
    ),
    path(
        "<slug:s>/manage/appearance/",
        views_oe.orga_appearance,
        name="orga_appearance",
    ),
    path(
        "<slug:s>/manage/config/<slug:section>/",
        views_oe.orga_config,
        name="orga_config",
    ),
    path(
        "<slug:s>/manage/config/",
        views_oe.orga_config,
        name="orga_config",
    ),
    path(
        "<slug:s>/manage/backup/",
        views_oe.orga_backup,
        name="orga_backup",
    ),
    path(
        "<slug:s>/manage/upload/<slug:typ>/",
        views_oe.orga_upload,
        name="orga_upload",
    ),
    path(
        "<slug:s>/manage/upload/template/<slug:typ>/",
        views_oe.orga_upload_template,
        name="orga_upload_template",
    ),
    path(
        "<slug:s>/manage/preferences/",
        views_oe.orga_preferences,
        name="orga_preferences",
    ),
    path(
        "<slug:s>/manage/texts/",
        views_oe.orga_texts,
        name="orga_texts",
    ),
    path(
        "<slug:s>/manage/texts/edit/<int:num>/",
        views_oe.orga_texts_edit,
        name="orga_texts_edit",
    ),
    path(
        "<slug:s>/manage/buttons/",
        views_oe.orga_buttons,
        name="orga_buttons",
    ),
    path(
        "<slug:s>/manage/buttons/edit/<int:num>/",
        views_oe.orga_buttons_edit,
        name="orga_buttons_edit",
    ),
    path(
        "<slug:s>/manage/run/",
        views_oe.orga_run,
        name="orga_run",
    ),
    path(
        "<slug:s>/manage/roles/",
        views_oe.orga_roles,
        name="orga_roles",
    ),
    path(
        "<slug:s>/manage/roles/edit/<int:num>",
        views_oe.orga_roles_edit,
        name="orga_roles_edit",
    ),
    path(
        "<slug:s>/manage/lottery/",
        views_or.orga_lottery,
        name="orga_lottery",
    ),
    path(
        "<slug:s>/manage/mail/send",
        views_om.orga_send_mail,
        name="orga_send_mail",
    ),
    path(
        "<slug:s>/manage/mail/archive",
        views_om.orga_archive_email,
        name="orga_archive_email",
    ),
    path(
        "<slug:s>/manage/spam/",
        views_om.orga_spam,
        name="orga_spam",
    ),
    path(
        "<slug:s>/manage/persuade/",
        views_om.orga_persuade,
        name="orga_persuade",
    ),
    path(
        "<slug:s>/manage/copy/",
        views_oy.orga_copy,
        name="orga_copy",
    ),
    path(
        "<slug:s>/manage/questions/",
        views_om.orga_questions,
        name="orga_questions",
    ),
    path(
        "<slug:s>/manage/questions/<int:r>/answer/",
        views_om.orga_questions_answer,
        name="orga_questions_answer",
    ),
    path(
        "<slug:s>/manage/questions/<int:r>/close/",
        views_om.orga_questions_close,
        name="orga_questions_close",
    ),
    path(
        "<slug:s>/manage/features/",
        views_oe.orga_features,
        name="orga_features",
    ),
    path(
        "<slug:s>/manage/features/<slug:slug>/on/",
        views_oe.orga_features_on,
        name="orga_features_on",
    ),
    path(
        "<slug:s>/manage/features/<slug:slug>/off/",
        views_oe.orga_features_off,
        name="orga_features_off",
    ),
    path(
        "<slug:s>/manage/sensitive/",
        views_om.orga_sensitive,
        name="orga_sensitive",
    ),
    path(
        "<slug:s>/manage/multichoice/available",
        views_ow.orga_multichoice_available,
        name="orga_multichoice_available",
    ),
    path(
        "<slug:s>/manage/factions/available",
        views_ow.orga_factions_available,
        name="orga_factions_available",
    ),
    path(
        "<slug:s>/manage/export/<slug:nm>",
        views_ow.orga_export,
        name="orga_export",
    ),
    path(
        "<slug:s>/manage/suggestions/<slug:perm>/",
        views_mg.orga_close_suggestion,
        name="orga_close_suggestion",
    ),
    path(
        "<slug:s>/manage/<slug:nm>/version/<int:num>/",
        views_ow.orga_version,
        name="orga_version",
    ),
    path(
        "<slug:s>/manage/warehouse/area/",
        views_oms.orga_warehouse_area,
        name="orga_warehouse_area",
    ),
    path(
        "<slug:s>/manage/warehouse/area/edit/<int:num>/",
        views_oms.orga_warehouse_area_edit,
        name="orga_warehouse_area_edit",
    ),
    path(
        "<slug:s>/manage/warehouse/area/assignments/<int:num>/",
        views_oms.orga_warehouse_area_assignments,
        name="orga_warehouse_area_assignments",
    ),
    path(
        "<slug:s>/manage/warehouse/checks/",
        views_oms.orga_warehouse_checks,
        name="orga_warehouse_checks",
    ),
    path(
        "<slug:s>/manage/warehouse/manifest/",
        views_oms.orga_warehouse_manifest,
        name="orga_warehouse_manifest",
    ),
    path(
        "<slug:s>/manage/warehouse/assignment/manifest/",
        views_oms.orga_warehouse_assignment_manifest,
        name="orga_warehouse_assignment_manifest",
    ),
    path(
        "<slug:s>/manage/warehouse/assignment/area/<int:num>/",
        views_oms.orga_warehouse_assignment_area,
        name="orga_warehouse_assignment_area",
    ),
    path(
        "<slug:s>/manage/warehouse/assignment/edit/<int:num>/",
        views_oms.orga_warehouse_assignment_item_edit,
        name="orga_warehouse_assignment_item_edit",
    ),
    path(
        "<slug:s>/<int:n>/",
        views_mg.orga_redirect,
        name="orga_redirect",
    ),
    path(
        "<slug:s>/<int:n>/<path:p>",
        views_mg.orga_redirect,
        name="orga_redirect",
    ),
]
